### ISSUE TITLE
The flags of  "export database" don't work

### ISSUE THREAD

**Issue by viktor4116** [orientechnologies/orientdb#2096]
The "export database" command doesn't recognize its documented flags.
(Flags taken from https://github.com/orientechnologies/orientdb/wiki/Console-Command-Export)

Example:
create database remote:localhost/test5 root pass plocal
create class User extends V
create vertex User set name = 'Luca'
export database /tmp/test5.out -excludeAll -includeClass User
> 2014-02-06 20:45:31:991 WARN Unrecognized option -excludeAll, skipped [ODatabaseExport]
> 2014-02-06 20:45:31:992 WARN Unrecognized option -includeClass, skipped [ODatabaseExport]

**Comment by mathieubodin** [comment]
Issue is still occurring on 2.0-rc1.

**Comment by lvca** [comment]
This is a documentation problem I've just fixed (https://github.com/orientechnologies/orientdb/wiki/Console-Command-Export): flags need = not space. Try with:

    export database /tmp/test5.out -excludeAll -includeClass User

**Comment by mathieubodin** [comment]
> Try with:

> export database /tmp/test5.out -excludeAll -includeClass User

Just teasing, but, well, it's embarrassing, isn't it ! 

I think you missed something : As ```-excludeAll``` flag isn't recognized, all other flags are pointless in my use case : correct me if I'm wrong, whenever I want to export only what's related to the OUser class I might use the following command :

```
export database /tmp/export_test_fix_#2096 -excludeAll -includeClass=OUser
```

Here is the output for this kind of command :
```
Exporting current database to: database /tmp/export_test_fix_#2096 -excludeAll -includeClass=OUser in GZipped JSON format ...

2015-01-09 13:40:53:205 WARNING Unrecognized option -excludeAll, skipped [ODatabaseExport]
Started export of database 'GratefulDeadConcerts' to /tmp/export_test_fix_#2096.json.gz...
Exporting database info...OK
Exporting clusters...OK (14 clusters)
Exporting schema...OK (13 classes)
Exporting records...
- Cluster 'internal' (id=0)...OK (records=0/3)
- Cluster 'index' (id=1)...OK (records=0/2)
- Cluster 'manindex' (id=2)...OK (records=0/1)
- Cluster 'default' (id=3)...OK (records=0/0)
- Cluster 'orole' (id=4)...OK (records=0/3)
- Cluster 'ouser' (id=5)...OK (records=3/3)
- Cluster 'ofunction' (id=6)...OK (records=0/0)
- Cluster 'oschedule' (id=7)...OK (records=0/0)
- Cluster 'orids' (id=8)...OK (records=0/0)
- Cluster 'v' (id=9)...OK (records=0/809)
- Cluster 'e' (id=10)...OK (records=0/0)
- Cluster 'followed_by' (id=11)...OK (records=0/7047)
- Cluster 'written_by' (id=12)...OK (records=0/501)
- Cluster 'sung_by' (id=13)...OK (records=0/501)

Done. Exported 3 of total 8870 records

Exporting index info...
OK (3 indexes)
Exporting manual indexes content...
- Exporting index dictionary ...OK (entries=0)
OK (1 manual indexes)

Database export completed in 2025ms
```
Note the warning. Fortunately, only records of class OUser are exported, but also some others entries like info, clusters, schema, etc...

**Comment by lvca** [comment]
This seems a bug. Can you try this?

    export database /tmp/export_test_fix_#2096 -excludeAll -includeCluster=ouser -includeClass=OUser

**Comment by mathieubodin** [comment]
Here is what I got :
```
{
   "info": {
      "name": "GratefulDeadConcerts",
      "default-cluster-id": 3,
      "exporter-version": 11,
      "engine-version": "2.0-rc1",
      "engine-build": "UNKNOWN@r; 2014-12-17 21:54:12+0000",
      "storage-config-version": 14,
      "schema-version": 4,
      "mvrbtree-version": 3,
      "schemaRecordId": "#0:1",
      "indexMgrRecordId": "#0:2"
   },
   "clusters": [
      {
         "name": "ouser",
         "id": 5
      }
   ],
   "schema": {
      "version": 1,
      "classes": []
   },
   "records": [
      {
         "@type": "d",
         "@rid": "#5:0",
         "@version": 1,
         "@class": "OUser",
         "name": "admin",
         "password": "{SHA-256}8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918",
         "status": "ACTIVE",
         "roles": [
            "#4:0"
         ],
         "@fieldTypes": "roles=n"
      },
      {
         "@type": "d",
         "@rid": "#5:1",
         "@version": 1,
         "@class": "OUser",
         "name": "reader",
         "password": "{SHA-256}3D0941964AA3EBDCB00CCEF58B1BB399F9F898465E9886D5AEC7F31090A0FB30",
         "status": "ACTIVE",
         "roles": [
            "#4:1"
         ],
         "@fieldTypes": "roles=n"
      },
      {
         "@type": "d",
         "@rid": "#5:2",
         "@version": 1,
         "@class": "OUser",
         "name": "writer",
         "password": "{SHA-256}B93006774CBDD4B299389A03AC3D88C3A76B460D538795BC12718011A909FBA5",
         "status": "ACTIVE",
         "roles": [
            "#4:2"
         ],
         "@fieldTypes": "roles=n"
      }
   ],
   "indexes": [],
   "manualIndexes": [
      {
         "name": "dictionary",
         "content": []
      }
   ]
}
```
Hope it might help.

**Comment by lvca** [comment]
Reproduces, thanks. Fixing...

**Comment by mathieubodin** [comment]
Cool thx
