### ISSUE TITLE
Property '' Not Exists Error when using ALTER PROPERTY

### ISSUE THREAD

**Issue by bfausett** [orientechnologies/orientdb#3134]
OrientDB Version: 1.7.9

I have created a Graph database along with several vertices in a specific Class (Books).  Each vertices has 5 properties, one being "title", which stores the title of the book. I have created an index on the "title" property within the Books class. I am able to see this property that exists by the following means:

1- Query vertices from the Book class using the Book.title in the where clause.  Vertices are returned based upon the criteria I specify.

2- class info Books - which lists the properties

INDEXES (2 altogether)
-------------------------------+----------------+
 NAME                          | PROPERTIES     |
-------------------------------+----------------+
 Books.fullName              | fullName       |
 Books.title                 | title          |
-------------------------------+----------------+

I realized that I wanted to be able to search for book titles in a case insensitive manner.  I found within the OrientDB documentation the ALTER PROPERTY command.  Each time I try to execute the following command:

ALTER PROPERTY Books.title COLLATE "ci"

I then get the following error:

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: P
roperty 'Books.title' not exists.

How can I get past this error?  Any help would be appreciated.

Thanks,
bfausett

**Comment by na2014** [comment]
I'm having the same problem, and am using the sample default GratefulDeadConcerts db.  I'm also trying to change the collation to be case insensitive.  I try the following:

ALTER PROPERTY V.name COLLATE ci

I get the error:

com.orientechnologies.orient.core.exception.OCommandExecutionException: Property 'V.name' not exists

The output of info and info class V are below.  

Has anyone figured this out yet?  It's frustrating to be stuck on something so basic.  


orientdb {db=GratefulDeadConcerts}> info

Current database: GratefulDeadConcerts (url=remote:localhost/GratefulDeadConcerts)

DISTRIBUTED CONFIGURATION: none (OrientDB is running in standalone mode)

DATABASE PROPERTIES
--------------------------------+----------------------------------------------------+
 NAME                           | VALUE                                              |
--------------------------------+----------------------------------------------------+
 Name                           | null                                               |
 Version                        | 14                                                 |
 Conflict Strategy              | version                                            |
 Date format                    | yyyy-MM-dd                                         |
 Datetime format                | yyyy-MM-dd HH:mm:ss                                |
 Timezone                       | GMT                                                |
 Locale Country                 | UK                                                 |
 Locale Language                | EN                                                 |
 Charset                        | UTF-8                                              |
 Schema RID                     | #0:1                                               |
 Index Manager RID              | #0:2                                               |
 Dictionary RID                 | null                                               |
--------------------------------+----------------------------------------------------+

CLUSTERS
----------------------------------------------+-------+-------------------+----------------+
 NAME                                         | ID    | CONFLICT STRATEGY | RECORDS        |
----------------------------------------------+-------+-------------------+----------------+
 _studio                                      |    14 |                   |              0 |
 default                                      |     3 |                   |              0 |
 e                                            |    10 |                   |              0 |
 followed_by                                  |    11 |                   |           7047 |
 index                                        |     1 |                   |              2 |
 internal                                     |     0 |                   |              3 |
 manindex                                     |     2 |                   |              1 |
 ofunction                                    |     6 |                   |              0 |
 orids                                        |     8 |                   |              0 |
 orole                                        |     4 |                   |              3 |
 oschedule                                    |     7 |                   |              0 |
 ouser                                        |     5 |                   |              3 |
 sung_by                                      |    13 |                   |            501 |
 v                                            |     9 |                   |            809 |
 written_by                                   |    12 |                   |            501 |
----------------------------------------------+-------+-------------------+----------------+
 TOTAL = 15                                                               |           8870 |
------------------------------------------------------+-------------------+----------------+

CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
 NAME                                         | SUPERCLASS                         | CLUSTERS   | RECORDS        |
----------------------------------------------+------------------------------------+------------+----------------+
 _studio                                      |                                    | 14         |              0 |
 E                                            |                                    | 10         |              0 |
 followed_by                                  | E                                  | 11         |           7047 |
 OFunction                                    |                                    | 6          |              0 |
 OIdentity                                    |                                    | -          |              0 |
 ORestricted                                  |                                    | -          |              0 |
 ORIDs                                        |                                    | 8          |              0 |
 ORole                                        | OIdentity                          | 4          |              3 |
 OSchedule                                    |                                    | 7          |              0 |
 OTriggered                                   |                                    | -          |              0 |
 OUser                                        | OIdentity                          | 5          |              3 |
 sung_by                                      | E                                  | 13         |            501 |
 V                                            |                                    | 9          |            809 |
 written_by                                   | E                                  | 12         |            501 |
----------------------------------------------+------------------------------------+------------+----------------+
 TOTAL = 14                                                                                                 8864 |
----------------------------------------------+------------------------------------+------------+----------------+

INDEXES
----------------------------------------------+------------+-----------------------+----------------+------------+
 NAME                                         | TYPE       |         CLASS         |     FIELDS     | RECORDS    |
----------------------------------------------+------------+-----------------------+----------------+------------+
 dictionary                                   | DICTIONARY |                       |                |          0 |
 ORole.name                                   | UNIQUE     | ORole                 | name           |          3 |
 OUser.name                                   | UNIQUE     | OUser                 | name           |          3 |
----------------------------------------------+------------+-----------------------+----------------+------------+
 TOTAL = 3                                                                                                     6 |
-----------------------------------------------------------------------------------------------------------------+
orientdb {db=GratefulDeadConcerts}> info class V

Class................: V
Default cluster......: v (id=9)
Supported cluster ids: [9]
Cluster selection....: balanced
orientdb {db=GratefulDeadConcerts}>

**Comment by na2014** [comment]
Since this item was closed, and I don't know how to reopen, I created ticket 3400
https://github.com/orientechnologies/orientdb/issues/3400

**Comment by bfausett** [comment]
It has been quite frustrating.  I've opened three issues for this and each time they close the issue without it being resolved.

I'm having other issues as well with Traversal that haven't been resolved.  I've worked with other graph db's and have never had this difficult of a time.  Not sure OrientDB is the correct solution for what I'm trying to accomplish because of the lack of basic graph functionality and support or valid documentation.

**Comment by na2014** [comment]
My issue was resolved in the other post, though the process was rather confusing.  Take a look and see if it helps at all.

**Comment by lvca** [comment]
Please don't spam with the same issue multiple time, this drives us crazy. If an issue has been closed and you think it's not correct, please comment it to reopen. So we don't loose history.

**Comment by bfausett** [comment]
No problem.  However, I had mentioned to reopen the issue and it's still not re-opened nor resolved.

**Comment by lvca** [comment]
@bfausett The problem is super clear:

'Books.title' cannot be created on class : 'Books' because field: 'title' is absent in class definition.

You have no "title" field in Books class. Seems you names the fields with the class as prefix. I see this by looking at your output:

```
 info Class Books

Class................: Books
Super class..........: V
Default cluster......: Books (id=11)
Supported cluster ids: [11]
Cluster selection....: round-robin

INDEXES (3 altogether)
-------------------------------+----------------+
NAME | PROPERTIES |
-------------------------------+----------------+
Books.fullName | fullName |
Books.BooksId | BooksId |
Books.title | title |
-------------------------------+----------------+
```

So create a property "title" in Books:

```
orientdb> crete property Books.title STRING
```

**Comment by bfausett** [comment]
I followed the documentation when creating vertices with multiple properties using the examples in your documentation.  Perhaps I have missed something along the way though.  Here is how I created the vertices:

                               OrientGraph bGraph = new OrientGraph(dbUrl, "admin", "admin");
				
				// create Map for all node/vertex properties
				Map<String, Object> nodeProps = new HashMap<String, Object>();

				
				//There is a loop here that goes through a table full of books

				// first set all the properties of the book vertex
				nodeProps.put("booksId", orabook.getbooksId());
				nodeProps.put("fullName", orabook.getFullName());
				nodeProps.put("title", orabook.getTitle());
				
				// create the vertex along with all the properties in the Class Books
				mimoGraph.addVertex("class:Books", nodeProps);

				bGraph.commit();
				
				//loop ends here
                                bGraph.shutdown();

Here are the import statements.  Note that within this same class I am creating Indexes and Edges within the same database as well.

import com.orientechnologies.orient.core.sql.OCommandSQL;
import com.tinkerpop.blueprints.Parameter;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientVertex;

Am I doing something wrong?  
Thanks!

**Comment by bfausett** [comment]
Also, note that I am able to return a vertex based upon a search for a value in a specific property.  So it appears the property does exist.  See the code below:

public Book findByTitle(String title) {
		Book returnBook = null;

		try {
			for (Vertex bVertex : bGraph.getVertices("Books.title", title)) {

				if (bVertex != null) {
					returnBook = new Book(bVertex.getId().toString(), Long.parseLong(bVertex.getProperty(
							"BooksId").toString()), bVertex.getProperty("fullName").toString(), conVertex.getProperty("title").toString());
				}

			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		return returnBook;

	}

I have tested this over and over and am able to get results back....and quite fast I might add.  The speed is quite impressive once you put an Index on the property.

thanks!
