### ISSUE TITLE
Support disabling of validation to import a database remotely

### ISSUE THREAD

**Issue by darkredz** [orientechnologies/orientdb#3226]
I just downloaded the latest 2.0-rc1 from the official website. I tried to reimport data that is exported from 2.0-M3 with schema and data through the console: import database backup.gz. 
It seems that it failed to import the data after creating the schema, and indexes aren't created as well.

I tried with 2 database, and it had the same error where there's field of LINKLIST type.
Error: has been declared as LINKLIST but contains a null record (probably a deleted record?)

Here's the console log:
Connecting to database [remote:localhost/TcStatistic] with user 'root'...OK
orientdb {db=TcStatistic}> import database TcStatistic_new.gz                                                                 

Importing database database TcStatistic_new.gz...
Started import of database 'remote:localhost/TcStatistic' from TcStatistic_new.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class _studio was removed.
- Class ORestricted was removed.
- Class OTriggered was removed.
- Class OSchedule was removed.
- Class ORIDs was removed.
- Class OFunction was removed.
Removed 6 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster '_studio'...OK, assigned id=9
- Creating cluster 'commentanalysis'...OK, assigned id=13
- Creating cluster 'commentphrases'...OK, assigned id=14
Rebuilding indexes of truncated clusters ...
Done 2 indexes were rebuilt.
Done. Imported 10 clusters
Importing database schema...OK (11 classes)

Importing records...Error importing record #-1:-1. Source line 0, column 34807
Error on database import happened just before line 0, column 34808
com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:441)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:396)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:282)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1852)
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:355)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.createRecord(OStorageRemoteThread.java:243)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1712)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2270)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1672)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1663)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:71)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecord(ODatabaseImport.java:1291)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecords(ODatabaseImport.java:1187)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:425)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1538)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)
Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'CommentAnalysis.phrases' has been declared as LINKLIST but contains a null record (probably a deleted record?)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateLink(ODocument.java:443)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateLinkCollection(ODocument.java:430)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:275)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1905)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2214)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2107)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:349)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1373)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:350)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'TcStatistic' from file: TcStatistic_new.gz

Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.

Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'CommentAnalysis.phrases' has been declared as LINKLIST but contains a null record (probably a deleted record?)

Here's the content of the gzip backup json content:
{"info":{"name":"TcStatistic","default-cluster-id":3,"exporter-version":10,"engine-version":"2.0-M3","engine-build":"UNKNOWN@r; 2014-11-18 18:49:47+0000","storage-config-version":13,"schema-version":4,"mvrbtree-version":3,"schemaRecordId":"#0:1","indexMgrRecordId":"#0:2"},"clusters":[{"name":"internal","id":0},{"name":"index","id":1},{"name":"manindex","id":2},{"name":"default","id":3},{"name":"orole","id":4},{"name":"ouser","id":5},{"name":"ofunction","id":6},{"name":"oschedule","id":7},{"name":"orids","id":8},{"name":"_studio","id":9},{"name":"commentanalysis","id":13},{"name":"commentphrases","id":14}],"schema":{"version":4,"classes":[{"name":"CommentAnalysis","default-cluster-id":13,"cluster-ids":[13],"cluster-selection":"round-robin","properties":[{"name":"api_status","type":"SHORT","collate":"default"},{"name":"bpid","type":"INTEGER","collate":"default"},{"name":"cid","type":"INTEGER","collate":"default"},{"name":"created","type":"INTEGER","collate":"default"},{"name":"language","type":"STRING","collate":"default"},{"name":"language_score","type":"SHORT","collate":"default"},{"name":"phrases","type":"LINKLIST","linked-class":"CommentPhrases","collate":"default"},{"name":"rating","type":"SHORT","collate":"default"},{"name":"review_type","type":"SHORT","collate":"default"},{"name":"sentiment_polarity","type":"SHORT","collate":"default"},{"name":"sentiment_score","type":"DOUBLE","collate":"default"},{"name":"status","type":"SHORT","collate":"default"},{"name":"uid","type":"INTEGER","collate":"default"}]},{"name":"CommentPhrases","default-cluster-id":14,"cluster-ids":[14],"cluster-selection":"round-robin","properties":[{"name":"is_intensified","type":"BOOLEAN","collate":"default"},{"name":"is_negated","type":"BOOLEAN","collate":"default"},{"name":"parent","type":"LINK","linked-class":"CommentAnalysis","collate":"default"},{"name":"sentiment_polarity","type":"SHORT","collate":"default"},{"name":"sentiment_score","type":"DOUBLE","collate":"default"},{"name":"title","type":"STRING","collate":"default"}]},{"name":"OFunction","default-cluster-id":6,"cluster-ids":[6],"cluster-selection":"round-robin","properties":[{"name":"code","type":"STRING","collate":"default"},{"name":"idempotent","type":"BOOLEAN","collate":"default"},{"name":"language","type":"STRING","collate":"default"},{"name":"name","type":"STRING","collate":"default"},{"name":"parameters","type":"EMBEDDEDLIST","linked-type":"STRING","collate":"default"}]},{"name":"OIdentity","default-cluster-id":-1,"cluster-ids":[-1],"abstract":true,"cluster-selection":"round-robin"},{"name":"ORIDs","default-cluster-id":8,"cluster-ids":[8],"cluster-selection":"round-robin"},{"name":"ORestricted","default-cluster-id":-1,"cluster-ids":[-1],"abstract":true,"cluster-selection":"round-robin","properties":[{"name":"_allow","type":"LINKSET","linked-class":"OIdentity","collate":"default"},{"name":"_allowDelete","type":"LINKSET","linked-class":"OIdentity","collate":"default"},{"name":"_allowRead","type":"LINKSET","linked-class":"OIdentity","collate":"default"},{"name":"_allowUpdate","type":"LINKSET","linked-class":"OIdentity","collate":"default"}]},{"name":"ORole","default-cluster-id":4,"cluster-ids":[4],"super-class":"OIdentity","cluster-selection":"round-robin","properties":[{"name":"inheritedRole","type":"LINK","linked-class":"ORole","collate":"default"},{"name":"mode","type":"BYTE","collate":"default"},{"name":"name","type":"STRING","mandatory":true,"not-null":true,"collate":"ci"},{"name":"rules","type":"EMBEDDEDSET","collate":"default"}]},{"name":"OSchedule","default-cluster-id":7,"cluster-ids":[7],"cluster-selection":"round-robin","properties":[{"name":"arguments","type":"EMBEDDEDMAP","collate":"default"},{"name":"function","type":"LINK","mandatory":true,"not-null":true,"linked-class":"OFunction","collate":"default"},{"name":"name","type":"STRING","mandatory":true,"not-null":true,"collate":"default"},{"name":"rule","type":"STRING","mandatory":true,"not-null":true,"collate":"default"},{"name":"start","type":"BOOLEAN","collate":"default"},{"name":"starttime","type":"DATETIME","collate":"default"},{"name":"status","type":"STRING","collate":"default"}]},{"name":"OTriggered","default-cluster-id":-1,"cluster-ids":[-1],"abstract":true,"cluster-selection":"round-robin"},{"name":"OUser","default-cluster-id":5,"cluster-ids":[5],"super-class":"OIdentity","cluster-selection":"round-robin","properties":[{"name":"name","type":"STRING","mandatory":true,"not-null":true,"collate":"ci"},{"name":"password","type":"STRING","mandatory":true,"not-null":true,"collate":"default"},{"name":"roles","type":"LINKSET","linked-class":"ORole","collate":"default"},{"name":"status","type":"STRING","mandatory":true,"not-null":true,"collate":"default"}]},{"name":"_studio","default-cluster-id":9,"cluster-ids":[9],"cluster-selection":"round-robin"}]},"records":[{"@type":"b","@rid":"#0:0","@version":1,"value":"AAAAAA=="},{"@type":"d","@rid":"#0:1","@version":496,"schemaVersion":4,"classes":[{"@type":"d","@version":0,"name":"OTriggered","shortName":null,"defaultClusterId":-1,"clusterIds":[-1],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":true,"properties":[],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"ORole","shortName":null,"defaultClusterId":4,"clusterIds":[4],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[{"@type":"d","@version":0,"name":"mode","type":17,"globalId":1,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"rules","type":11,"globalId":2,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"inheritedRole","type":13,"globalId":3,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"ORole","customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"name","type":7,"globalId":0,"mandatory":true,"readonly":false,"notNull":true,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"ci"}],"superClass":"OIdentity","customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"ORIDs","shortName":null,"defaultClusterId":8,"clusterIds":[8],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"OUser","shortName":null,"defaultClusterId":5,"clusterIds":[5],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[{"@type":"d","@version":0,"name":"name","type":7,"globalId":0,"mandatory":true,"readonly":false,"notNull":true,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"ci"},{"@type":"d","@version":0,"name":"status","type":7,"globalId":6,"mandatory":true,"readonly":false,"notNull":true,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"password","type":7,"globalId":4,"mandatory":true,"readonly":false,"notNull":true,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"roles","type":15,"globalId":5,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"ORole","customFields":null,"collate":"default"}],"superClass":"OIdentity","customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"OIdentity","shortName":null,"defaultClusterId":-1,"clusterIds":[-1],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":true,"properties":[],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"OFunction","shortName":null,"defaultClusterId":6,"clusterIds":[6],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[{"@type":"d","@version":0,"name":"language","type":7,"globalId":12,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"parameters","type":10,"globalId":14,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedType":7,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"name","type":7,"globalId":0,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"idempotent","type":0,"globalId":13,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"code","type":7,"globalId":11,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"}],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"ORestricted","shortName":null,"defaultClusterId":-1,"clusterIds":[-1],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":true,"properties":[{"@type":"d","@version":0,"name":"_allowDelete","type":15,"globalId":10,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"OIdentity","customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"_allowRead","type":15,"globalId":8,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"OIdentity","customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"_allow","type":15,"globalId":7,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"OIdentity","customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"_allowUpdate","type":15,"globalId":9,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"OIdentity","customFields":null,"collate":"default"}],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"CommentAnalysis","shortName":null,"defaultClusterId":13,"clusterIds":[13],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[{"@type":"d","@version":0,"name":"phrases","type":14,"globalId":40,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"CommentPhrases","customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"review_type","type":2,"globalId":35,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"status","type":2,"globalId":43,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"uid","type":1,"globalId":34,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"cid","type":1,"globalId":29,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"language","type":7,"globalId":12,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"sentiment_score","type":5,"globalId":31,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"language_score","type":2,"globalId":33,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"sentiment_polarity","type":2,"globalId":32,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"created","type":1,"globalId":42,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"api_status","type":2,"globalId":44,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"bpid","type":1,"globalId":30,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"rating","type":2,"globalId":41,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"}],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"CommentPhrases","shortName":null,"defaultClusterId":14,"clusterIds":[14],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[{"@type":"d","@version":0,"name":"sentiment_score","type":5,"globalId":31,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"parent","type":13,"globalId":39,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"linkedClass":"CommentAnalysis","customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"is_negated","type":0,"globalId":37,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"is_intensified","type":0,"globalId":38,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"sentiment_polarity","type":2,"globalId":32,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"title","type":7,"globalId":36,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"}],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"OSchedule","shortName":null,"defaultClusterId":7,"clusterIds":[7],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[{"@type":"d","@version":0,"name":"start","type":0,"globalId":19,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"status","type":7,"globalId":6,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"starttime","type":6,"globalId":18,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"arguments","type":12,"globalId":16,"mandatory":false,"readonly":false,"notNull":false,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"name","type":7,"globalId":0,"mandatory":true,"readonly":false,"notNull":true,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"function","type":13,"globalId":17,"mandatory":true,"readonly":false,"notNull":true,"min":null,"max":null,"regexp":null,"linkedClass":"OFunction","customFields":null,"collate":"default"},{"@type":"d","@version":0,"name":"rule","type":7,"globalId":15,"mandatory":true,"readonly":false,"notNull":true,"min":null,"max":null,"regexp":null,"customFields":null,"collate":"default"}],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"},{"@type":"d","@version":0,"name":"_studio","shortName":null,"defaultClusterId":9,"clusterIds":[9],"clusterSelection":"round-robin","overSize":0.0,"strictMode":false,"abstract":false,"properties":[],"superClass":null,"customFields":null,"@fieldTypes":"overSize=f,properties=e"}],"globalProperties":[{"@type":"d","@version":0,"name":"name","type":"STRING","id":0},{"@type":"d","@version":0,"name":"mode","type":"BYTE","id":1},{"@type":"d","@version":0,"name":"rules","type":"EMBEDDEDSET","id":2},{"@type":"d","@version":0,"name":"inheritedRole","type":"LINK","id":3},{"@type":"d","@version":0,"name":"password","type":"STRING","id":4},{"@type":"d","@version":0,"name":"roles","type":"LINKSET","id":5},{"@type":"d","@version":0,"name":"status","type":"STRING","id":6},{"@type":"d","@version":0,"name":"_allow","type":"LINKSET","id":7},{"@type":"d","@version":0,"name":"_allowRead","type":"LINKSET","id":8},{"@type":"d","@version":0,"name":"_allowUpdate","type":"LINKSET","id":9},{"@type":"d","@version":0,"name":"_allowDelete","type":"LINKSET","id":10},{"@type":"d","@version":0,"name":"code","type":"STRING","id":11},{"@type":"d","@version":0,"name":"language","type":"STRING","id":12},{"@type":"d","@version":0,"name":"idempotent","type":"BOOLEAN","id":13},{"@type":"d","@version":0,"name":"parameters","type":"EMBEDDEDLIST","id":14},{"@type":"d","@version":0,"name":"rule","type":"STRING","id":15},{"@type":"d","@version":0,"name":"arguments","type":"EMBEDDEDMAP","id":16},{"@type":"d","@version":0,"name":"function","type":"LINK","id":17},{"@type":"d","@version":0,"name":"starttime","type":"DATETIME","id":18},{"@type":"d","@version":0,"name":"start","type":"BOOLEAN","id":19},{"@type":"d","@version":0,"name":"tags","type":"EMBEDDEDSET","id":20},{"@type":"d","@version":0,"name":"createdAt","type":"DATETIME","id":21},{"@type":"d","@version":0,"name":"fullname","type":"STRING","id":22},{"@type":"d","@version":0,"name":"orderID","type":"STRING","id":23},{"@type":"d","@version":0,"name":"nick","type":"STRING","id":24},{"@type":"d","@version":0,"name":"slug","type":"STRING","id":25},{"@type":"d","@version":0,"name":"reviews","type":"LINKLIST","id":26},{"@type":"d","@version":0,"name":"category","type":"LINK","id":27},{"@type":"d","@version":0,"name":"totalReviews","type":"INTEGER","id":28},{"@type":"d","@version":0,"name":"cid","type":"INTEGER","id":29},{"@type":"d","@version":0,"name":"bpid","type":"INTEGER","id":30},{"@type":"d","@version":0,"name":"sentiment_score","type":"DOUBLE","id":31},{"@type":"d","@version":0,"name":"sentiment_polarity","type":"SHORT","id":32},{"@type":"d","@version":0,"name":"language_score","type":"SHORT","id":33},{"@type":"d","@version":0,"name":"uid","type":"INTEGER","id":34},{"@type":"d","@version":0,"name":"review_type","type":"SHORT","id":35},{"@type":"d","@version":0,"name":"title","type":"STRING","id":36},{"@type":"d","@version":0,"name":"is_negated","type":"BOOLEAN","id":37},{"@type":"d","@version":0,"name":"is_intensified","type":"BOOLEAN","id":38},{"@type":"d","@version":0,"name":"parent","type":"LINK","id":39},{"@type":"d","@version":0,"name":"phrases","type":"LINKLIST","id":40},{"@type":"d","@version":0,"name":"rating","type":"SHORT","id":41},{"@type":"d","@version":0,"name":"created","type":"INTEGER","id":42},{"@type":"d","@version":0,"name":"status","type":"SHORT","id":43},{"@type":"d","@version":0,"name":"api_status","type":"SHORT","id":44}],"@fieldTypes":"classes=e"},{"@type":"d","@rid":"#0:2","@version":25,"indexes":[{"@type":"d","@version":0,"type":"NOTUNIQUE","name":"CommentAnalysis.created_status_bpid_sentiment_score_sentiment_polarity_language_score_rating","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_score","keyType":"DOUBLE","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_polarity","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"language_score","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"rating","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","clusters":["commentanalysis"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"NOTUNIQUE","name":"CommentAnalysis.created","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","clusters":["commentanalysis"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"DICTIONARY_HASH_INDEX","name":"CommentAnalysis.cid","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","field":"cid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","clusters":["commentanalysis"],"mapRid":"#1:7","algorithm":"SBTREE","valueContainerAlgorithm":"NONE","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"NOTUNIQUE","name":"CommentAnalysis.created_status_bpid","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","clusters":["commentanalysis"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"FULLTEXT","name":"CommentPhrases.title_fulltext","indexDefinition":{"@type":"d","@version":0,"className":"CommentPhrases","field":"title","keyType":"STRING","collate":"default","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","clusters":["commentphrases"],"mapRid":null,"algorithm":"LUCENE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"UNIQUE","name":"ORole.name","indexDefinition":{"@type":"d","@version":0,"className":"ORole","field":"name","keyType":"STRING","collate":"ci","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","clusters":["orole"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"NONE","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"NOTUNIQUE_HASH_INDEX","name":"CommentAnalysis.bpid","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","clusters":["commentanalysis"],"mapRid":"#1:5","algorithm":"SBTREE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"UNIQUE","name":"OUser.name","indexDefinition":{"@type":"d","@version":0,"className":"OUser","field":"name","keyType":"STRING","collate":"ci","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","clusters":["ouser"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"NONE","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"DICTIONARY","name":"dictionary","indexDefinition":{"@type":"d","@version":0,"keyTypes":["STRING"],"collate":"default","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OSimpleKeyIndexDefinition","clusters":[],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"NONE","metadata":{"@type":"d","@version":0,"durableInNonTxMode":true,"trackMode":"FULL"},"@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"NOTUNIQUE","name":"CommentAnalysis.bpid_sentiment_score_sentiment_polarity_language_score_status_rating","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_score","keyType":"DOUBLE","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_polarity","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"language_score","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"rating","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","clusters":["commentanalysis"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"NOTUNIQUE","name":"CommentAnalysis.created_bpid_status_rating","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"rating","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","clusters":["commentanalysis"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"},{"@type":"d","@version":0,"type":"NOTUNIQUE","name":"CommentAnalysis.bpid_status","indexDefinition":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","clusters":["commentanalysis"],"mapRid":null,"algorithm":"SBTREE","valueContainerAlgorithm":"SBTREEBONSAISET","@fieldTypes":"clusters=e"}],"@fieldTypes":"indexes=e"},{"@type":"b","@rid":"#1:0","@version":1,"value":""},{"@type":"b","@rid":"#1:1","@version":1,"value":""},{"@type":"b","@rid":"#1:2","@version":1,"value":""},{"@type":"b","@rid":"#1:3","@version":1,"value":""},{"@type":"b","@rid":"#1:4","@version":1,"value":""},{"@type":"b","@rid":"#1:5","@version":1,"value":""},{"@type":"b","@rid":"#1:6","@version":1,"value":""},{"@type":"b","@rid":"#1:7","@version":1,"value":""},{"@type":"b","@rid":"#1:8","@version":1,"value":""},{"@type":"b","@rid":"#1:9","@version":1,"value":""},{"@type":"b","@rid":"#1:10","@version":1,"value":""},{"@type":"b","@rid":"#1:11","@version":1,"value":""},{"@type":"b","@rid":"#1:12","@version":1,"value":""},{"@type":"b","@rid":"#1:13","@version":1,"value":""},{"@type":"b","@rid":"#1:14","@version":1,"value":""},{"@type":"b","@rid":"#1:15","@version":1,"value":""},{"@type":"b","@rid":"#2:0","@version":1,"value":""},{"@type":"d","@rid":"#4:0","@version":2,"@class":"ORole","name":"admin","inheritedRole":null,"mode":1,"rules":[{"@type":"d","@version":0,"resourceGeneric":"BYPASS_RESTRICTED","specificResources":{},"access":15,"@fieldTypes":"access=b"}],"@fieldTypes":"mode=b,rules=e"},{"@type":"d","@rid":"#4:1","@version":2,"@class":"ORole","name":"reader","inheritedRole":null,"mode":0,"rules":[{"@type":"d","@version":0,"resourceGeneric":"FUNCTION","specificResources":{},"access":2,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"RECORD_HOOK","specificResources":{},"access":2,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"SCHEMA","specificResources":{},"access":2,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"DATABASE","specificResources":{},"access":2,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"CLASS","specificResources":{},"access":2,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"CLUSTER","specificResources":{"internal":2,"orole":2,"ouser":2},"access":2,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"COMMAND","specificResources":{},"access":2,"@fieldTypes":"access=b"}],"@fieldTypes":"mode=b,rules=e"},{"@type":"d","@rid":"#4:2","@version":2,"@class":"ORole","name":"writer","inheritedRole":null,"mode":0,"rules":[{"@type":"d","@version":0,"resourceGeneric":"CLASS","specificResources":{},"access":15,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"DATABASE","specificResources":{},"access":2,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"SCHEMA","specificResources":{},"access":7,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"CLUSTER","specificResources":{"internal":2,"orole":2,"ouser":2},"access":15,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"RECORD_HOOK","specificResources":{},"access":15,"@fieldTypes":"access=b"},{"@type":"d","@version":0,"resourceGeneric":"COMMAND","specificResources":{},"access":15,"@fieldTypes":"access=b"}],"@fieldTypes":"mode=b,rules=e"},{"@type":"d","@rid":"#5:0","@version":1,"@class":"OUser","name":"admin","password":"{SHA-256}8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918","status":"ACTIVE","roles":["#4:0"],"@fieldTypes":"roles=n"},{"@type":"d","@rid":"#5:1","@version":1,"@class":"OUser","name":"reader","password":"{SHA-256}3D0941964AA3EBDCB00CCEF58B1BB399F9F898465E9886D5AEC7F31090A0FB30","status":"ACTIVE","roles":["#4:1"],"@fieldTypes":"roles=n"},{"@type":"d","@rid":"#5:2","@version":1,"@class":"OUser","name":"writer","password":"{SHA-256}B93006774CBDD4B299389A03AC3D88C3A76B460D538795BC12718011A909FBA5","status":"ACTIVE","roles":["#4:2"],"@fieldTypes":"roles=n"},{"@type":"d","@rid":"#9:0","@version":1,"@class":"_studio","name":"GetCommentByPhrasesLucene","query":"select from CommentPhrases where title LUCENE 'order*' GROUP BY parent","tags":["NLP"],"type":"Bookmark"},{"@type":"d","@rid":"#9:1","@version":2,"@class":"_studio","name":"GetCommentsByPhraseANDSortByLangScore","query":"select parent.@rid, parent.sentiment_score, parent.language_score, parent.bpid, parent.cid, parent.sentiment_polarity, title from CommentPhrases \u000awhere title LUCENE 'order*' \u000aAND parent.status <> 0 AND parent.bpid = 1390\u000aGROUP BY parent\u000aORDER BY parent.language_score DESC","tags":["NLP"],"type":"Bookmark"},{"@type":"d","@rid":"#9:2","@version":1,"@class":"_studio","type":"GraphConfig"},{"@type":"d","@rid":"#13:0","@version":4,"@class":"CommentAnalysis","sentiment_score":0.43251553,"uid":1941,"bpid":1390,"language_score":36,"language":"English","phrases":["#14:0","#14:1","#14:2"],"sentiment_polarity":2,"review_type":1,"cid":184,"created":1408533214,"rating":80,"api_status":1,"status":25,"@fieldTypes":"sentiment_score=d,language_score=s,phrases=z,sentiment_polarity=s,review_type=s,rating=s,api_status=s,status=s"},{"@type":"d","@rid":"#13:1","@version":2,"@class":"CommentAnalysis","sentiment_score":0.67,"created":null,"bpid":1390,"rating":80,"language":"English","api_status":1,"review_type":2,"uid":1941,"language_score":59,"phrases":["#14:3","#14:4","#14:5"],"sentiment_polarity":2,"cid":482,"status":2,"@fieldTypes":"sentiment_score=d,rating=s,api_status=s,review_type=s,language_score=s,phrases=z,sentiment_polarity=s,status=s"},{"@type":"d","@rid":"#14:0","@version":2,"@class":"CommentPhrases","is_negated":null,"sentiment_score":0.6,"parent":"#13:0","title":"excellent","is_intensified":false,"sentiment_polarity":2,"@fieldTypes":"sentiment_score=d,sentiment_polarity=s"},{"@type":"d","@rid":"#14:1","@version":1,"@class":"CommentPhrases","is_negated":null,"sentiment_score":0.27,"parent":"#13:0","title":"accept","is_intensified":null,"sentiment_polarity":2,"@fieldTypes":"sentiment_score=d,sentiment_polarity=s"},{"@type":"d","@rid":"#14:2","@version":1,"@class":"CommentPhrases","is_negated":null,"sentiment_score":0.45,"parent":"#13:0","title":"future orders","is_intensified":null,"sentiment_polarity":1,"@fieldTypes":"sentiment_score=d,sentiment_polarity=s"},{"@type":"d","@rid":"#14:3","@version":1,"@class":"CommentPhrases","is_negated":null,"sentiment_score":0.67,"parent":"#13:1","title":"fast order","is_intensified":null,"sentiment_polarity":2,"@fieldTypes":"sentiment_score=d,sentiment_polarity=s"},{"@type":"d","@rid":"#14:4","@version":1,"@class":"CommentPhrases","is_negated":null,"sentiment_score":0.76,"parent":"#13:1","title":"orders","is_intensified":null,"sentiment_polarity":2,"@fieldTypes":"sentiment_score=d,sentiment_polarity=s"},{"@type":"d","@rid":"#14:5","@version":1,"@class":"CommentPhrases","is_negated":null,"sentiment_score":0.89,"parent":"#13:1","title":"good","is_intensified":null,"sentiment_polarity":2,"@fieldTypes":"sentiment_score=d,sentiment_polarity=s"}],"indexes":[{"name":"OUser.name","type":"UNIQUE","clustersToIndex":["ouser"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"OUser","field":"name","keyType":"STRING","collate":"ci","nullValuesIgnored":true}}},{"name":"CommentAnalysis.cid","type":"DICTIONARY_HASH_INDEX","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","field":"cid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true}}},{"name":"CommentAnalysis.created_status_bpid_sentiment_score_sentiment_polarity_language_score_rating","type":"NOTUNIQUE","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_score","keyType":"DOUBLE","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_polarity","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"language_score","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"rating","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true}}},{"name":"CommentAnalysis.bpid","type":"NOTUNIQUE_HASH_INDEX","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true}}},{"name":"CommentAnalysis.bpid_status","type":"NOTUNIQUE","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true}}},{"name":"CommentAnalysis.created_status_bpid","type":"NOTUNIQUE","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true}}},{"name":"CommentAnalysis.created","type":"NOTUNIQUE","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true}}},{"name":"dictionary","type":"DICTIONARY","definition":{"defClass":"com.orientechnologies.orient.core.index.OSimpleKeyIndexDefinition","stream":{"@type":"d","@version":0,"keyTypes":["STRING"],"collate":"default","nullValuesIgnored":true}},"metadata":{"@type":"d","@version":0,"durableInNonTxMode":true,"trackMode":"FULL"}},{"name":"CommentAnalysis.created_bpid_status_rating","type":"NOTUNIQUE","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"created","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"rating","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true}}},{"name":"ORole.name","type":"UNIQUE","clustersToIndex":["orole"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"ORole","field":"name","keyType":"STRING","collate":"ci","nullValuesIgnored":true}}},{"name":"CommentAnalysis.bpid_sentiment_score_sentiment_polarity_language_score_status_rating","type":"NOTUNIQUE","clustersToIndex":["commentanalysis"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OCompositeIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentAnalysis","indexDefinitions":[{"@type":"d","@version":0,"className":"CommentAnalysis","field":"bpid","keyType":"INTEGER","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_score","keyType":"DOUBLE","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"sentiment_polarity","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"language_score","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"status","keyType":"SHORT","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"CommentAnalysis","field":"rating","keyType":"SHORT","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true}}},{"name":"CommentPhrases.title_fulltext","type":"FULLTEXT","clustersToIndex":["commentphrases"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"CommentPhrases","field":"title","keyType":"STRING","collate":"default","nullValuesIgnored":true}}}],"manualIndexes":[{"name":"dictionary","content":[]}]}

**Comment by darkredz** [comment]
Also it seems that in RC1 a field with LUCENE fulltext index will become SBTREE fulltext index after using the import command from the database when using the db.validation = false workaround

**Comment by lvca** [comment]
The problem seems to be at server side where validation is enabled. We could support a new:

    ALTER DATABASE validation false

To disable it before the import and then re-enable it.

**Comment by lvca** [comment]
Updating docs...

**Comment by lvca** [comment]
Done: https://github.com/orientechnologies/orientdb-docs/blob/master/Console-Command-Import.md#validation-errors

**Comment by laa** [comment]
Tests are failing could you fix them &

**Comment by lvca** [comment]
I'm fixing the remote case right now that failed.

**Comment by lvca** [comment]
Done.

**Comment by tglman** [comment]
this is not completely fixed due to the fact that the server can close and reopen the database the next request, loosing this setting, reopening

**Comment by tglman** [comment]
fixed, closing

**Comment by tglman** [comment]
reopening because the fix bring some issue in case of Multi thread set.

**Comment by tglman** [comment]
fixed again closing again
