### ISSUE TITLE
UTF8 character breaking query

### ISSUE THREAD

**Issue by devourment77** [orientechnologies/orientdb#3345]
Hello,

When running this query with 2.0-rc1, we get an odd error that says "AND" is an invalid keyword.  Taking out the "ß" character fixes the query.  We have not run into this with other utf8 chars yet.

QUERY
select * from Attraction where name = 'Schloßberg Hotel' and archive = false

ERROR FROM ORIENTDB
-----------------------------------------------------------------^
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #57: Invalid keyword 'AND'
Command: select * from Attraction where name = 'Schloßberg Hotel' and archive = false
-----------------------------------------------------------------^
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:93)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:266)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:96)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1150)
    at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
    at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
    at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

**Comment by lvca** [comment]
This issue should be already fixed in 2.0-SNAPSHOT. Please could you try it?

**Comment by devourment77** [comment]
I will try it, also forgot to mention that we were using OrientGraphNoTx (java).

**Comment by devourment77** [comment]
We tried with the "develop" branch and still see the issue.  I didn't not see a 2-0-SNAPSHOT branch to try out (apologies if I overlooked it).

Thanks
Brandon

**Comment by tglman** [comment]
we had a very similar issue due to the encoding, that is solved, but i think the issue you describe exist in the current parser code, that parser will be deprecate soon, we are already working on a new one without this issues.

The workaround is use the query parameters in this way the parser don't have problem to read the query.

**Comment by luigidellaquila** [comment]
fixed in develop branch
