### ISSUE TITLE
Orient 2.0 final - wal file size growing more than the storage.wal.maxSize

### ISSUE THREAD

**Issue by ginojohn** [orientechnologies/orientdb#3454]
We have a application with 2.0 in embedded mode. The server started with    -Dstorage.wal.maxSize=250. but the wal size keep growing. The system have around 30 wal files with 140MB

**Comment by laa** [comment]
HI Gino,
They will be deleted at once you stop massive load of data.
It is not a bug,  you simple have a lot of data not flushed from disk
cache. Storage is tuning himself to keep all wal is needed to restore data
in the case of crash.


On Sat, Jan 24, 2015 at 6:38 PM, ginojohn <notifications@github.com> wrote:

> We have a application with 2.0 in embedded mode. The server started with
> -Dstorage.wal.maxSize=250. but the wal size keep growing. The system have
> around 30 wal files with 140MB
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3454>.
>



-- 
Best regards,
Andrey Lomakin.

**Comment by laa** [comment]
Also in 2.0.1 if wal will be really big and consumes all disk space, non flushed data will be flushed automatically and wal will be shrinked.
In 2.1 size of the wal needed to keep data will be decreased at 2 times.

**Comment by ginojohn** [comment]
This is a server with lot of active transactions. The server is running out of disk space and application is not working.

**Comment by ginojohn** [comment]
The server also have other applications running if the size grows without control all other applications also gets impacted. Also once the disk is full it keeps creating 0 size wal files

**Comment by laa** [comment]
Gino it is already fixed in 2.0.1 version, could you try it ?

**Comment by laa** [comment]
Also could you set value of storage.wal.fuzzyCheckpointShutdownWait property to the 60 ? It will faster cut wal during tx processing.

**Comment by ginojohn** [comment]
I tried with 2.0.1 SNAPSHOT. I still see the issue. We really need a way to control size of the wal files. The total database size don't grow much but there are lot of transactions.

In 5 minutes it created 135 wal files and disk is full at 66th wal file and no files are deleted.

**Comment by laa** [comment]
Gino,when you tried did you mean that you tried today, or it was at Friday ?

**Comment by ginojohn** [comment]
I tried it today.

**Comment by morphace** [comment]
I run into a similar problem. Is the problem fixed in 2.0.1 or not?
What is the exact meaning of storage.wal.fuzzyCheckpointShutdownWait?
Is this the frequency of the processing of the WAL files?
Does it make sense to have a short frequency, when the database update during transactions is little?

**Comment by lvca** [comment]
Closed by @laa
