### ISSUE TITLE
OrientDB 2.0.1 fails to start on Linux using OpenJDK 6 (IcedTea)

### ISSUE THREAD

**Issue by DanielRuthardt** [orientechnologies/orientdb#3501]
This issue applies to the vanilla package, downloaded, extracted and started without touching anything.
There seems to be some kind of class loading issue.
OrientDB starts normally when switching to e.g. Oracle JDK 7.

```
2015-01-30 12:00:43:102 WARNING Cannot find default script language for javascript [OScriptManager]
2015-01-30 12:00:43:141 WARNING No enough physical memory available for DISKCACHE: 1,989MB (heap=455MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
2015-01-30 12:00:43:145 INFO  Loading configuration from: /usr/local/orientdb/orientdb-community-2.0.1/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-01-30 12:00:43:377 INFO  OrientDB Server v2.0.1 (build UNKNOWN@r; 2015-01-28 18:33:00+0000) is starting up... [OServer]
2015-01-30 12:00:43:398 INFO  Databases directory: /usr/local/orientdb/orientdb-community-2.0.1/databases [OServer]
2015-01-30 12:00:43:429 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
2015-01-30 12:00:43:430 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2015-01-30 12:00:43:444 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal
    at com.orientechnologies.orient.core.record.impl.ODocument.setup(ODocument.java:2201)
    at com.orientechnologies.orient.core.record.impl.ODocument.<init>(ODocument.java:107)
    at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:323)
    at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
    at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
    at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
    at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:831)
    at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
    at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

**Comment by zanerock** [comment]
I'm having the same problem with OrientDB 2.0. Have tried icedtea7 and openjdk 7

**Comment by DanielRuthardt** [comment]
So it seems to be an issue with IcedTea / OpenJDK.
I won't have time until the end of next week, but I am curious to see what happens when trying any of the other 1.6 JDKs like Diablo JDK, HP's or IBM's. Basically whatever JDK my Linux box allows me to install without too much work :-)

**Comment by tglman** [comment]
Hi all, 
yes is happened also to me this error in some corner case, i already know what cause this, i've to investigate a bit more to get a working fix but is all aobut move the ODatabaseRecordThreadLocal static inizialization somewhere else.

**Comment by zanerock** [comment]
2.0-RC1 was working, and I'm not 100%, but I'm fairly positive that was with OpenJDK; the issue seems to have appeared between 2.0-RC1 and 2.0.

**Comment by evgeny-konovalov** [comment]
Same problem with orientdb 2.0.2 and 2.0.5
```
openjdk version "1.7.0-internal"
OpenJDK Runtime Environment (build 1.7.0-internal-b56)
OpenJDK Server VM (build 24.0-b56, mixed mode)
```

**Comment by bra-fsn** [comment]
Same:
```
2015-03-24 10:24:01:671 WARNING Cannot find default script language for javascript [OScriptManager]
2015-03-24 10:24:01:726 INFO  OrientDB auto-config DISKCACHE=5,622MB (heap=494MB os=8,165MB disk=12,832MB) [orientechnologies]
2015-03-24 10:24:01:730 INFO  Loading configuration from: /usr/home/orientdb/orientdb-community-2.0.5/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-03-24 10:24:02:017 INFO  OrientDB Server v2.0.5 (build UNKNOWN@r; 2015-03-12 22:59:10+0000) is starting up... [OServer]
2015-03-24 10:24:02:036 INFO  Databases directory: /usr/home/orientdb/orientdb-community-2.0.5/databases [OServer]
2015-03-24 10:24:02:063 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
2015-03-24 10:24:02:065 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2015-03-24 10:24:02:078 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal
        at com.orientechnologies.orient.core.record.impl.ODocument.setup(ODocument.java:2199)
        at com.orientechnologies.orient.core.record.impl.ODocument.<init>(ODocument.java:107)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:323)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:831)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
^C
```

here on FreeBSD with:
```
openjdk version "1.6.0_32"
OpenJDK Runtime Environment (build 1.6.0_32-b34)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```
and
```
openjdk version "1.7.0_76"
OpenJDK Runtime Environment (build 1.7.0_76-b13)
OpenJDK 64-Bit Server VM (build 24.76-b04, mixed mode)
```

while it starts with:
```
openjdk version "1.8.0_40"
OpenJDK Runtime Environment (build 1.8.0_40-b25)
OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)
```

**Comment by lvca** [comment]
@tglman do you know why?

**Comment by DanielRuthardt** [comment]
Unfortunately I wasn't able to test any other JDKs, as all the other (mostly 1.6.x) JDKs fail to install on the Linux box I wanted to test it on.

**Comment by kitaeff** [comment]
Version 2.0.5 worked on Oracle's JDK without any problem, but startup on OpenJDK failed with the same exception. We analyzed database sources and found cyclic dependency in startup process:

1. `Orient` class has static field `OScriptManager scriptManager` which is set to new instance in field initializer.
2. `OScriptManager` constructor checks supported script engines. If engine for JavaScript is not found it calls `OLogManager` to warn about it.
3. `OLogManager` calls `ODatabaseRecordThreadLocal` to get name of current working db (if any)
4. `ODatabaseRecordThreadLocal` static initializer accesses `Orient` static field `instance` which value is not yet exposed to other classes because of initialization in progress. Static initializer fails with `NullPointerException`.
5. JVM is unable to load class with failing intializer and throws `NoClassDefFoundError` hiding source NPE.

Oracle's JDK has required script engine and database starts up without problem, OpenJDK does not (except builds in some distributions). For our project we worked around by making (temporarily) own custom OrientDB build with warning commented out.

**Comment by tglman** [comment]
hi, i add a check for avoid that nullpointer, if this check fail it can happen some small amount of memory retention, but should be fine in general, and anyway is better than not be able to start the server.

I'm closing it, is fixed in 2.1, reopen it if you need backport to 2.0.x

**Comment by lvca** [comment]
Hey guys, can you confirm this has been fixed?

**Comment by lvca** [comment]
@tglman could you backport also to 2.0.6 please?

**Comment by DanielRuthardt** [comment]
This issue still exists for OrientDB 2.1.0 and the following JDKs:
Oracle JDK 1.8.0_51
Icedtea JDK 1.7.0_79

So using a newer JDK doesn't seem to help this time.

**Comment by DanielRuthardt** [comment]
What might be a difference (unable to check, the previous setup doesn't exist anymore) this time, is that the server is up and running and can be accessed using the console, just the plugins won't start, so the web interface can't be used.

**Comment by smolinari** [comment]
In a try to workaround this issue, 

https://github.com/orientechnologies/orientdb/issues/4840

I installed ODB using the downloadable package from the OrientDB website. However, I am also running into this exact problem too. I can't run the application as a service and when I start in a console, it works and I can call up the ODB console, but I can't access the database anyway else. 

I am running with 

OpenJDK Runtime Environment (IcedTea6 1.13.8) (6b36-1.13.8-1~deb7u1)

I am going to try and upgrade OpenJDK to see what happens.
 
Scott

**Comment by pokluda** [comment]
`fork = true`
in ant might help ([https://ant.apache.org/manual/Tasks/java.html](https://ant.apache.org/manual/Tasks/java.html)).

**Comment by smolinari** [comment]
@pokluda ODB has moved to Maven. 

Scott

**Comment by robbiesmith** [comment]
I have seen this (or something closely related) on Windows, with OrientDB version 2.1.14 and JVM 1.8.0_77 (Oracle).

For details see http://stackoverflow.com/questions/36345804/noclassdeffounderror-when-starting-orientdb

**Comment by turbogeek** [comment]
Having similar issue. I am attempting to run via a Groovy script. When I run a client script in its won instance via a run in both Eclipse and Netbeans, no issues. But when I run from a Java application running Groovy (i.e. an application supporting embedded groovy scripts), I get the error.  I am using orientdb-community-2.1.11.

**Comment by jCalamari** [comment]
I was able to trace down this issue. In my case, `OScriptManager:85` was looking up javascript enginee (which seems to be default) and it could not find it. In `OScriptManager:87` logs a warning which at some point calls 'ODatabaseRecordThreadLocal:31', which return null and now things start to get messy.. I simply disabled warning level: `OLogManager.instance().setWarnEnabled(false)` and application started up.

**Comment by lvca** [comment]
@jCalamari why OrientDB instance is null in your case? How your app is started?

**Comment by jCalamari** [comment]
@lvca I was very surprised it was null. I am running gremlin-orient 3.1.1-incubating.1 (orient 2.12.2) as service in docker container.

**Comment by jCalamari** [comment]
Pretty much the same is described here:
https://github.com/orientechnologies/orientdb/issues/5855

**Comment by rareddy** [comment]
This is still a bug on OpenJDK on Linux
`
$java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)
`
I downloaded the OrientDB Community edition 2.2.25. Below is stack trace

`
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.activateOnCurrentThread(ODatabaseDocumentTx.java:3130)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:162)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at com.orientechnologies.orient.jdbc.OrientJdbcConnection.<init>(OrientJdbcConnection.java:62)
	at com.orientechnologies.orient.jdbc.OrientJdbcDriver.connect(OrientJdbcDriver.java:63)
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:319)
	... 25 more
`
