### ISSUE TITLE
Calling graph.getEdges on some vertices throws exception after a restore operation

### ISSUE THREAD

**Issue by shajigopal** [orientechnologies/orientdb#4171]
OrientDB version: 2.0.5
We used the orient java api to backup and restore the graph.
When we traverse the restired graph we get the following exception for certain vertices:

java.lang.NullPointerException
                at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:117)
                at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:272)
                at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1221)
                at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:736)
                at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.getRealBagSize(OSBTreeBonsaiLocal.java:1323)
                at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:940)
                at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:679)
                at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:182)
                at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:1062)
                at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:1004)

**Comment by lvca** [comment]
@tglman Is this already fixed in 2.0.9?

**Comment by tglman** [comment]
i don't see any commit related to this problem, and i didn't work on it, as far as i know is not fixed in 2.0.9, will be quite useful have the database with this problem or even the database before the restore procedure.

**Comment by shajigopal** [comment]
Please let us me know the location where I can upload the db with this problem

**Comment by tglman** [comment]
hi, You can use any dropbox account you prefer, if you want to keep private the database and not post here you can send a mail to support with the refer to this issue.

**Comment by tglman** [comment]
@shajigopal Thank you we received the database, we will let you know

**Comment by lvca** [comment]
@tglman Any news on this? I'd like to put this fix in the upcoming 2.1-rc3

**Comment by tglman** [comment]
i tested the import of the database in 2.0.x, and 2.1-SNAPSHOT, and both work correctly.

so i'm closing this.

by the way you should re-import the database to get it fixed.

**Comment by shajigopal** [comment]
Can I use OrientDB 2.0.10 community edition to test this?
