### ISSUE TITLE
SQL Parser: backticks do not properly escape hyphen '-' character.

### ISSUE THREAD

**Issue by patrickjmccarty** [orientechnologies/orientdb#4353]
Queries fail when using a property name containing a hyphen/dash '-' character, despite the use of backticks. Also, certain API calls that run queries internally, such as createProperty(), fail when propertyName contains a hyphen. Possibly related to #4276.

I'm upgrading my project from OrientDB 1.4.1 to 2.1-rc3, and hyphens were allowed back then. However in 2.1-rc3 they cause an exception (and a rather unhelpful one at that). The validation in OClassImpl.addPropertyInternal() considers the name with dashes to be valid, so I take this to mean that dashes should still be allowed. The bug seems to be in how the SQL parser handles escaping using backticks.

The underlying problem is easy to reproduce by running:
```select count(*) from OUser where `My-Field` = "abc"```

If square brackets are used instead of backticks, it works correctly, so maybe compare the square bracket implementation with the backtick implementation.

**Comment by lvca** [comment]
Have you tried 2.1-SNAPSHOT? I think we fixed right after the release of 2.1-rc3

**Comment by patrickjmccarty** [comment]
Yes the problem still exists in orientdb-community-2.1-20150610.173559-189-distribution.

**Comment by luigidellaquila** [comment]
Hi @patrickjmccarty 

due to limitations of current executor, in 2.1 you can only use back tick quotation for reserved words, not for non-identifier characters like '-'.
This will be supported in next releases

**Comment by patrickjmccarty** [comment]
@luigidellaquila My real problem is not that backtick parsing is broken but that basic java API functions like createProperty() are broken *because* they use backticks. I think you could just change OClassImpl.getEscapedName() to use square brackets instead of backticks? Seems like that would be a really easy fix that could go in 2.1 to fix the regression. And backtick parsing could then be fully fixed in 2.2.

Have a look at getEscapedName() in:
https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/metadata/schema/OClassImpl.java

**Comment by luigidellaquila** [comment]
fixed in branch 2.1.x supporting backtick syntax.
It will be released with 2.1.1

**Comment by pradeepg-telsiz** [comment]
I am using 2.1.2 and still seeing this issue in distributed mode but not in standalone mode.
