### ISSUE TITLE
OrientDB shouldn't check static paths

### ISSUE THREAD

**Issue by Robin479** [orientechnologies/orientdb#4379]
Fix OServerCommandGetStaticContent to check paths before serving files.

**Comment by StarpTech** [comment]
This is really a huge security lack. Thanks for reporting. Should be fixed as hotfix because now everyone can try historischen luck with this.

**Comment by Robin479** [comment]
I emailed l.garulli[at]orientdb.com about this about a week ago to handle this discretely, but it's not fixed in the 2.1-rc4 so I thought I but it here.

**Comment by lvca** [comment]
@Robin479 Thanks for reporting it. I've changed the issue data to reduce impact of such issue. We're going to fix it asap on 2.0.11 and next 2.1 GA.

**Comment by lvca** [comment]
@Robin479 Following your steps I cannot reproduce it. I wrote you an email in private.

**Comment by lvca** [comment]
Reproduced by using TELNET. Fixing it now.

**Comment by lvca** [comment]
Fixed on 2.0.11 (2.0.x branch) and 2.1 GA (develop branch).

**Comment by lvca** [comment]
As side note, we never recommend to open OrientDB to the Internet or Public networks.

**Comment by Robin479** [comment]
It doesn't work "out of the box", because the default settings for `orientdb.www.path` is empty, which then falls back to `${user.dir}/src/site`, which effectively resolves to `$ORIENT_HOME/bin/src/site` (if you run from `server.sh`). This folder usually doesn't exist on a user system, which effectively disables serving of static content in general (except for the "virtual folder" feature). Thus, a system is only compromised, if the user configures `orientdb.www.path` to point to a valid existing folder.
