### ISSUE TITLE
Time out during "Rebuild all Indexes"

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb#4742]
Issue related to #4841 and know for Orient team. @lvca is working on fix for that issue. Open large database and run "Rebuild all Indexes"  notice:

OIndexRebuildOutputListener] --> 6.11% progress, 5,479 indexed so far (547 items/s
ec)
jvm 1    | WARN  [OHazelcastDistributedDatabase] [node_VA005SH_AUS1_8080] timeout (60005ms) on waiti
ng for synchronous responses from nodes=[node_VA005SH_AUS1_8080] responsesSoFar=[] request=id=1364 f
rom=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=admin
jvm 1    | WARN  [ODistributedResponseManager] [node_VA005SH_AUS1_8080] no response received from lo
cal node about request id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userNam
e=admin
jvm 1    | WARN  [ODistributedResponseManager] [node_VA005SH_AUS1_8080] detected 1 node(s) in timeou
t or in conflict and quorum (1) has not been reached, rolling back changes for request (id=1364 from
=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=admin)
jvm 1    | WARN  [ODistributedResponseManager] [node_VA005SH_AUS1_8080] Quorum 1 not reached for req
uest (id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=admin). Elapsed
=60008ms No server in conflict. Received: {node_VA005SH_AUS1_8080=waiting-for-response}
jvm 1    | ERROR [ONetworkProtocolHttpDb] Internal server error:
jvm 1    | com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing
 distributed request (id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName
=admin) against database 'spectrum.[]' to nodes [node_VA005SH_AUS1_8080]
jvm 1    | --> com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 1 not r
eached for request (id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=a
dmin). Elapsed=60008ms No server in conflict. Received: {node_VA005SH_AUS1_8080=waiting-for-response

**Comment by lvca** [comment]
This is already in 2.0.14-SNAPSHOT. This issue is the same as for https://github.com/orientechnologies/orientdb/issues/4666, right?

**Comment by shlapkov** [comment]
No it is not the same and it is not fixed.

**Comment by shlapkov** [comment]
Based on last update from Jill: http://www.prjhub.com/#/issues/4841: Initial issue resolved in 2.0.14 snapshot. However, OrientDB 2.0 doesn't support per-command timeouts introduced in 2.1. So, we will backport it before closing the issue.

**Comment by lvca** [comment]
The back-porting has been executed 2 days ago.

**Comment by jillray7** [comment]
@shlapkov Why do you think this isn't resolved? Please provide details.

**Comment by jillray7** [comment]
@lvca I think the problem is that they can't ignore the exceptions. It produces errors on client and Orient studio UI. @shlapkov Can you confirm?

**Comment by shlapkov** [comment]
Yes we can't ignore this exception see: https://github.com/shlapkov/OrientIssues/blob/master/2.0.14-SNAPSHOT/TimeOutError.PNG

It maybe looks OK for orient but not for us. Please re-open ticket.

**Comment by lvca** [comment]
Reproduced.

**Comment by lvca** [comment]
Fixed.

**Comment by lvca** [comment]
2015-08-07 10:29:33:900 INFO  - Rebuilding index pokec.Profile.AGE (estimated 1632874 items)... [OIndexRebuildOutputListener]
2015-08-07 10:29:43:902 INFO  --> 6,26% progress, 102.262 indexed so far (10.226 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:29:53:903 INFO  --> 18,83% progress, 307.519 indexed so far (20.525 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:30:03:903 INFO  --> 44,19% progress, 721.592 indexed so far (41.407 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:30:13:907 INFO  --> 94,17% progress, 1.537.645 indexed so far (81.605 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:30:23:907 INFO  --> 194,03% progress, 3.168.215 indexed so far (163.057 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:30:33:908 INFO  --> 394,37% progress, 6.439.524 indexed so far (327.130 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:30:43:909 INFO  --> 794,76% progress, 12.977.456 indexed so far (653.793 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:30:53:910 INFO  --> 1594,77% progress, 26.040.664 indexed so far (1.306.320 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:31:03:911 INFO  --> 3194,85% progress, 52.167.851 indexed so far (2.612.718 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:31:13:912 INFO  --> 6395,08% progress, 104.423.681 indexed so far (5.225.583 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:31:23:913 INFO  --> 12795,62% progress, 208.936.383 indexed so far (10.451.270 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:31:33:914 INFO  --> 25596,40% progress, 417.957.038 indexed so far (20.902.065 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:31:43:915 INFO  --> 51197,39% progress, 835.988.871 indexed so far (41.803.183 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:31:53:916 INFO  --> 102399,21% progress, 1.672.050.148 indexed so far (83.606.127 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:32:03:336 INFO  --> OK, indexed 1.632.640 items in 149.435 ms [OIndexRebuildOutputListener]
2015-08-07 10:32:45:101 INFO  - Rebuilding index pokec.Profile.region (estimated 1632874 items)... [OIndexRebuildOutputListener]
2015-08-07 10:32:55:101 INFO  --> 6,30% progress, 102.854 indexed so far (10.285 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:33:05:102 INFO  --> 19,03% progress, 310.769 indexed so far (20.791 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:33:15:103 INFO  --> 45,55% progress, 743.739 indexed so far (43.297 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:33:25:104 INFO  --> 96,78% progress, 1.580.352 indexed so far (83.661 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:33:35:105 INFO  --> 198,41% progress, 3.239.705 indexed so far (165.935 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:33:45:106 INFO  --> 794,02% progress, 12.965.313 indexed so far (972.560 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:33:55:107 INFO  --> 1595,06% progress, 26.045.394 indexed so far (1.308.008 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:34:05:108 INFO  --> 3196,53% progress, 52.195.266 indexed so far (2.614.987 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:34:15:109 INFO  --> 6398,18% progress, 104.474.177 indexed so far (5.227.891 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:34:25:110 INFO  --> 12799,74% progress, 209.003.583 indexed so far (10.452.940 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:34:35:111 INFO  --> 51194,31% progress, 835.938.566 indexed so far (62.693.498 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:34:45:112 INFO  --> 102394,69% progress, 1.671.976.264 indexed so far (83.603.769 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:34:55:113 INFO  --> 204795,50% progress, 3.344.052.419 indexed so far (167.207.615 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:35:01:454 INFO  --> OK, indexed 1.632.640 items in 136.354 ms [OIndexRebuildOutputListener]
2015-08-07 10:35:41:741 INFO  - Rebuilding index pokec.OUser.name (estimated 3 items)... [OIndexRebuildOutputListener]
2015-08-07 10:35:41:742 INFO  --> OK, indexed 3 items in 1 ms [OIndexRebuildOutputListener]
2015-08-07 10:35:41:905 INFO  - Rebuilding index pokec.Profile._key (estimated 1632874 items)... [OIndexRebuildOutputListener]
2015-08-07 10:35:51:906 INFO  --> 11,33% progress, 185.006 indexed so far (18.500 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:36:01:907 INFO  --> 45,14% progress, 737.038 indexed so far (55.203 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:36:11:908 INFO  --> 97,29% progress, 1.588.650 indexed so far (85.161 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:36:21:909 INFO  --> 395,51% progress, 6.458.222 indexed so far (486.957 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:36:31:910 INFO  --> 799,28% progress, 13.051.292 indexed so far (659.307 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:36:41:911 INFO  --> 3195,14% progress, 52.172.661 indexed so far (3.912.136 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:36:51:912 INFO  --> 6399,16% progress, 104.490.157 indexed so far (5.231.749 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:37:01:913 INFO  --> 25597,25% progress, 417.970.891 indexed so far (31.348.073 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:37:11:914 INFO  --> 102395,79% progress, 1.671.994.247 indexed so far (125.402.335 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:37:21:917 INFO  --> 204799,33% progress, 3.344.114.986 indexed so far (167.212.073 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:37:23:985 INFO  --> OK, indexed 1.632.640 items in 102.079 ms [OIndexRebuildOutputListener]
2015-08-07 10:37:23:993 INFO  - Rebuilding index pokec.Profile.region (estimated 1632874 items)... [OIndexRebuildOutputListener]
2015-08-07 10:37:33:994 INFO  --> 6,49% progress, 106.050 indexed so far (10.605 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:37:43:995 INFO  --> 20,38% progress, 332.790 indexed so far (22.674 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:37:53:996 INFO  --> 47,67% progress, 778.346 indexed so far (44.555 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:38:03:997 INFO  --> 99,86% progress, 1.630.592 indexed so far (85.224 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:38:13:998 INFO  --> 393,93% progress, 6.432.338 indexed so far (480.174 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:38:23:999 INFO  --> 794,13% progress, 12.967.220 indexed so far (653.488 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:38:34:000 INFO  --> 1595,77% progress, 26.056.991 indexed so far (1.308.977 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:38:44:001 INFO  --> 3197,68% progress, 52.214.148 indexed so far (2.615.715 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:38:54:002 INFO  --> 6399,30% progress, 104.492.436 indexed so far (5.227.828 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:39:04:003 INFO  --> 25594,92% progress, 417.932.727 indexed so far (31.344.029 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:39:14:004 INFO  --> 51196,89% progress, 835.980.621 indexed so far (41.804.789 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:39:24:005 INFO  --> 102398,97% progress, 1.672.046.138 indexed so far (83.606.551 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:39:33:447 INFO  --> OK, indexed 1.632.640 items in 129.454 ms [OIndexRebuildOutputListener]
2015-08-07 10:39:33:453 INFO  - Rebuilding index pokec.ORole.name (estimated 3 items)... [OIndexRebuildOutputListener]
2015-08-07 10:39:33:455 INFO  --> OK, indexed 3 items in 2 ms [OIndexRebuildOutputListener]
2015-08-07 10:39:33:461 INFO  - Rebuilding index pokec.Profile.AGE (estimated 1632874 items)... [OIndexRebuildOutputListener]
2015-08-07 10:39:43:462 INFO  --> 8,84% progress, 144.352 indexed so far (14.435 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:39:53:463 INFO  --> 22,70% progress, 370.583 indexed so far (22.623 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:40:03:464 INFO  --> 48,53% progress, 792.403 indexed so far (42.182 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:40:13:465 INFO  --> 99,26% progress, 1.620.807 indexed so far (82.840 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:40:23:466 INFO  --> 395,28% progress, 6.454.404 indexed so far (483.359 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:40:33:467 INFO  --> 797,26% progress, 13.018.273 indexed so far (656.386 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:40:43:468 INFO  --> 1598,27% progress, 26.097.759 indexed so far (1.307.948 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:40:53:469 INFO  --> 3199,26% progress, 52.239.938 indexed so far (2.614.217 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:41:03:470 INFO  --> 12794,94% progress, 208.925.229 indexed so far (15.668.529 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:41:13:471 INFO  --> 25596,98% progress, 417.966.483 indexed so far (20.904.125 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:41:23:472 INFO  --> 51199,00% progress, 836.015.193 indexed so far (41.804.871 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:41:33:473 INFO  --> 204795,66% progress, 3.344.054.968 indexed so far (250.803.977 items/sec) [OIndexRebuildOutputListener]
2015-08-07 10:41:39:172 INFO  --> OK, indexed 1.632.640 items in 125.711 ms [OIndexRebuildOutputListener]

**Comment by lvca** [comment]
So 10:41:39:172-10:29:33:900 = about 12 minutes and no timeout. I tried with one node only running distributed. Did you run it on more than 1 node?

**Comment by shlapkov** [comment]
@lvca one node, looks OK today

**Comment by lvca** [comment]
By the way the distributed deploy now is much faster because of https://github.com/orientechnologies/orientdb/issues/4747
