### ISSUE TITLE
Ignored Parameters for Subqueries

### ISSUE THREAD

**Issue by 67726e** [orientechnologies/orientdb#4846]
I'm using the Java Document API execute queries, but unfortunately it seems as though whatever handles both named & positional parameters does not handle deeper than a single subquery. Currently I am getting around this with a `String.format` for the deeply-nested properties since the fields are `UUID`s but this would not be suitable for user-input which I will have to deal with in the near future.

```java
		Map<String, Object> parameters = Maps.newHashMap();
		parameters.put("companyId", companyId);
		parameters.put("userId", userId);
		parameters.put("comparedEmployee", isEmployee(type));
		parameters.put("profiledEmployee", !isEmployee(type));

		String query = String.format("SELECT FROM Profile WHERE companyId=:companyId AND comparedEmployee=:comparedEmployee AND " +
						"profiledEmployee=:profiledEmployee AND comparedId IN (SELECT externalId FROM (SELECT EXPAND(in) FROM " +
						"(SELECT EXPAND(outE('Favorite')) FROM User WHERE externalId='%s') WHERE companyId='%s'))",
						userId, companyId);

		String query2 = "SELECT FROM Profile WHERE companyId=:companyId AND comparedEmployee=:comparedEmployee AND " +
				"profiledEmployee=:profiledEmployee AND comparedId IN (SELECT externalId FROM (SELECT EXPAND(in) FROM " +
				"(SELECT EXPAND(outE('Favorite')) FROM User WHERE externalId=:userId) WHERE companyId=:companyId))";

		String query3 = "SELECT FROM Profile WHERE companyId = ? AND comparedEmployee = ? AND " +
				"profiledEmployee = ? AND comparedId IN (SELECT externalId FROM (SELECT EXPAND(in) FROM " +
				"(SELECT EXPAND(outE('Favorite')) FROM User WHERE externalId= ? ) WHERE companyId= ? ))";

		List<ODocument> documents = factory.db()
				.command(new OSQLSynchQuery<ODocument>(query))
				.execute(parameters);

		List<ODocument> documents2 = factory.db()
				.command(new OSQLSynchQuery<>(query2))
				.execute(parameters);

		List<ODocument> documents3 = factory.db()
				.command(new OSQLSynchQuery<>(query3))
				.execute(companyId, isEmployee(type), !isEmployee(type));

		Logger.getAnonymousLogger().info("===== Documents: " + documents.size());
		Logger.getAnonymousLogger().info("===== Documents 2:" + documents2.size());
		Logger.getAnonymousLogger().info("===== Documents 3:" + documents3.size());
```
Running these queries yields these results in the logs:

```
INFO: ===== Documents: 54
Aug 24, 2015 7:52:39 PM com.echovate.platform.service.GraphServiceImpl findFavoritedProfilesByCompanyAndType
INFO: ===== Documents 2:0
Aug 24, 2015 7:52:39 PM com.echovate.platform.service.GraphServiceImpl findFavoritedProfilesByCompanyAndType
INFO: ===== Documents 3:0
```

You will also notice for execution of `query3`, I have only supplied 3 parameters. To supply more to handle the last two positional parameters in the query results in an exception.

```
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT FROM Profile WHERE companyId = ? AND comparedEmployee = ? AND profiledEmployee = ? AND comparedId IN (SELECT externalId FROM (SELECT EXPAND(in) FROM (SELECT EXPAND(outE('Favorite')) FROM User WHERE externalId= ? ) WHERE companyId= ? ))
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.bindParameters(OSQLPredicate.java:380)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:190)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:438)
	at com.orientechnologint.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:420)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:391)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	... 8 more
```

**Comment by nagarajasr** [comment]
which version of OrientDB are you using? we had somewhat similar issue in 2.0.13 and it seems to be resolved in 2.1.0 GA in our case.

**Comment by 67726e** [comment]
I can confirm I am using `2.1.0` for all of my OrientDB dependencies, despite the warning it issues because of the version difference between my database and the client.

<img width="388" alt="screen shot 2015-08-25 at 10 18 52 am" src="https://cloud.githubusercontent.com/assets/543788/9469062/ff4057a6-4b12-11e5-91e4-1d7f6e565e37.png">

**Comment by tglman** [comment]
this is already fixed in 2.1

**Comment by 67726e** [comment]
@tglman Given that I am using `2.1.0` in my project and am still experiencing this issue, can you explain how this issue is fixed?

**Comment by 67726e** [comment]
@tglman @nagarajasr The problem is still there. If either of y'all would be willing to point me in the direction of the test cases/errant code I'd be happy to work on a pull request.

**Comment by tglman** [comment]
Hi @67726e,

I think the issue exist only if you use strictMode= false on the sql, and that cannot be really fixed, we are working to rewrite the engine to  completely fix that in 3.0, now with strictMode should work because we do a preparsing phase that rebuild a statement that the old parser can handle.

i think @luigidellaquila  can give more update on this.

**Comment by luigidellaquila** [comment]
Hi @67726e 

Please take a look at this

http://orientdb.com/docs/last/Release-2.1.0.html#strict-sql-parser

Could you please check if strictSql is enabled in your db? Probably the problem is there

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @67726e 

This issue was fixed long time ago. I'm closing it, please reopen if you still see any similar problems

Thanks

Luigi
