### ISSUE TITLE
serialization error after a sql batch of insert

### ISSUE THREAD

**Issue by yujinlim** [orientechnologies/orientdb#4865]
```
2015-08-26 16:59:39:532 WARNI {db=test} Error deserializing record with id #11:3 send this data for debugging: AA5Qcm9maWxlKQAAACM1AAAALisAAAAzDQAAADkzAAAARAAUamFja0BzLmNvbQQoCigM/oiiiu1TFHVudmVyaWZpZWQGIAIgAAMB  [ORecordSerializerBinary]{db=test} Fetching error on record #11:3
java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:133)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:53)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readLinkCollection(ORecordSerializerBinaryV0.java:451)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:348)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:193)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:74)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1755)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2332)
	at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:729)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:130)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:70)
	at com.orientechnologies.orient.server.network.protocol.binary.OAbstractCommandResultListener.fetchRecord(OAbstractCommandResultListener.java:54)
	at com.orientechnologies.orient.server.network.protocol.binary.OSyncCommandResultListener.result(OSyncCommandResultListener.java:45)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1380)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1330)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:393)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:222)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
```

**Comment by lvca** [comment]
Already fixed in 2.1.: https://github.com/orientechnologies/orientdb/commit/11a78a4#diff-51f74acf1c2cafb328f57962fffd9cd4R128

**Comment by yujinlim** [comment]
:+1:

**Comment by quantonganh** [comment]
```
OrientDB console v.2.1.0 (build UNKNOWN@r; 2015-08-05 13:38:23+0000) www.orientdb.com
```

and it still happened:

```
Jan 15 02:53:28 x orientdb-upstart: 2016-01-14 18:33:55:235 WARNI {db=x_api} Error deserializing record with id #11:43 send this data for
 debugging: AAhVc2VyKQAAADGlAQAAAEkNAAAAbCsAAAB3LQAAAH0vAAAAhzEAAAFnqQEAAAFuAC5kaXJrQGR1dGNoaGFyZHN0eWxlLmNvbQEAAAACABUAAAAAAAAAVgAVAAAAAAAAAJsAAAAAAAAAAAAAFH
VudmVyaWZpZWTg/b3YjlQSRGlyayBNZWlqvANodHRwczovL2ZiY2RuLXByb2ZpbGUtYS5ha2FtYWloZC5uZXQvaHByb2ZpbGUtYWsteGFmMS92L3QxLjAtMS9wNzIweDcyMC8xMjAzMjI0Ml85MDk2NzM0MDU3
OTM4MjNfNjg5NjY4Mjg5NTk1MjYxOTI2OV9uLmpwZz9vaD1kYjE0YjU2MzM4MTExM2RiODhmNzk1OTZmOTI3MDMwOSZvZT01NkMzNjREMyZfX2dkYV9fPTE0NTU2NjY1NDNfNmQ4YjA3MTc4MWZkN2E2NzUxZW
FiNDVlN2E2YWQzNzMGIAQgQgMBAAKYfOIAAABzAAAAAAAAAAAAAAgA/////wAAAAA=  [ORecordSerializerBinary]
```

By running `display raw record #11:43`, I saw an exception at the end:

```
  Exception on reading: java.lang.NullPointerException
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:131)
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:52)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readLinkCollection(ORecordSerializerBinaryV0.jav
a:451)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:3
48)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryDebug.deserializeDebug(ORecordSerializerBinaryDebug
.java:72)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.displayRawRecord(OConsoleDatabaseApp.java:1074)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)
```

**Comment by lvca** [comment]
@quantonganh Look at the milestone: it has been fixed in 2.1.1, while you're still using 2.1.0.
