### ISSUE TITLE
NullPointerException on first field access with Object API in 2.1.0/2

### ISSUE THREAD

**Issue by xonfour** [orientechnologies/orientdb#4953]
I'm using the Object API and just updated from 1.7* to 2.1.2. Changed code to use OPartitionedDatabasePool. I have no idea what is happening here. Accessing any simple or complex field of a persisted object produces this exception:

```
Exception in thread "main" java.lang.NullPointerException
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.checkClassRegistration(OObjectEntitySerializer.java:350)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.isTransientField(OObjectEntitySerializer.java:291)
	at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.isGetterMethod(OObjectMethodFilter.java:114)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:114)
	at db.orientdb.model.OrientDBBaseConfiguration_$$_javassist_0.getCiConfigurations(OrientDBBaseConfiguration_$$_javassist_0.java)
	at
[...]
```

Fun fact: With 2.0.15 it works on Linux but not on Windows, 2.1.0/2 fails on both platforms!

**Comment by rkunas** [comment]
Hi, have made some workaround or something for this bug. I have the same issue. We are doing something wrong maybe.      at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.checkClassRegistration(OObjectEntitySerializer.java:350)
     at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.isTransientField(OObjectEntitySerializer.java:291)
     at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.isGetterMethod(OObjectMethodFilter.java:114)
     at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:114)
     at com.aparendo.model.AddressEntity_$$_javassist_1.getStreet(AddressEntity_$$_javassist_1.java)

**Comment by jaggernoth** [comment]
+1

**Comment by tglman** [comment]
this bug seems already fixed by this commit: https://github.com/orientechnologies/orientdb/commit/8f9da3cb0e0692ab88956cd89b2fb199e299ac14
can you check last hotfix: 2.1.7

**Comment by bodiam** [comment]
I tested it with OrientDB 2.1.8, and this bug is still there

```
java.lang.NullPointerException
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.getDeclaredFields(OObjectEntitySerializer.java:1478)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.getField(OObjectEntitySerializer.java:1083)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.getTypeByClass(OObjectEntitySerializer.java:1036)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getDocFieldValue(OObjectProxyMethodHandler.java:379)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:312)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:300)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.manageGetMethod(OObjectProxyMethodHandler.java:289)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:115)
	at com.bpb.amazon.Asin_$$_jvst737_0.getRating(Asin_$$_jvst737_0.java)
```

**Comment by tglman** [comment]
Hi @bodiam,

That error is probably coming from the fact that you don't have the database in the thread, i've done i fix that will specify a better error massage in case that happen.

will be out in 2.1.9 and 2.2

**Comment by bodiam** [comment]
Hi @tglman ,

I'm not sure what you mean, that I don't have the database in the thread? I have retrieved my records, that works. Now, I want to use the records in the view, but whenever I try to access a property of the retrieved documents, I get a nullpointer exception, because these objects are all proxied objects. If I don't close the database connection, which seems like not a smart thing to do, it works, and I don't get the NPE anymore.

Suggestions on how to fix this? I'm running on OrientDB 2.1.8.

**Comment by jaggernoth** [comment]
@bodiam : can you put a sample object class you are trying to save/load

**Comment by bodiam** [comment]
Sure, this my code:

````
@TupleConstructor
//@ToString
@EqualsAndHashCode
class Book {

    String link
    String asin
    String title
    String author
    String description
    Integer numberOfPages
    Date publicationDate

    String smallImage
    String mediumImage
    String largeImage

    String formattedPrice
    BigDecimal rating

    Double getRoundedRating() {

        return Double.valueOf(Math.round(((this.getRating() ?: 0) * 2.0))) / 2.0
    }

    String getShortLink() {
        UrlShortener.shorten(this.link)
    }
}
````

And I retrieve the object like this:

```
            List<Book> books = db.command(new OSQLSynchQuery<Book>("select * from Book SKIP :skp LIMIT :lim")).execute(params)
            int count = db.command(new OSQLSynchQuery<Integer>("select count(*) from Book")).execute(params).get(0).field("count")
```

And if I put a breakpoint at the count, I can see the books. If I exit the method, and I close the DB connection, and I try the same thing (ie accessing a property), I get nullpointer exceptions.

**Comment by tglman** [comment]
Hi @bodiam,

for use object outside a connection scope (ex in the view) you should detach them: http://orientdb.com/docs/last/Object-Database.html#detach

**Comment by bodiam** [comment]
Ah, thanks, I didn't know! Is there also a way to detach my complete collection? I saw there's a detachAll, but that seems to do something very different.

**Comment by tglman** [comment]
hi @bodiam,

The only way to detach a whole collection is iterate on it and run detach for each element. detachAll can help on that if you have a collection inside an object.

**Comment by bodiam** [comment]
I get this issue even when doing a detach of my objects...

````
java.lang.NullPointerException: null
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.setFieldValue(OObjectEntitySerializer.java:1013) ~[orientdb-object-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.detach(OObjectProxyMethodHandler.java:141) ~[orientdb-object-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.detach(OObjectEntitySerializer.java:219) ~[orientdb-object-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.detach(OObjectDatabaseTx.java:311) ~[orientdb-object-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx$detach.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-all-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[groovy-all-2.4.4.jar:2.4.4]
````

This is triggered from this code:

````
            if (results) {
                return db.detach(results.get(0), true); // <-- causes the NPE
            } else {
                return null
            }
```

I'm still on 2.1.8 btw.

**Comment by bodiam** [comment]
I figured out what it means. It means that someField in my database exists, which doesn't exist in my class anymore. This will result in a nullpointer exception. Besides the fact that I find that a bit weird, the error message isn't very helpful either. 

It's caused by the OObjectProxyMethodHandler, where the OObjectEntitySerializer.getField(fieldName, selfClass) takes place. The code assumes that `getField` returns a valid/existing field. It doesn't, because it doesn't exist in my class (anymore). So, doing something like:

```
Field f = OObjectEntitySerializer.getField(fieldName, selfClass)
if(field == null) throw new NullPointerException("Couldn't find field $fieldName in $selfClass")
```

Would have saved me some debugging ;-)

**Comment by tglman** [comment]
hi @bodiam,

Cool that you found the exact point by yourself, i would say that we can open a different issue for that, and if you wont you can contribute with a PR for improve our error messages.

**Comment by bodiam** [comment]
Hi @tglman , thanks for the reply. That might be an option, but I'm not sure if I'll do the pull request. I'm spending too much time on working around issues like this, and I'm considering moving to ArangoDB.

**Comment by LuZhiYuan90** [comment]
@tglman Hi, i met the same problem, if some fileds in the database and doesn't in my java pojo, when i use detach method will result  a nullpointexception,How to solve this problem? Have any @Annotation just like @ignore ？
