### ISSUE TITLE
Can't insert data in distributed setup: Cannot find best cluster for class 'BDH_fe_nl_EXHIB' on server 'test1-dev'. ClusterStrategy=local

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5011]
See also issue #5003

```
Sent run-time exception to the client /172.1
7.64.12:33079: com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDH_fe_nl_EXHIB' on server 'test1-dev'. ClusterStrategy=local
com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDH_fe_nl_EXHIB' on server 'test1-dev'. ClusterStrategy=local
        at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:89)
        at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:60)
        at com.orientechnologies.orient.server.distributed.task.OCreateRecordTask.<init>(OCreateRecordTask.java:76)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:898)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2437)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2407)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1092)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:394)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Sent run-time exception to the client /172.17.64.12:35925: com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDE_fe_nl_CUST' on server 'test1-dev'. ClusterStrategy=local
com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDE_fe_nl_CUST' on server 'test1-dev'. ClusterStrategy=local
        at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:89)
        at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:60)
        at com.orientechnologies.orient.server.distributed.task.OCreateRecordTask.<init>(OCreateRecordTask.java:76)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:898)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2437)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2407)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1092)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:394)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Sent run-time exception to the client /172.17.64.12:33079: com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDH_fe_nl_ITEM' on server 'test1-dev'. ClusterStrategy=local
com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDH_fe_nl_ITEM' on server 'test1-dev'. ClusterStrategy=local
        at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:89)
        at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:60)
        at com.orientechnologies.orient.server.distributed.task.OCreateRecordTask.<init>(OCreateRecordTask.java:76)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:898)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2437)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2407)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1092)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:394)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by lvca** [comment]
How can we reproduce it? Can we schedule an online session with you?

**Comment by wouterv** [comment]
I can reproduce it in our environment, so what we could do is enable debugging and attach an IDE with the orient code in it to the server to see where it goes wrong.

But I'm guessing this will need a restart of the node that goes wrong and that could potentially fix the problem as it gets a fresh db from another node. Or is there another way to enable debugging without restarting?

As for an online session. I can do that monday, preferrable in the morning.

**Comment by wouterv** [comment]
I did some additional testing by running an insert command of one of the failing clusters in test1-dev, there they fail. But when I do it in test2-dev, inserts work fine. So restarting the server would probably fix the problem as a fresh copy of the db will be install. I will try to do an rsync of the live server, hoping that I do not get an inconsistent copy.

**Comment by wouterv** [comment]
I also tried taking the backup and started it on a distributed server with 1 node, but I could just insert data..

**Comment by lvca** [comment]
Could you please acquire logs when this happens again? You can do that at run-time (https://github.com/orientechnologies/orientdb-docs/blob/master/source/Logging.md#on-remote-server)

**Comment by wouterv** [comment]
I ran curl -u root:root -X POST 'http://localhost:2480/server/log.file/FINEST'
responds with: Command not found: server/log.file/FINEST

And the log says 2015-09-28 09:59:26:322 WARNING ->0:0:0:0:0:0:0:1: Command not found: POST.server/log.file/FINEST [ONetworkProtocolHttpDb]

**Comment by lvca** [comment]
The problem relies into the starting sequence: the distributed configuration of the starting node is updated during a distributed deploy. This was the sequence that caused the problem:
- `test2-dev` startup at 13:56
- `test2-dev` online at 13:56
- `test1-dev` startup at 13:57
- `test3-dev` startup at 14:01 <---- NODE `test3-dev` started during node `test1-dev' startup
- `test1-dev` online at 14:09

So node `test3-dev` is started while node `test1-dev` was starting. This seems to cause problems. As temporary workaround please start nodes in sequence.

**Comment by lvca** [comment]
This has benn fixed in 2.1.3 we'll release on Monday or earlier. Once released, could you please confirm if this is gone? Thanks.

**Comment by lvca** [comment]
2.1.3 has been released, please let me know if this is fixed by closing it. Thanks.

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Comment by wouterv** [comment]
It has not been fixed in 2.1.3!
On production we have 3 nodes, prod1, prod2 and prod3. We went from single mode back to distributed mode last tuesday with 2.1.3 and all the distributed-config.json files did only contain prod2 entries, so we got the insert errors agian

**Comment by wouterv** [comment]
The strange this is that prod3 was running and then I started prod1 and 2 simultaneuously.

**Comment by lvca** [comment]
@wouterv could you please share log of 3 servers to see why this happened?

**Comment by wouterv** [comment]
@lvca I'm afraid the old info is already overwritten, as the current default in logging seems to be fine and as I am restarting the servers it writes a LOT of logging, deleting the old logs..

**Comment by wouterv** [comment]
@lvca I think this is another issue that the original one. To fix things, I shutdown all servers. Removed the distributed-config.json from prod2. Started prod2 and started prod1, After all was up, started prod3.

Now the config file only contains cluster info on prod1 and prod3, but not on prod2..

**Comment by wouterv** [comment]
@lvca just send you 3 seperate emails with the server logs. I restarted the whole thing just now, so you can see what happened with the config. We are still missing _prod2 config rows, so I configured our clients to only connect to 1 & 3.

**Comment by lvca** [comment]
I see you have FINE level on file log. This slows down everything. Did you change the default log settings in config/orientdb-server-log.properties

**Comment by lvca** [comment]
By the way I see the node had 8GB of RAM, but OrientDB process has only 0.5G of heap and 1GB of DISKCACHE. How is big your database?

**Comment by wouterv** [comment]
No we did not. These are the default settings in the enterptrise distribution. I doublechecked the tar.gz I downloaded and these are the settings on orientdb-server-log.properties:

``` 
...
# Set the default logging level for new ConsoleHandler instances
java.util.logging.ConsoleHandler.level = FINE
# Set the default formatter for new ConsoleHandler instances
java.util.logging.ConsoleHandler.formatter = com.orientechnologies.common.log.OLogFormatter

# Set the default logging level for new FileHandler instances
java.util.logging.FileHandler.level = FINE
...
```
Looks like somebody f'ed up on your side.

**Comment by wouterv** [comment]
@lvca The machines also run docker instances of our application. Our database is about 27GB (it contains blobs)

**Comment by lvca** [comment]
To disable such deep logging level, please open config/orientdb-server-config.xml and change the logging level of log to info:
 
```xml
<entry value="info" name="log.file.level"/>
```

Could you then try to start servers and send me the logs? Looking what happened should be then straightforward.

**Comment by wouterv** [comment]
@lvca I cant just restart the servers on production, our clients already suffered an outage of an hour today.. Restart means at least 30-40 minutes of downtime due to the db syncing

**Comment by lvca** [comment]
No, I meant pre-production/test env, not production. However if you change the config, and then restart one node per time, you shouldn't have out of service.

**Comment by wouterv** [comment]
@lvca I reproduced the issue on our preproduction servers. Stopped all servers. I cleared the distribution-config.json on prod1. Started prod1, wait until online (fast), start prod2, wait until online (slow). Clusters ending with _prod2 are defined, ending with _prod1 are not. 
Sent the logs to your email.

**Comment by lvca** [comment]
Thanks, I'm reading your logs now.

**Comment by lvca** [comment]
@wouterv this is not an issue: the first cluster is assigned to the first node that starts, with no prefix. The important is that every node has one cluster as ownership. if it's not in the list, then "*" is taken. Do you have the stack trace of the exception about "master cluster not found"?

**Comment by wouterv** [comment]
Master cluster not found we haven't seen, only this:

```
at java.lang.Thread.run(Thread.java:745) com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDH_agradi_nl_ARTICLE' on server 'prod1'. ClusterStrategy=local 
    at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:90) 
    at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:60) 
    at com.orientechnologies.orient.server.distributed.task.OCreateRecordTask.<init>(OCreateRecordTask.java:76) 
    at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:1023) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2582) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2551) 
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1221) 
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400) 
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223) 
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) 
```

**Comment by thiagopm** [comment]
Hi, We are getting the same error: "com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'HashTag' on server 'orientdb1B'. ClusterStrategy=local".

But we are using .Net driver and AWS Elastic Load balancer. 

I don't know if it could be the problem...

**Comment by lvca** [comment]
Hi guys, I think to have found the problem: when first node starts after a clean of distributed cfg (or first start), he doesn't create own clusters, so they are never assigned as master. Working to a fix.

**Comment by lvca** [comment]
Fixed in 2.1.4-SNAPSHOT (2.1.x branch)

**Comment by wouterv** [comment]
Great, I'll test a snapshot build on our preproduction env.

**Comment by thiagopm** [comment]
Where could I Download this SNAPSHOT compiled?

**Comment by lvca** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.1.5-SNAPSHOT/

**Comment by thiagopm** [comment]
thank you

**Comment by wouterv** [comment]
This still broken if you do not start the clusters in sequence. 
I started prod1 without distributed-config.json and then simultaneously prod2 and prod3. Result is that I cannot insert data on node prod2, I see in the cluster config that only prod3 is configured. WIll send you the logs again.

**Comment by wouterv** [comment]
Warning in prod 2 log: 

```
2015-10-17 15:21:27:416 WARNI Cannot find best cluster for class 'BDE_<anonymized>_nl_COUNTRY'. Configured servers for clusters [bde_<anonymized>_nl_country, bde_<anonymized>_nl_country_prod2, bde_<anonymized>_country_prod3, bde_<anonymized>_nl_country_prod1] are [prod2, prod1, prod3] [OLocalClusterStrategy]
```

**Comment by wouterv** [comment]
I tested by starting prod1, starting prod2, waiting for finish, start prod3, wait for finish. Then everything is fine, so this is partially fixed, only the case when you want to startup two nodes simultaneously is still broken, despite being mentioned fixed in 2.1.3, it is not.

**Comment by lvca** [comment]
By watching this error:
```
2015-10-17 15:21:27:416 WARNI Cannot find best cluster for class 'BDE_vandermeer_nl_COUNTRY'. Configured servers for clusters [bde_vandermeer_nl_country, bde_vandermeer_nl_country_prod2, bde_vandermeer_nl_country_prod3, bde_vandermeer_nl_country_prod1] are [prod2, prod1, prod3] [OLocalClusterStrategy]
```

There is a problem in the algorithm because prod2 is in the list of nodes.

**Comment by lvca** [comment]
@wouterv I managed concurrent startup/shutdown of nodes by locking the distributed cfg. Please confirm this problem is gone, so we can close the issue.

**Comment by wouterv** [comment]
Still broken. I start prod1, and start prod2 then prod3 (a few seconds between them) and after a while everything just hangs. Will send you logs and threaddumps

**Comment by wouterv** [comment]
@lvca It could actually be that I created a wrong build myself, can you please provide a fresh 2.1.5 snapshot so I can try again?

**Comment by lvca** [comment]
I'm trying to reproduce it locally now

**Comment by lvca** [comment]
Reproduced on 3 nodes by restarting 2 nodes together, after 3rd time happened. Fixed. Tested 10 times by restarting randomly 3 nodes.

**Comment by wouterv** [comment]
@lvca when can we expect the release of 2.1.5?
