### ISSUE TITLE
Gremlin and Lucene

### ISSUE THREAD

**Issue by fabsx00** [orientechnologies/orientdb#5021]
Hi,

I'm currently trying to access a Lucene Index via Gremlin on OrientDB 2.1.2 (community) , with no luck so far. The index has been created using the Java API using code such as the following:
    
    OrientVertexType vType = noTx.getVertexType("V");
     vType.createIndex("nodeIndex", "FULLTEXT", null, null, "LUCENE",
				indexKeys);

where `noTx` is a handle for the database and `indexKeys` is an array of `properties`.

Retrieving from the index using SQL queries of the format
    
    SELECT * FROM V WHERE [key1,...] LUCENE"query"

works fine, however, trying to access nodes using the gremlin query
    
    g.V(key, val)

fails with a `NullPointerException`. Deleting the index, the above query succeeds.
I have also tried accessing the database via `gremlin.sh` like this:

    $ ./gremlin.sh
    gremlin> g = new OrientGraph("plocal:/tmp/tempDB");

which gives me the following trace:

    Sep 25, 2015 5:46:44 PM com.orientechnologies.common.log.OLogManager log
    INFO: OrientDB auto-config DISKCACHE=29,601MB (heap=455MB os=32,104MB disk=623,039MB)
    Sep 25, 2015 5:46:44 PM com.orientechnologies.common.log.OLogManager log
    SEVERE: {db=tempDB} Error on loading index by configuration:  {type:FULLTEXT,name:nodeIndex.,indexVersion:1,indexDefinition:{className:V,indexDefinitions: [5],indClasses:[5],nullValuesIgnored:true},indexDefinitionClass:com.orientechnologies.orient.core.index.OCompositeInd exDefinition,clusters:[1],mapRid:null,algorithm:LUCENE,valueContainerAlgorithm:SBTREEBONSAISET}
    com.orientechnologies.orient.core.index.OIndexException: Engine type: 'LUCENE' is not supported. Types are [SBTREE,MVRBTREE]. Please

I figure that means the lucene plugin has not been loaded. Is there a way I can load the plugin on the gremlin shell? Or is there a better way to access the index?

**Comment by robfrank** [comment]
Hi @fabsx00, the problem is that the gremlin.sh doesn't include the plugin directory in the classpath. I'm fixing on develop and hotfix branches (2.1.x, 2.0.x) then I'll give you a solution

**Comment by robfrank** [comment]
The script is fixed, please get the right version here:

https://raw.githubusercontent.com/orientechnologies/orientdb/2.1.x/graphdb/script/gremlin.sh

**Comment by fabsx00** [comment]
Hi,
thanks for the quick response. I've tried the 2.1.x branch with the new version of `gremlin.sh`, but unfortunately, the problem remains. Here are the exact steps I took to reproduce:

1. Database and Index Creation: I used the following small program to create a database with a Lucene index on `V`s `myKey` property:


        import com.orientechnologies.orient.core.metadata.schema.OType;
        import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
        import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
        import com.tinkerpop.blueprints.impls.orient.OrientVertexType;
    
        public class OrientDBTest
        {
	    public static void main(String[] args)
	    {
		OrientGraphFactory factory = new OrientGraphFactory(
				"plocal:/tmp/tempDB/", "admin", "admin");

		OrientGraphNoTx noTx = factory.getNoTx();

		OrientVertexType vType = noTx.getVertexType("V");
		vType.createProperty("myKey", OType.STRING);

		vType.createIndex("nodeIndex.", "FULLTEXT", null, null, "LUCENE",
				new String[] { "myKey" });
              }
        }

2. I started `bin/gremlin.sh` and loaded the database like this:
      
        g = new OrientGraph("plocal:/tmp/tempDB");

This then produces the stack trace indicating that Engine type "LUCENE" is not known.

Hope this makes it easier to reproduce. Thanks again for your help.
Fabian

**Comment by robfrank** [comment]
I guess you run the java code inside your IDE, with orientdb-lucene in the classpath. 
Then you build the distribution archive and decompress it to run gremlin.
The archive doesn't contain the lucene jar. 
My suggestion is to download the official package from http://orientdb.com/download/ and patch the gremlin.sh script.

**Comment by fabsx00** [comment]
I tried both: the 2.1.x branch and the official release with a patched `gremlin.sh`. In both cases, I made sure that the lucene plugin is in the plugin directory. Is it working on your side?

**Comment by robfrank** [comment]
I'm sorry. I pushed a wrong version of the script. Please retry with this one:
https://raw.githubusercontent.com/orientechnologies/orientdb/2.1.x/graphdb/script/gremlin.sh

it correctly includes plugins dir in the classpath

**Comment by fabsx00** [comment]
Yes, the plugins directory is on the classpath and it also contains the lucene plugin. Still, I get the same error when trying to create the OrientGraph. Is it possible that putting the jar onto the classpath alone is insufficient? Does it maybe need to be referenced somehow to actually be loaded, i.e., for it's `static{...}` method to be executed? Is it working for you?

**Comment by robfrank** [comment]
I've just done these steps:
- download of orient-commmunity-2.1.2 
- untar it
- replace of gremlin.sh in bin dir with https://raw.githubusercontent.com/orientechnologies/orientdb/2.1.x/graphdb/script/gremlin.sh
- run console to create the database and the index (more after)
- run gremlin and open the created db
- gremlin opens the db without errors

So, in console I did:
orientdb> create database plocal:/tmp/testDb admin admin plocal
orientdb {db=testDb}> create property V.title string
orientdb {db=testDb}> create index nodeIndex on V (title) fulltext engine lucene

and in gremlin

./gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
gremlin> g = new OrientGraph("plocal:/tmp/testDB");
Oct 01, 2015 11:41:51 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=5,431MB (heap=455MB os=7,935MB disk=65,082MB)
==>orientgraph[plocal:/tmp/testDB]

**Comment by fabsx00** [comment]
ok, thanks for testing this. I'm assuming the remaining problem is on my side then ;) I'll close this.

**Comment by robfrank** [comment]
thank you very much for the report, I hope you'll solve the problem
