### ISSUE TITLE
Parse bug for select from ...  where matches with parameter

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5229]
Reproduction is easy.

Add the following line to method testMatches in OSelectStatementTest:

```
checkRightSyntax("select from Person where name matches :param1");
```
The following error will occur:
```
com.orientechnologies.orient.core.sql.parser.ParseException: Encountered "" at line 1, column 26.
Was expecting one of:
    
	at com.orientechnologies.orient.core.sql.parser.OrientSql.generateParseException(OrientSql.java:12583)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_consume_token(OrientSql.java:12453)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.NotBlock(OrientSql.java:5015)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.AndBlock(OrientSql.java:4910)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.OrBlock(OrientSql.java:4860)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.WhereClause(OrientSql.java:4825)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.SelectStatement(OrientSql.java:612)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.QueryStatement(OrientSql.java:408)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:324)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:79)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatementTest.checkSyntax(OSelectStatementTest.java:28)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatementTest.checkRightSyntax(OSelectStatementTest.java:17)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatementTest.testMatches(OSelectStatementTest.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatementTest.checkSyntax(OSelectStatementTest.java:40)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatementTest.checkRightSyntax(OSelectStatementTest.java:17)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatementTest.testMatches(OSelectStatementTest.java:347)
```

**Comment by lsavio** [comment]
We reproduced the problem and we took it in charge.

**Comment by luigidellaquila** [comment]
Hi @wouterv 

I fixed the problem, the fix in on 2.1.x branch.
I'm keeping this open to port the fix on develop branch

Thanks (and thanks @lsavio for the help)

Luigi

**Comment by luigidellaquila** [comment]
Hi @wouterv 

I also ported the fix on develop branch. It can be closed if it's ok on your side.

Thanks

Luigi

**Comment by wouterv** [comment]
@luigidellaquila it works for most cases indeed, thank you  for that. 
But I have an issue when there are special characters in the expression. 

In 2.0.x we used java.util.regex.Pattern.quote(expression) to make sure that special characters are not interpreted als regex, but in 2.1.x this doesn't work anymore.

Here's a testcase of what I mean

add to initialization
```
    db.command(new OCommandSQL("CREATE class matchesstuff")).execute();

    db.command(new OCommandSQL("insert into matchesstuff (name, foo) values ('admin[name]', 1)")).execute();
```

```
  @Test
  public void testParamWithMatchesQuoteRegex(){
    //issue #5229
    Map<String, Object> params = new HashMap<String, Object>();
    params.put("param1", ".*admin[name].*");//will not work
    OSQLSynchQuery sql = new OSQLSynchQuery("select from matchesstuff where name matches :param1");
    List<ODocument> results = db.query(sql, params);
    assertEquals(results.size(), 0);
    params.put("param1", Pattern.quote("admin[name]") + ".*");//should work
    results = db.query(sql, params);
    assertEquals(results.size(), 1);
  }

```

**Comment by luigidellaquila** [comment]
Hi @wouterv 

Thanks a lot, I'm adding the test case to the suite, I'll give you an ETA in short

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @wouterv 

I fixed the problem, you can find the fix in 2.1.x branch (soon also in develop).
In a few hours we will also release 2.1.5, it will contain this fix.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed also in develop branch. Please let me know if I can close 

Thanks

Luigi

**Comment by wouterv** [comment]
Got another testcase which goes wrong with regard to match and quoting:
An and/not query works when not quoting, but fails when using quotes (we are using a generic system, so these queries+params are generated).

```
  @Test
  public void testParamWithMatchesAndNot(){
    //issue #5229
    Map<String, Object> params = new HashMap<String, Object>();
    params.put("param1", "adm.*");
    params.put("param2", "foo.*");
    OSQLSynchQuery sql = new OSQLSynchQuery("select from OUser where (name matches :param1 and not (name matches :param2))");
    List<ODocument> results = db.query(sql, params);
    assertEquals(results.size(), 1);

    params.put("param1",  Pattern.quote("adm") + ".*");
    results = db.query(sql, params);
    assertEquals(results.size(), 1);
  }
```

**Comment by luigidellaquila** [comment]
Hi @wouterv 

I think this is another issue, in particular it's not related to named parameters. I tried the following 

```sql
Map<String, Object> params = new HashMap<String, Object>();
    OSQLSynchQuery sql = new OSQLSynchQuery("SELECT FROM OUser WHERE (name MATCHES '\\\\Qadm\\\\E.*' AND NOT (name MATCHES 'foo.*' ) )");
    List<ODocument> results = db.query(sql, params);
    assertEquals(results.size(), 1);
```
and it fails too.
It seems the matcher is not using quoted strings properly.
I'm investigating it, I'll let you know soon

Thanks

Luigi

**Comment by wouterv** [comment]
I'm not seeing a fix for the last issue I posted. And if I add my test on 2.1.x, it still fails.

**Comment by wouterv** [comment]
@luigidellaquila I try to reopen this issue from prjhub, but the button doesn't do anything.

**Comment by luigidellaquila** [comment]
Hi @wouterv 

I just pushed a fix on 2.1.x branch, could you please check if it completely solves your problem?

Thanks

Luigi

**Comment by wouterv** [comment]
Hi @luigidellaquila 

I pulled the latest source with your new tests in it and add mine as quote above:
```
  @Test
   public void testParamWithMatchesAndNot(){
     //issue #5229
     Map<String, Object> params = new HashMap<String, Object>();
     params.put("param1", "adm.*");
     params.put("param2", "foo.*");
     OSQLSynchQuery sql = new OSQLSynchQuery("select from OUser where (name matches :param1 and not (name matches :param2))");
     List<ODocument> results = db.query(sql, params);
     assertEquals(results.size(), 1);

     params.put("param1",  Pattern.quote("adm") + ".*");
     results = db.query(sql, params);
     assertEquals(results.size(), 1);
   }
```
And this still fails..

**Comment by luigidellaquila** [comment]
Hi @wouterv 

I tried your test case, it seems the evaluation of the regexp is clashing with collate strategy on OUser.name. It seems that the '\Qadm\E.*' expression is being collated to '\qadm\e.*' that obviously is not correct.

The test case on a different class (your first test on 'select from matchesstuff') works fine.

I think

**Comment by luigidellaquila** [comment]
Hi @wouterv 

I just pushed a fix on 2.1.x branch.
I just disabled collate on statements that use MATCHES on a regular expression, IMHO it just doesn't make sense

Thanks

Luigi

**Comment by wouterv** [comment]
All our test are now green, thanks!
