### ISSUE TITLE
Transaction issue - sql parser and rollback does not work

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5235]
This tx should not work because there exist no vertex with the mid "550f1ae5d41a5d027d27b412".
After executing in studio orientdb creates a new ShopUser vertex but the other commands doesn't throw an exception.

```
LET t0 = create vertex ShopUser cluster DE_shopUser content {"DisplayName":"Natalia Fruck","Mid":"562e6df4fa52aacf2a582d51","Active":true,"Position":"shop_user","Email":"test@test.de","Created":1445982670949}
LET t1 = UPDATE Node ADD References = $t0  WHERE Mid = '550f1ae5d41a5d027d27b412'
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node  WHERE Mid = '550f1ae5d41a5d027d27b412'  )
```

 I follow the transaction feature since I joined to orientdb 2.0.4 -> 2.1.4 and until now nobody see the big issue in this implementation. This is both sad and disturbing.

**Comment by StarpTech** [comment]
Orientdb: 2.1.4
Strict sql: yes
Studio: Batch

Or other queries which are valid.

```
LEt $t4 = find references #14:0
LET t0 = UPDATE Node ADD References = $t4
LET t1 = create vertex node content { "test": "wedwed" }
```

```
LEt $t4 = select from node
LET t0 = UPDATE Node ADD References = $t6666666666666
LET t1 = create vertex node content { "test": "wedwed" }
```

```
LET t0 = UPDATE Node ADD wdwedwe = dwedwedwed
LET t1 = create vertex node content { "test": "wedwed" }
```

I thought we have a new sql parser?

**Comment by StarpTech** [comment]
Or another in COMMAND mode

```
UPDATE Node ADD References = $t6666666666666
```
this will update all queries and leads to this result

```
"References": [
                null,
                "#3:0",
                "#3:2",
                "#3:1"
            ]
```

**Comment by luigidellaquila** [comment]
The problem here is that OrientDB works schemaless, a query like
```
LET t0 = UPDATE Node ADD wdwedwe = dwedwedwed
LET t1 = create vertex node content { "test": "wedwed" }
```
makes sense because  ```dwedwedwed``` can be defined in some documents but not in others (so default to ```null```).

The system is supposed to tolerate records with different attributes and default to null when a value for an attribute is not defined, this is why you are not receiving an exception here.

OrientDB has specific operators to deal with non existing fields, such as ```is defined``` and ```is not defined```, maybe they can help in your use case?
Please let me know how I can give support on this

Thanks

Luigi

**Comment by StarpTech** [comment]
@luigidellaquila yes, this is the last example but the less important one. Look at my first issue:

```
LET t0 = create vertex ShopUser cluster DE_shopUser content {"DisplayName":"Natalia Fruck","Mid":"562e6df4fa52aacf2a582d51","Active":true,"Position":"shop_user","Email":"test@test.de","Created":1445982670949}
LET t1 = UPDATE Node ADD References = $t0  WHERE Mid = '550f1ae5d41a5d027d27b412'
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node  WHERE Mid = '550f1ae5d41a5d027d27b412'  )
```

You arguments is not valid here a transaction should be Atomic either all occur, or nothing occurs.

**Comment by StarpTech** [comment]
@luigidellaquila ?

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I discussed it with the team, what you expect can make sense, but it's not the current behavior.

Probably what you need is something like

```
if ($t1 == null) ROLLBACK
```

It's not currently supported, but probably it's not hard to implement.
It will give you much finer control on scripted transactions.

I'm analyzing a possible implementation, I'll let you know very soon

Thanks

Luigi

**Comment by StarpTech** [comment]
@luigidellaquila thank you.

**Comment by StarpTech** [comment]
@luigidellaquila Any progress?

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I implemented it in develop branch and I'm testing it, I'll push it to the repo as soon as all tests pass.
The backporting to 2.1.x should be simple 

Thanks

Luigi

**Comment by StarpTech** [comment]
This sounds great! Thanks.

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I just pushed the new implementation in develop branch.
The syntax is following:

```
if(<sql predicate>){
  <statement>
  <statement>
  ...
}
```

Now I'm backporting it to 2.1.x, I hope I won't encounter problems there.

Thanks

Luigi

**Comment by StarpTech** [comment]
Hi luigidellaquila can you give me an example related to my problem? When it will be released?

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I just pushed it in both 2.1.x and develop branches, here you can find some docs (it's quite simple)

https://github.com/orientechnologies/orientdb-docs/blob/master/SQL-batch.md

About your use case, it could be something like 

```sql
LET t0 = create vertex ShopUser cluster DE_shopUser content {"DisplayName":"Natalia Fruck","Mid":"562e6df4fa52aacf2a582d51","Active":true,"Position":"shop_user","Email":"test@test.de","Created":1445982670949}
LET $t0 = select from Node WHERE Mid = '550f1ae5d41a5d027d27b412'
if($t0.size() == 0){
    ROLLBACK
    RETURN
}
LET t1 = UPDATE Node ADD References = $t0  WHERE Mid = '550f1ae5d41a5d027d27b412'
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node  WHERE Mid = '550f1ae5d41a5d027d27b412'  )
```

I did not try this specific case, so it will probably need some small changes (eg. null check)

Thanks

Luigi

**Comment by StarpTech** [comment]
Thanks I will try.

**Comment by LucaSon90** [comment]
Hi @StarpTech,
can we consider the issue closed ?

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I suppose this is solved. I'm closing this issue, please reopen if you experience any related problems

Thanks

Luigi

**Comment by StarpTech** [comment]
Hi @luigidellaquila the `if` expression is really helpful thanks but from developer point of view it doesnt solve the issue.
In the documentation there is: `OrientDB is an ACID compliant DBMS.`
That's wrong at least in the case of `Atomic` because I have to check the results sets of all my queries to avoid secondary failures. This should be documented unless full ACID is supported. Orientdb have to check the transactions constraint itself.

**Comment by StarpTech** [comment]
@luigidellaquila

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I see it in a different way, the second statement actually succeeds. The fact that no records are updated is not a failure, it's just the expected behavior of an UPDATE when no records match the WHERE condition. See it in a different way: when you execute a simple, single statement UPDATE that does not match any records, do you expect an exception?

So the ACID compliance is guaranteed from my point of view.

Thanks

Luigi

**Comment by StarpTech** [comment]
ACID compliance is not a personally thing. When I talk about Atomicity then I see the whole thing and that is the transaction not a single command.

**Comment by luigidellaquila** [comment]
Atomicity means that if I update three records, at the end of the transaction all the three are updated or none of them is. In this case, all the statements are correctly executed


```
BEGIN;
UPDATE Foo SET bar = 1 WHERE field = 'matches one record';
UPDATE Foo SET bar = 1 WHERE field = 'matches zero records';
UPDATE Foo SET bar = 1 WHERE field = 'matches ten records';
COMMIT;
```
if the third statement fails to update one of the ten records, then you have a failure and a rollback, but if the second one just does not match any records, then the statement is correctly executed, with no exception and no error.

The semantics of UPDATE is "update all the records that match a particular condition with some values", if there are no records that match the criteria, no records are updated, but the UPDATE operation succeeds and respects the semantics. Do you get my point?

Thanks

Luigi

**Comment by StarpTech** [comment]
You view a single update command as a transaction but what is with constraints between multiple commands? E.g

```
BEGIN;
$1 = CREATE VERTEX Foo;
$2 = CREATE VERTEX Bar;
CREATE EDGE E FROM $1 to $2; 
COMMIT;
```
When $1 or $2 failed then the transaction can not be viewed as valid. He must be rollbacked.

**Comment by luigidellaquila** [comment]
In that case nothing strange can happen, you are just creating three records, so if one of the three is not created, then there was an error.

A similar case to the original one would be 

```
BEGIN;
$1 = SELECT FROM Foo;
$2 = SELECT FROM Bar;
CREATE EDGE E FROM $1 to $2; 
COMMIT;
```

That should be the same as

```
CREATE EDGE E FROM (SELECT FROM Foo) to (SELECT FROM Bar);
```

In this case, if no vertices are present, then no edges should be created. Actually I think there is a specific check on CREATE EDGE, that ensures that there are valid vertices on both sides, and it fails if it's not the case, but again, if it's there (and I still did not remove it...) it's specific to CREATE EDGE

Thanks

Luigi
