### ISSUE TITLE
Lucene Spatial Index files not closed after database.drop() in 2.1.5 and 2.1.7

### ISSUE THREAD

**Issue by EricSchreiner** [orientechnologies/orientdb#5304]
db = getPooledDbInstance();
db.activateOnCurrentThread(); 
db.drop();

After this sequence Lucene files are still existion and open so the database directory cannot be deleted.

**Comment by maggiolo00** [comment]
hi @EricSchreiner 
are you in plocal or remote?

Do you get any exception?

**Comment by EricSchreiner** [comment]
hi @maggiolo00 
it's plocal no Exceptions
One of or unittests fails because it cannot delete the database directory after a drop. I found out that the reason for this seems to be that some Lucene index files have not been closed files

**Comment by maggiolo00** [comment]
hi @EricSchreiner 

i've executed this unit test and passes

```JAVA
@Test
  public void testDeleteLuceneIndex() {

    ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal:databases/testRemove");

    try {
      db.create();
      OClass test = db.getMetadata().getSchema().createClass("test");
      test.createProperty("name", OType.STRING);
      test.createProperty("lat", OType.DOUBLE);
      test.createProperty("long", OType.DOUBLE);
      db.command(new OCommandSQL("create index test.name on test (name) FULLTEXT ENGINE LUCENE")).execute();

      db.command(new OCommandSQL("create index test.ll on test (lat,long) SPATIAL ENGINE LUCENE")).execute();

      ODocument doc = new ODocument();

      doc.field("name", "Test");
      doc.field("lat", 0);
      doc.field("long", 0);
      db.save(doc);
    } finally {
      db.drop();
    }

    File dbFolder = new File("databases/testRemove");

    Assert.assertEquals(false, dbFolder.exists());
  }
```


Can you help me to replicate the issue?
Thanks

**Comment by EricSchreiner** [comment]
hi @maggiolo00 
it seems that the test only fails if you insert data and query the data (see below).
If you set INSERTCOUNT to 0 it will work
if you set INSERTCOUNT to 100 and remove the three lines for the select it will also work

```java
@Test
  public void testDeleteLuceneIndex1() {

    String dbName="plocal:./playground/db/db.2.1.5";
    
    int INSERTCOUNT=100; // @maggiolo00 set cont to 0 and the test will not fail anymore
    
    ODatabaseDocumentTx db = new ODatabaseDocumentTx(dbName);

    db.create();
    OClass test = db.getMetadata().getSchema().createClass("test");
    test.createProperty("name", OType.STRING);
    test.createProperty("latitude", OType.DOUBLE).setMandatory(false);
    test.createProperty("longitude", OType.DOUBLE).setMandatory(false);
    db.command(new OCommandSQL("create index test.name on test (name) FULLTEXT ENGINE LUCENE")).execute();
    db.command(new OCommandSQL("create index test.ll on test (latitude,longitude) SPATIAL ENGINE LUCENE")).execute();
    db.close();
    
    OPartitionedDatabasePool dbPool = new OPartitionedDatabasePool(dbName, "admin", "admin");
    
    db=dbPool.acquire();
    fillDb(db,INSERTCOUNT);
    db.close();
    
    db=dbPool.acquire();
    // @maggiolo00 Remove the next three lines and the test will not fail anymore
    OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>("select from test where [latitude,longitude] WITHIN [[50.0,8.0],[51.0,9.0]]");
    List<ODocument> result =db.command(query).execute();
    Assert.assertEquals(INSERTCOUNT, result.size());
    db.close();
    
    db=dbPool.acquire();
    db.drop();
    
    File dbFolder = new File("./playground/db/db.2.1.5");
    Assert.assertEquals(false, dbFolder.exists());
    
    File dbFolderRoot = new File("./playground/db");
    dbFolderRoot.delete();
    Assert.assertEquals(false, dbFolderRoot.exists());
  }
    

  private void fillDb(ODatabaseDocumentTx db, int count ) {
    for(int i=0;i<count;i++) {
      ODocument doc = new ODocument("test");
      doc.field("name", "Test"+i);
      doc.field("latitude", 50.0+(i*0.000001));
      doc.field("longitude", 8.0+(i*0.000001));
      db.save(doc);
    }
    OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>("select * from test");
    List<ODocument> result =db.command(query).execute();
    Assert.assertEquals(count, result.size()); 
  }
  

```

**Comment by maggiolo00** [comment]
hi @EricSchreiner 

even with insert and query on my box still passes.

Can you show me your pom?

**Comment by EricSchreiner** [comment]
@maggiolo00  Have you used my code or did you update yours? If you have updated yours please note
that in your original test was an error: 
```java
ODocument doc = new ODocument();
```
should be replaced by
```
ODocument doc = new ODocument("test");
```
And now my (hopefully not too stupid) question: What is a pom?

**Comment by maggiolo00** [comment]
@EricSchreiner i used your code
i changed only the db location

pom is for maven dependency in your project to include orientdb.

Did you copy manually the libraries in your classpath?

**Comment by EricSchreiner** [comment]
@maggiolo00  yes I've copied manually. This is my classpath:
FindBugs-2.0.2\
ccBase-small.jar
ccUser2v1.0.jar
commons-fileupload-1.3.1.jar
commons-io-2.4.jar
concurrentlinkedhashmap-lru-1.4.jar
imgscalr-lib-4.2.jar
jasypt-1.9.2.jar
javax.mail-1.5.0.jar
jetty-continuation-9.2.9.v20150224.jar
jetty-http-9.2.9.v20150224.jar
jetty-io-9.2.9.v20150224.jar
jetty-security-9.2.9.v20150224.jar
jetty-server-9.2.9.v20150224.jar
jetty-servlet-9.2.9.v20150224.jar
jetty-util-9.2.9.v20150224.jar
jna-4.0.0.jar
jna-platform-4.0.0.jar
lucene-analyzers-common-4.7.0.jar
lucene-core-4.7.0.jar
lucene-facet-4.7.0.jar
lucene-memory-4.7.0.jar
lucene-misc-4.7.0.jar
lucene-queries-4.7.0.jar
lucene-queryparser-4.7.0.jar
lucene-sandbox-4.7.0.jar
lucene-spatial-4.7.0.jar
metadata-extractor-2.6.4.jar
mockito-all-1.10.19.jar
orientdb-core-2.1.5.jar
orientdb-lucene-2.1.5.jar
servlet-api-3.1.jar
snappy-java-1.1.0.1.jar
spatial4j-0.4.1.jar
xercesImpl.jar
xmpcore.jar

**Comment by EricSchreiner** [comment]
Hi @maggiolo00 
any news. Is it reproducible now?

**Comment by EricSchreiner** [comment]
Also checked with 2.1.7. Problem still exists

**Comment by kalmusr** [comment]
Hi All, I have the same problem with lucene indexes (using .net OriendDB binary driver).

@EricSchreiner: Are you using linux or windows operating system?
For me it appears only on windows. On Linux the lucene indexes were always dropped properly.

**Comment by EricSchreiner** [comment]
@kalmusr I'm currently just testing on Windows

**Comment by EricSchreiner** [comment]
Also checked with 2.1.8. Problem still exists

**Comment by EricSchreiner** [comment]
Hi @lvca, any ideas when it will be fiexed?

**Comment by maggiolo00** [comment]
@EricSchreiner 

on my mac i'm unable to reproduce it.


@robfrank 
do you have any idea why this test could fail on Windows?

**Comment by EricSchreiner** [comment]
Hi @maggiolo00 
sorry but I have no idea. I guess it has to to with the Lucene implementation

**Comment by EricSchreiner** [comment]
Hi @lvca, any ideas when it will be fiexed?

**Comment by robfrank** [comment]
Hi, these problems with Lucene on Windows are fixed on the next 2.2.1 release

**Comment by EricSchreiner** [comment]
Hi @lvca, @robfrank  Please reopen. This issue can still be reproduced under Windows as described above with version 2.2.13. It's now a year ago and we are still not capable to run our test environment....
