### ISSUE TITLE
GraphSail is broken because of invalid edge lable encoding 

### ISSUE THREAD

**Issue by fabianmeyer** [orientechnologies/orientdb#5424]
When running the example code of the Tinkerpop GraphSail outplementation (https://github.com/tinkerpop/blueprints/wiki/Sail-Ouplementation), the OrientBaseGraph throws a: com.orientechnologies.orient.core.exception.OSchemaException: Invalid class name found. Character '%' cannot be used in class name 'http%3A%2F%2Ftinkerpop.com%23knows'

The OrientBaseGraph uses the java.net.URLEncoder to encode the class name of the label. The encoder in fact maps the IRI "http://tinkerpop.com#knows" to "http%3A%2F%2Ftinkerpop.com%23knows", which is an invalid class name.

Example code:
```java
	OrientGraph graph = new OrientGraph("remote:localhost/test");
		try {
			Sail sail = new GraphSail<>(graph);
			sail.initialize();
			ValueFactory vf = sail.getValueFactory();
			SailConnection sc = sail.getConnection();
			sc.begin();

			sc.addStatement(vf.createURI("http://tinkerpop.com#1"), vf.createURI("http://tinkerpop.com#knows"),
					vf.createURI("http://tinkerpop.com#3"), vf.createURI("http://tinkerpop.com"));
			sc.addStatement(vf.createURI("http://tinkerpop.com#1"), vf.createURI("http://tinkerpop.com#name"),
					vf.createLiteral("marko"), vf.createURI("http://tinkerpop.com"));
			sc.addStatement(vf.createURI("http://tinkerpop.com#3"), vf.createURI("http://tinkerpop.com#name"),
					vf.createLiteral("josh"), vf.createURI("http://tinkerpop.com"));

			System.out.println("get statements: ?s ?p ?o ?g");
			CloseableIteration<? extends Statement, SailException> results = sc.getStatements(null, null, null, false);
			while (results.hasNext()) {
				System.out.println(results.next());
			}

			System.out.println("\nget statements: http://tinkerpop.com#3 ?p ?o ?g");
			results = sc.getStatements(vf.createURI("http://tinkerpop.com#3"), null, null, false);
			while (results.hasNext()) {
				System.out.println(results.next());
			}

			sc.rollback();
			sc.close();
			sail.shutDown();
			graph.shutdown();
		} catch (SailException e) {
			e.printStackTrace();
		} finally {
			graph.shutdown();
		}
```

Full exception:
```
Exception in thread "main" com.orientechnologies.orient.core.exception.OSchemaException: Invalid class name found. Character '%' cannot be used in class name 'http%3A%2F%2Ftinkerpop.com%23knows'
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:407)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:400)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:100)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$6.call(OrientBaseGraph.java:1392)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$6.call(OrientBaseGraph.java:1389)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1744)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createEdgeType(OrientBaseGraph.java:1389)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createEdgeType(OrientBaseGraph.java:1373)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createEdgeType(OrientBaseGraph.java:1358)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:928)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addEdge(OrientBaseGraph.java:687)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addEdge(OrientBaseGraph.java:84)
	at com.tinkerpop.blueprints.oupls.sail.GraphSailConnection.addStatementInternal(GraphSailConnection.java:251)
	at com.tinkerpop.blueprints.oupls.sail.GraphSailConnection.addStatementInternal(GraphSailConnection.java:197)
	at org.openrdf.sail.helpers.SailConnectionBase.addStatement(SailConnectionBase.java:471)
	at de.hs_rm.cs.vs.OrientDBTest.main(OrientDBTest.java:25)
```

**Comment by luigidellaquila** [comment]
Hi @fabianmeyer 

that limitation has been there for a long time, but probably it can be removed thanks to the new support for backtick quoting of class names.
I'm double-checking it, I'll let you know

Thanks

Luigi

**Comment by fabianmeyer** [comment]
Hi,

is there any other way to use OrientDB as a Sail? I only saw the architecture overview (http://orientdb.com/docs/last/Java-API.html#architecture-of-components) in the documentation, containing the "Sail" function block and thought it's realized through the GraphSail outplementation.

**Comment by luigidellaquila** [comment]
Hi @fabianmeyer 

I just pushed a fix for this in branch 2.1.x.
Now I'm porting it to develop branch

Thanks

Luigi

**Comment by fabianmeyer** [comment]
Hi, the example is still broken:

Invalid class name found. Character '.' cannot be used in class name 'http%3A%2F%2Ftinkerpop.com%23knows'

**Comment by luigidellaquila** [comment]
Hi @fabianmeyer 

the '.' can be used in a class name, but it has to be quoted with back-ticks, eg.
```
select from `foo.bar`
``` 
We should check Sails code and see if it correctly quotes the class name.

Thanks

Luigi

**Comment by fabianmeyer** [comment]
I think it's a broken encoding in "OrientBaseGraph.encodeClassName(String iClassName)", which simply transforms the edge label into an encoded URL. An encoded URL can contain [A-Z, a-z], [0-9], '%', '-', '_', '.' and '~'.

**Comment by fabianmeyer** [comment]
Same problem occurs with the field names, where '%' is currently not a valid character, but is encoded by the OrientBaseGraph.

**Comment by lvca** [comment]
Thanks @fabianmeyer  for the PR.

**Comment by lvca** [comment]
I don't know why @tglman reverted it, but because of it I have to report this issue.

**Comment by lvca** [comment]
Fixed again by allowing % in class (and property) names.
