### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#5556]
Hi, guys. Some strange things are going on when I'm trying to run tests on OrientDB. It seems that something went wrong and a bunch of tests are constantly failing. Check this out - http://helios.orientechnologies.com/job/orient-maven/1165/. My result is pretty much the same.

**Comment by luigidellaquila** [comment]
Hi @maseev 

probably that problem is already fixed, I see no failing tests locally.

Please refer to http://helios.orientdb.com/ as the other CI server is being discontinued.

Thanks

Luigi

**Comment by maseev** [comment]
Here's what I did:

* Pulled the latest version of the develop branch
* run ``` mvn clean test ``` from the root folder

Here's the result:

```
Results :

Failed tests: 
  OStoragePerformanceStatisticTest.testReadSpeedFromCache:46->testMBeanCase:378 expected [9765] but found [-1]
  OStoragePerformanceStatisticTest.testReadSpeedFromFile:79->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testWriteSpeedToCache:112->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testWriteSpeedToFile:145->testMBeanCase:340 expected [false] but found [true]

Tests run: 1235, Failures: 4, Errors: 0, Skipped: 0
```

Am I supposed to do something specific to make the tests pass?

**Comment by maseev** [comment]
I was able to run all tests, eventually. Everything is ok now. Still don't understand what changed, but all test are passing now without any errors.

By the way, why don't you guys add your project to [coveralls](https://coveralls.io/), so people could see the code coverage on the title page? I think it would be a great idea to show everyone how mature your product is. What do you think?

**Comment by luigidellaquila** [comment]
Hi @maseev 

Thank you for the report, I think I can close this issue now.

About coveralls, we are thinking about that, but does it really add important value when used with an internal CI?

Thanks

Luigi

**Comment by maseev** [comment]
About coveralls - it simply provides, among other advantages, a test coverage badge that you can put on the README page. It will show to other users how mature your project is. I think this is great to know that code of the project I'm going to use is covered with unit and integration tests thoroughly. Don't you think?

**Comment by maseev** [comment]
@luigidellaquila [here](https://github.com/maseev/narwhal), it's not that difficult to integrate your project with travis-ci and coveralls. In my case I only had to add [two](https://github.com/maseev/narwhal/blob/master/pom.xml#L43) plugins and add a [.travis.yml](https://github.com/maseev/narwhal/blob/master/.travis.yml) file. I also added two badges to the README file so everyone can see that build is passing as well as the test coverage percentages. Cool huh?
