### ISSUE TITLE
case insensitive ISSUE

### ISSUE THREAD

**Issue by seeden** [orientechnologies/orientdb#5895]
Hi 

I have two collections named book and user. User has field name which is case insensitive.
Book has a linked class user. OrientDB version (2.1.10 and latest 2.1.13)

When I use
```sql
SELECT * FROM user WHERE name LIKE "adam%"
```
I will get 1 record
```js
{ name: 'Adam Smith' }
```
When I try to find all book with query
```sql
SELECT * FROM book WHERE user.name LIKE "adam%"
```

I will get 0 records.

But next query is working correctly
```sql
SELECT * FROM book WHERE user.name LIKE "Adam%"
```
I will get 1 book.

I guess that orientdb has a bug because it will forget to use case insensitive search.

**Comment by seeden** [comment]
Maybe it is related with https://github.com/orientechnologies/orientdb/issues/5394 somehow

**Comment by seeden** [comment]
It is not working with = too

It is working with
```sql
SELECT * FROM book WHERE user.name = "Adam Smith"
```

It is NOT working
```sql
SELECT * FROM book WHERE user.name = "adam smith"
```

Collate is set to CI for user.name

**Comment by seeden** [comment]
I can see same issue in the latest version 2.1.13

**Comment by luigidellaquila** [comment]
Hi @seeden 

Thank you for reporting. I think this issue is related to the fact that the query is checking only the schema of the target class, so the CI on the linked class is not taken into consideration (it's just a guess, I have to double check)

I'll take a look at that asap

Thanks

Luigi

**Comment by seeden** [comment]
Hi @luigidellaquila 

I was thinking in the same way. Thank you for your fast reaction

Zlatko

**Comment by luigidellaquila** [comment]
Hi @seeden 

I just pushed a fix on 2.1.x branch, the fix will be available in v 2.1.16

Now I'm porting the fix to develop (2.2)

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Done, pushed fix and a specific test case.

I'm closing this issue, please reopen if you see any related problems

Thanks

Luigi

**Comment by seeden** [comment]
Thank you @luigidellaquila 
I will wait for next release.

**Comment by seeden** [comment]
@luigidellaquila I have tried latest 2.1.16 and this issue is still there.

**Comment by luigidellaquila** [comment]
Hi @seeden 

I just tried latest 2.1.16 and it seems to work fine... could you please provide a full test case or script to reproduce it?

Thanks

Luigi
