### ISSUE TITLE
Long running application using OPartitionedDatabasePool causing a OTokenSecurityException: missing session and token

### ISSUE THREAD

**Issue by ajob61** [orientechnologies/orientdb#6177]
We have been testing our application with 2.2.0 GA to validate if being investigate migration from using it the 2.1.x versions. For context our application connects to the OrientDB server remotely as a client on the same environment and we use the OPartitionedDatabasePool for handling the accessing ODatabaseDocumentTx instances from multiple threads. 

All was going well in our testing, the application was acquiring ODatabaseDocumentTx instances via multiple threads via OPartitionedDatabasePool and performing several CRUD operations. However after running for a while and we begin to see the following exceptions logged out on the orientdb server logs.

_com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	Storage URL="plocal:/Applications/OrientDB/orientdb-community-2.2.0/databases/dbname"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:268)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)_

Which we have never seen before in the 2.0.x or 2.1.x versions.

Also Corresponding on our application logs we are seeing the following multiple instances of the following messages

_May 20, 2016 10:32:26 PM com.orientechnologies.common.log.OLogManager log
WARNING: Caught I/O errors from Not connected (local socket=/127.0.0.1:50297), trying to reconnect (error: java.io.EOFException)
May 20, 2016 10:32:26 PM com.orientechnologies.common.log.OLogManager log
WARNING: Connection re-acquired transparently after 2ms and 1 retries to server '127.0.0.1:2424/dbname': no errors will be thrown at application level
May 20, 2016 10:32:26 PM com.orientechnologies.common.log.OLogManager log
WARNING: Caught I/O errors from Not connected (local socket=0.0.0.0/0.0.0.0:50300), trying to reconnect (error: java.io.EOFException)
May 20, 2016 10:32:26 PM com.orientechnologies.common.log.OLogManager log_

However even though these messages indicate a reconnection, from the point that these messages begin to be thrown no CRUD operations persist, which causes our multiple thread instances to hang, repeating the same CRUD operation over and over.

Restart the app and it starts off ok as before but again will begin to exhibit the above behaviour after some time has passed.

Has anyone else seen this behaviour or these messages? I have looked at the documentation for 2.2 to see if there some additional steps that I maybe missing in the migration however I don't believe I am.

This behaviour is occurring on both our local Mac Development environments and our Linux Test environments.

### Runninng Mode
Remote

### OrientDB Version
 v2.2.0

### Operating System
Linux & MacOSX

### Java Version
8

**Comment by lvca** [comment]
@tglman Is this already fixed in 2.2.1-SNAPSHOT?

**Comment by tglman** [comment]
Hi,

Yes this should be fixed already in 2.2.1 SNAPSHOT, closing

**Comment by ajob61** [comment]
Just tried it on snapshot build orientdb-community-2.2.1-20160524.123408-24.

Still getting 
com.orientechnologies.common.log.OLogManager.log Caught I/O errors, trying to reconnect (error: null) errors.

com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	Storage URL="plocal:/usr/local/username/orientdb-community-2.2.1-SNAPSHOT/databases/db_name"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:268)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

Could you advise the snapshot that this has been addressed in?

**Comment by tglman** [comment]
The commits that fix that issue is: https://github.com/orientechnologies/orientdb/commit/7838653fdbe138f944e139e7514eedc7f648ac03 and this: https://github.com/orientechnologies/orientdb/commit/b5d13cbee268bf3caf45380597b5ae6381f6e0f6, so any snapshot after the 19th of May should be fine, in any case the fix is on the client, did you update the client as well ?

**Comment by ajob61** [comment]
Yes updated the client to the snapshot orientdb-community-2.2.1-20160524.123408-24 as well. Again it seems to time out after about 20 mins and stop working.

_May 25, 2016 10:10:35 PM com.orientechnologies.common.log.OLogManager log
WARNING: Caught I/O errors, trying to reconnect (error: null)_

Looking at one of the stack traces on the client example

_com.orientechnologies.common.io.OIOException
	at com.orientechnologies.orient.client.remote.OStorageRemote.handleIOException(OStorageRemote.java:201)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:184)
	at com.orientechnologies.orient.client.remote.OStorageRemote.updateRecord(OStorageRemote.java:695)
	at com.orientechnologies.orient.core.config.OStorageConfiguration.update(OStorageConfiguration.java:213)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.set(ODatabaseDocumentTx.java:1505)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.setValidationEnabled(ODatabaseDocumentTx.java:1084)
	at com.orientechnologies.orient.core.intent.OIntentMassiveInsert.end(OIntentMassiveInsert.java:114)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.declareIntent(ODatabaseDocumentTx.java:1123)_

**Comment by tglman** [comment]
hi @s19n,

We fixxed some more issue on the network recently, in both server and client, now you should not see any error, except if you restart the server.

Can you confirm if also in your case is fixed?

**Comment by tglman** [comment]
hi @s19n,

We fixxed some more issue on the network recently, in both server and client, now you should not see any error, except if you restart the server.

Can you confirm if also in your case is fixed?

**Comment by tglman** [comment]
closing this again, with 2.2.1 we fixed many other issue that could cause this.

**Comment by ajob61** [comment]
Just retried on 2.2.2. Still getting messages in the client app.

_Jun 17, 2016 2:30:20 PM com.orientechnologies.common.log.OLogManager log
WARNING: Caught I/O errors, trying to reconnect (error: Channel is closed)_

with the matching server error

_Error executing request_
_com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	DB name="tangara2"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:281)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:227)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:185)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)_

It again runs fine for the first 30 mins. Then we start to see these errors. Is there a timeout which I should be setting on my OPartitionedDatabasePool?

**Comment by lvca** [comment]
It looks like 2.2.3-SNAPSHOT fixed this problem, please @ajob61 can you check it>

**Comment by stdunbar** [comment]
I'm using "OrientDB Server v2.2.3 (build 2.2.x@r2f229613abac00036c2fa1b59ab5d1e8a882d6de; 2016-06-20 06:46:10+0000)" and am seeing this issue.  I also have "The token provided is expired" in my logs.

**Comment by stdunbar** [comment]
And "OrientDB Server v2.2.4 (build 2.2.x@rf5282664db9300ef3358fb4d7e2066ad418c2e61; 2016-07-08 12:30:59+0000)" - same issue.  2.2.x is completely unusable for us.  We're using 2.2.4 of the client side libraries too.

**Comment by lvca** [comment]
We solved this problem in v2.2.5. Could you please update both client & server libs to 2.2.5?

**Comment by andeliero92** [comment]
i have the same issue:

`com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:289)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:289)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired
	DB name="ship-boat-scadenziario"
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:289)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	DB name="ship-boat-scadenziario"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:285)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	DB name="ship-boat-scadenziario"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:285)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	DB name="ship-boat-scadenziario"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:285)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	DB name="ship-boat-scadenziario"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:285)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)` 

and in my client:
`2016-07-22 10:54:08,914 [WARN] from com.orientechnologies.orient.client.remote.OStorageRemote in application-akka.actor.default-dispatcher-4 - Caught I/O errors, trying to reconnect (error: Channel is closed)
2016-07-22 10:55:15,415 [WARN] from com.orientechnologies.orient.client.remote.OStorageRemote in application-akka.actor.default-dispatcher-2 - Caught I/O errors, trying to reconnect (error: Channel is closed)`

**Comment by tglman** [comment]
hi,

With 2.2.7 we fixed all the problem we know about session management, so also this should be fixed, do you confirm?

**Comment by andeliero92** [comment]
yes, i confirm. With 2.2.7 works fine.
