### ISSUE TITLE
HTTP API causes ODistributedRecordLockedException and never releases lock.

### ISSUE THREAD

**Issue by tenderlygloriousgentleman** [orientechnologies/orientdb#6449]
## Expected behavior and actual behavior
I am getting many of these exceptions recorded in the database logs:
```
2016-07-20 19:28:18:114 SEVER Internal server error:
com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Record with rid #277:0 is locked by request 1.1920
        DB name="22222222-2222-2222-2222-222222222222" [ONetworkProtocolHttpDb]
```

The problem, once hit, seems to cause the server to become unresponsive and triggers
many warnings like this:

`2016-07-20 23:03:02:505 WARNI [node1467916585553] Detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=1.665 task=tx) [ODistributedResponseManager]`

This warning shows up exactly 10 times per id, which I assume is a default (why doesn't specifying `commit retry 100` make it retry 100 times?).

The only way to recover from this issue is to restart all the servers.

I am using the HTTP api against two connected servers, and accessing only the BATCH endpoint at a constant rate (possibly tens of calls per second). It seems weird that the server is not closing the transaction at the end of an HTTP call.

## Steps to reproduce the problem
First see the Misc section below for a description of the distributed topology I am using.

I have a load test that is generating many HTTP requests and selects one of the server nodes at random. The HTTP requests are all very similar. The request payload consists of SQL, and goes to the BATCH endpoint (described here: [http://orientdb.com/docs/last/SQL-batch.html](http://orientdb.com/docs/last/SQL-batch.html)).

Here is an example of the SQL script:
```
begin

...

let character = select from V_Character where (P_Uuid = 'ed04364b-4acd-46b3-8cba-99426aadcb1c')
let tt_root = select expand(out('DetectedBy')) from $character
if($tt_root.size() < 1) {
let tt_root = create vertex TimeTreeRoot set P_Version = '0.0.0', P_Uuid = 'c7f50aaf-d9c6-417b-a37a-37e7ebbb45b3'
create edge DetectedBy from $character to $tt_root set P_Version = '0.0.0', P_Context = '84002db3-bcbf-4a9d-b73a-ebfe73ea07c5', P_Uuid = 'f4aadfca-7cac-4d8d-9ebb-5cd4e08584da', P_DeclarationTime = 1469046877538
}

let tt_year = select from (select expand(out('TimeTreeAt')) from $tt_root) where (TimeTreeYear = 2016)
if($tt_year.size() < 1) {
let tt_year = create vertex TimeTreeYear set P_Version = '0.0.0', TimeTreeYear = 2016
create edge TimeTreeAt from $tt_root to $tt_year set P_Version = '0.0.0'
}

let tt_month = select from (select expand(out('TimeTreeAt')) from $tt_year) where (TimeTreeMonth = 7)
if($tt_month.size() < 1) {
let tt_month = create vertex TimeTreeMonth set P_Version = '0.0.0', TimeTreeMonth = 7
create edge TimeTreeAt from $tt_year to $tt_month set P_Version = '0.0.0'
}

let tt_day = select from (select expand(out('TimeTreeAt')) from $tt_month) where (TimeTreeDay = 20)
if($tt_day.size() < 1) {
let tt_day = create vertex TimeTreeDay set P_Version = '0.0.0', TimeTreeDay = 20
create edge TimeTreeAt from $tt_month to $tt_day set P_Version = '0.0.0'
}

let tt_hour = select from (select expand(out('TimeTreeAt')) from $tt_day) where (TimeTreeHour = 20)
if($tt_hour.size() < 1) {
let tt_hour = create vertex TimeTreeHour set P_Version = '0.0.0', TimeTreeHour = 20
create edge TimeTreeAt from $tt_day to $tt_hour set P_Version = '0.0.0'
}

let tt_minute = select from (select expand(out('TimeTreeAt')) from $tt_hour) where (TimeTreeMinute = 34)
if($tt_minute.size() < 1) {
let tt_minute = create vertex TimeTreeMinute set P_Version = '0.0.0', TimeTreeMinute = 34
create edge TimeTreeAt from $tt_hour to $tt_minute set P_Version = '0.0.0'
}

let tt_second = select from (select expand(out('TimeTreeAt')) from $tt_minute) where (TimeTreeSecond = 37)
if($tt_second.size() < 1) {
let tt_second = create vertex TimeTreeSecond set P_Version = '0.0.0', TimeTreeSecond = 37
create edge TimeTreeAt from $tt_minute to $tt_second set P_Version = '0.0.0'
}

let transactionEdge_0 = create edge DetectedBy from $tt_second to $transactionVertex_0 set P_Version = '0.0.0', P_Context = '84002db3-bcbf-4a9d-b73a-ebfe73ea07c5', P_Uuid = '2c182e5c-261e-4cb7-853a-7c408dc99de0', P_DeclarationTime = 1469046877538

...

commit retry 100
```

The difference between each call is the values for `TimeTreeYear`, `TimeTreeMonth`, ..., `TimeTreeSecond`, and `P_DeclarationTime`. These are values generated on the fly where the `P_DeclarationTime` is a Unix time and the `TimeTree*` values are the corresponding values for this unix time. Also, I want to point out that the `P_Uuid` properties are unique indices.

After generating many of these HTTP requests and hitting the BATCH api, we eventually hit the issue,
maybe after some tens of successful calls.

### Runninng Mode
Remote

### Misc
I have a distributed setup with 2 servers that are connected on a private network
in the cloud. They are able to connect using Hazelcast because I explicitly list
the private IP addresses in the hazelcast.xml file.

I am NOT using the Enterprise Edition.

Here is an image of what the graph looks like after completing successfully several calls before it eventually hits the issue:
![orientdbquestionimage](https://cloud.githubusercontent.com/assets/12654349/17007138/0f65a96a-4e9b-11e6-827b-baecda14683c.PNG)
### OrientDB Version
- v2.2.3

### Operating System
Linux

### Java Version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by lvca** [comment]
We fixed this kind of issue in the last 2.2.5. Please let me know.

**Comment by tenderlygloriousgentleman** [comment]
I have tried the repro in 2.2.5. I still have issues. I am getting these errors:

```
2016-07-22 03:29:02:166 WARNI [node1469141456917] Detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=0.676 task=tx) [ODistributedResponseManager]
2016-07-22 03:29:02:270 WARNI [node1469141456917] Detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=0.676 task=tx) [ODistributedResponseManager]
2016-07-22 03:29:02:379 WARNI [node1469141456917] Detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=0.676 task=tx) [ODistributedResponseManager]
2016-07-22 03:29:02:499 WARNI [node1469141456917] Detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=0.676 task=tx) [ODistributedResponseManager][node1469141456917] Error on fixing transaction 0.676 db=22222222-2222-2222-2222-222222222222 task=record_update(#50:0 v.108 realV.-2147483540)
java.lang.NullPointerException: Impossible to add a null identifiable in a ridbag
        at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.addEntry(OEmbeddedRidBag.java:492)
        at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.doDeserialization(OEmbeddedRidBag.java:541)
        at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.convertLinks2Records(OEmbeddedRidBag.java:278)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.convertLinks2Records(ORidBag.java:166)
        at com.orientechnologies.orient.core.record.impl.ODocument.mergeMap(ODocument.java:2155)
        at com.orientechnologies.orient.core.record.impl.ODocument.merge(ODocument.java:1218)
        at com.orientechnologies.orient.server.distributed.impl.task.OUpdateRecordTask.executeRecordTask(OUpdateRecordTask.java:113)
        at com.orientechnologies.orient.server.distributed.task.OAbstractRecordReplicatedTask.execute(OAbstractRecordReplicatedTask.java:103)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTxContextImpl.fix(ODistributedTxContextImpl.java:80)
        at com.orientechnologies.orient.server.distributed.impl.task.OCompletedTxTask.execute(OCompletedTxTask.java:116)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage$12.call(ODistributedStorage.java:1724)
        at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.executeUndoOnLocalServer(ODistributedStorage.java:1708)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager$1.call(ODistributedTransactionManager.java:204)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager$1.call(ODistributedTransactionManager.java:85)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.executeOperationInLock(ODistributedStorage.java:1067)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.commit(ODistributedTransactionManager.java:85)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1247)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:566)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2693)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2662)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:321)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:194)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:101)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:85)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2653)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2599)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:257)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:196)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:165)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:613)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-07-22 03:29:02:502 SEVER Internal server error:
com.orientechnologies.orient.core.exception.OTransactionException: New record allocated #52:0 but the expected was #52:159
        DB name="22222222-2222-2222-2222-222222222222" [ONetworkProtocolHttpDb]
```

This issue is corrupting the graph too, for example I have edges that only have one vertex on one side of the edge.

**Comment by tenderlygloriousgentleman** [comment]
Also, with 2.2.5, it seems like none of the transactions ever succeed completely, whereas with 2.2.3 at least some transactions succeeded.

**Comment by tenderlygloriousgentleman** [comment]
I built and used commit d7d81cd0bebbf7591daf8349684ae65f73c1bcfb.

I still get the same errors (i.e. requests are almost all ignored). I also still get the corruption of the graph. I am attaching pictures to clarify what I mean by the corruption.

![orientdbquestionimage1](https://cloud.githubusercontent.com/assets/12654349/17113363/43cfac2e-525f-11e6-9da0-543a24c6c505.PNG)
![orientdbquestionimage2](https://cloud.githubusercontent.com/assets/12654349/17113365/482885f2-525f-11e6-996a-d0beeda21602.PNG)

The second image shows the data for the vertex with RID #294:0.

**Comment by tenderlygloriousgentleman** [comment]
I also wanted to add some information. I replicated the scenario in the older version of 2.1.15, and everything behaved as expected in the older version of OrientDb.

**Comment by lvca** [comment]
Did you tried with 2.2.6-SNAPSHOT? Other users report it resolves all these kinds of problems.

**Comment by tenderlygloriousgentleman** [comment]
Yes, the 2.2.6-SNAPSHOT was at commit d7d81cd0bebbf7591daf8349684ae65f73c1bcfb when I pulled. It produced the output seen above in my comment on July 25, 2016.

**Comment by lvca** [comment]
No, I mean the 2.2.6 of 12h ago. Please can you try it?

**Comment by lvca** [comment]
@tenderlygloriousgentleman any news on this?

**Comment by lvca** [comment]
Closing. In case comment/reopen it.
