### ISSUE TITLE
SEVER Internal server error

### ISSUE THREAD

**Issue by smil2k** [orientechnologies/orientdb#6474]
## OrientDB Version, operating system, or hardware.
- v2.2,5
  ## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

Hi,

This is the only log what we got from orientdb when tried to query the database. No other information is available.

How to gain more insight of the "internal server error"?

I would expect a lenghty stacktrace or some other pointers, but nothing is to be seen in the log.

**Comment by maggiolo00** [comment]
Hi @smil2k 

what do you have in OrientDB logs?

**Comment by smil2k** [comment]
$ docker logs orient 2>&1 | grep Internal -A 10 -B 10

java.lang.ArrayIndexOutOfBoundsException
$ANSI{green {db=demo0727}} Error transforming record #293:2291 to JSON
java.lang.ArrayIndexOutOfBoundsException
$ANSI{green {db=demo0727}} Error transforming record #294:2323 to JSON
java.lang.ArrayIndexOutOfBoundsException
$ANSI{green {db=demo0727}} Error transforming record #293:2357 to JSON
java.lang.ArrayIndexOutOfBoundsException
$ANSI{green {db=demo0727}} Error transforming record #294:2389 to JSON
java.lang.ArrayIndexOutOfBoundsException

2016-07-27 20:10:36:732 SEVER Internal server error:
java.lang.ArrayIndexOutOfBoundsException [ONetworkProtocolHttpDb]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
        DB name="lhvc"
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:285)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
16523.796: [GC (Allocation Failure) [PSYoungGen: 256928K->14880K(249856K)] 377250K->135377K(796160K), 0.0322927 secs] [Times: user=0.08 sys=0.00, real=0.03 secs] 
16526.979: [GC (Allocation Failure) [PSYoungGen: 248864K->15456K(249856K)] 369361K->135953K(796160K), 0.0185182 secs] [Times: user=0.07 sys=0.00, real=0.02 secs] 
--
2016-07-27 20:07:47:704 SEVER Internal server error:
16192.363: [GC (Allocation Failure) [PSYoungGen: 268956K->1856K(269824K)] 367994K->100909K(816128K), 0.0048838 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]
2016-07-27 20:08:39:864 SEVER Internal server error:
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
        DB name="lhvc"
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:285)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-07-27 20:09:18:093 SEVER Internal server error:
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]
2016-07-27 20:09:23:212 SEVER Internal server error:
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]
2016-07-27 20:09:27:219 SEVER Internal server error:
16310.711: [GC (Allocation Failure) [PSYoungGen: 268608K->3040K(263680K)] 367661K->109710K(809984K), 0.0254719 secs] [Times: user=0.05 sys=0.04, real=0.03 secs] 
16311.520: [GC (Allocation Failure) [PSYoungGen: 263648K->5792K(266752K)] 370318K->112494K(813056K), 0.0102526 secs] [Times: user=0.03 sys=0.00, real=0.01 secs] 
16312.484: [GC (Allocation Failure) [PSYoungGen: 266400K->6112K(259584K)] 373102K->118400K(805888K), 0.0156945 secs] [Times: user=0.05 sys=0.01, real=0.02 secs] 
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]
2016-07-27 20:09:48:330 SEVER Internal server error:
16314.057: [GC (Allocation Failure) [PSYoungGen: 259552K->9696K(256512K)] 371840K->128344K(802816K), 0.0263007 secs] [Times: user=0.07 sys=0.02, real=0.02 secs] 
16314.718: [GC (Allocation Failure) [PSYoungGen: 256480K->9696K(251904K)] 375128K->129690K(798208K), 0.0183416 secs] [Times: user=0.06 sys=0.01, real=0.02 secs] 
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
        DB name="lhvc"
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:285)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
--
2016-07-27 20:06:26:303 SEVER Internal server error:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.;select * from bucket_ARE_label groupId = 'ESE-2B5B1CB4-5435-11E6-863B-0242AC140008'
        DB name="demo0727" [ONetworkProtocolHttpDb]
2016-07-27 20:06:37:731 SEVER Internal server error:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.;select * from bucket_ARE_label groupId = "ESE-2B5B1CB4-5435-11E6-863B-0242AC140008"
        DB name="demo0727" [ONetworkProtocolHttpDb]
2016-07-27 20:06:42:932 SEVER Internal server error:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.;select * from bucket_ARE_label where groupId = "ESE-2B5B1CB4-5435-11E6-863B-0242AC140008"
        DB name="demo0727" [ONetworkProtocolHttpDb]
2016-07-27 20:06:49:231 SEVER Internal server error:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.;select * from bucket_ARE_label where groupId = 'ESE-2B5B1CB4-5435-11E6-863B-0242AC140008'
        DB name="demo0727" [ONetworkProtocolHttpDb]
--

**Comment by tglman** [comment]
hi @smil2k,
the errors:
`OCommandExecutorNotFoundException: Cannot find a command executor for the command request:`
are due to some attempt to query the database while was doing a shutdown.
Nothing critical.

**Comment by smil2k** [comment]
HI,

Actually the database was not shutting down! 
The application was running fine during that time, the queries were executed by the web client.

Cheers,

Tamas

**Comment by mmacfadden** [comment]
For what it is worth I am getting a similar error.  I don't have all of the stack trace at the moment, but what I am seeing is that in studio, I keep getting the yellow banner at the top that says "Server might be offline. Please check your server status."  This happens just about every time I issue a query.  The database is definitely not shutting down.

**Comment by smil2k** [comment]
HI,

Same here: studio keeps saying "server might be offline". We did not have this in 2.1 and as far as I can recall in 2.2.3.

Cheers,

Tamas

**Comment by tglman** [comment]
hi All,

Actually re-reading the log i saw that there are a few errors mixed, like expiring sessions, socket close and out of memory errors hidden by the GC errror :`[GC (Allocation Failure) [PSYoungGen: 259552K->9696K(256512K)] 371840K->128344K(802816K), 0.0263007 secs] [Times: user=0.07 sys=0.02, real=0.02 secs] `

So i think all this strange issue were happening just due to an out of memory, and the failure of the GC of clean up the resources used.

What was the memory status of the server when this happened?

**Comment by smil2k** [comment]
The server stops every 11 days due to outofmemory. The problem was addressed presumably by 2.2.7. 

My expectation holds true anyhow: writing internal error without ANY clue in the log is not a best practice.

**Comment by mmacfadden** [comment]
It could have been a memory issue.  however, I was running this on a server with 2.2.0 with no problem.  The only change was the upgrade to 2.2.5.  Reverting back to 2.2.0 solved the problem.  I will check with 2.2.7 and I will also try adjusting the memory.

**Comment by mmacfadden** [comment]
I just updated to 2.2.8 and I am getting this all the time.  I am running in the docker container at the moment.  The studio is pretty much unusable at this point.  Every single query I run shows the following message in the studio:

""

And shows this in the console (over and over):

java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]
2016-09-02 05:29:39:175 SEVER Internal server error:
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]
2016-09-02 05:35:42:973 SEVER Internal server error:
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]

The server is definitely out running out of memory.  My first request would be to make sure an actual stack trace is being printed when this happens.

**Comment by mmacfadden** [comment]
Also, I have about 2GB free memory in the docker container (I think), so I don't think it is a memory issue.

**Comment by tglman** [comment]
hi @mmacfadden,

This is strange, in any case can you try the lastest release 2.2.10 and try to get a memory dump in case you have an OutOfMemory.

Regards.

**Comment by mmacfadden** [comment]
@tglman Sorry I should have come back and commented.  The real issue I am having is this one over here:

https://github.com/orientechnologies/orientdb/issues/6647

I am not sure if the two are related.  One thing I would say is that the fix that is really needed at the moment is for when this error crops up to print out a stack trace.  I will make a PR for that.

**Comment by tglman** [comment]
hI @mmacfadden,

Ok let's follow up there.

@smil2k is this fixed for you with the 2.2.10 ?

Regards

**Comment by smil2k** [comment]
Yes. I can still reproduce it. 

I think I was able to narrow down the problem to my browser:
Chromium Version 51.0.2704.79 Ubuntu 14.04 (64-bit)

If I open the studio using chromium, then this happens. Maybe it cuts the connection early.

**Comment by mmacfadden** [comment]
@smil2k Can you try disabling the network streaming option?

**Comment by smil2k** [comment]
Only if you show me how can I do that ;)

Cheers,

Tamas

**Comment by mmacfadden** [comment]
@smil2k Take a look at this issue here:

https://github.com/orientechnologies/orientdb/issues/6647

I am wondering if it is related.  If you look at the github repo reference there, you will find a config file that disables streaming by adding the following line:

``` <entry name="network.http.streaming" value="false" />```

For me this 'fixed' the problem.  Although we still don't know exactly what the underlying issue is.

**Comment by tglman** [comment]
hi @smil2k, @mmacfadden,

We did some changes fixed on http in 2.2.10, so this should be solved even without the flag, can you try the 2.2.10 and let me know if this solve your problem?

Thanks

**Comment by smil2k** [comment]
It seems it is working fine in chrome.

**Comment by smil2k** [comment]
Hi,

I just checked it again, still not working using chromium.

**Comment by tglman** [comment]
just pushed a fix that

**Comment by tglman** [comment]
hi @smil2k,

Last fix should have been released, can you try 2.2.18 and let us know if this is finally fixed also in your case?

Regards

**Comment by tglman** [comment]
Hi,

Fixed and release a while ago, closing.

Regards
