### ISSUE TITLE
DEFAULT schema values and CUSTOM fields not preserved on import/export

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6514]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[x] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Expected: exporting a database, then importing the same file into a new database preserves field DEFAULT values.

Actual: the imported database has no DEFAULT values on any fields.

## Steps to reproduce the problem

```
create database remote:localhost:2424/test_defaults <user> <pass> memory graph

create class V1 extends V
create property V1.id String
create property V1.name String
alter property V1.name default 'default_here'
create vertex V1 set id='1'
select name from V1 where id='1'

> ----+------+------------
> #   |@CLASS|name        
> ----+------+------------
> 0   |null  |default_here
> ----+------+------------

export database /tmp/data.zip

###

create database remote:localhost/test_defaults2 <user> <pass> memory graph
import database /tmp/data.zip.gz

select name from V1 where id='1'

> ----+------+------------
> #   |@CLASS|name        
> ----+------+------------
> 0   |null  |default_here
> ----+------+------------

create vertex V1 set id='2'
select name from V1 where id='2'

> ----+------
> #   |@CLASS
> ----+------
> 0   |null  
> ----+------
```

Note how the last insert should have created a "name" column with value "default_here", but the select shows no such column exists.

Unrelated bug: note that the syntax for IMPORT DATABASE and EXPORT DATABASE is inconsistent -- IMPORT DATABASE requires a filename including its extension, while EXPORT DATABASE tacks `.gz` onto whatever filename is passed in.

**Comment by obi1kenobi** [comment]
The export / import process also doesn't preserve CUSTOM data set on classes, like so:
```
ALTER CLASS V1 CUSTOM foo=bar
```

**Comment by lvca** [comment]
This has been already fixed. @tglman can you confirm it?

**Comment by obi1kenobi** [comment]
@lvca can you confirm which version it's fixed in? It's definitely not fixed in 2.1.16 or 2.1.9.

**Comment by tglman** [comment]
hi,

This has been fixed in 2.2.5, the fix hasn't been ported yet to 2.1.x, if needed i can port it.

Regards

**Comment by a-unite** [comment]
@tglman it is definitely  needed and we are still looking for it too.

Thanks

**Comment by tglman** [comment]
hi, 
I just ported the fix in 2.1.x should be released in 2.1.21

Regards

**Comment by obi1kenobi** [comment]
Hi @tglman, thanks for the quick fix. Just to confirm, which of the three issues I referred to were you able to fix?
- `ALTER PROPERTY foo.bar DEFAULT baz` not applied on `IMPORT DATABASE`
- `ALTER CLASS foo CUSTOM bar=baz` not applied on `IMPORT DATABASE`
- `IMPORT DATABASE` and `EXPORT DATABASE` require different filepath arguments

**Comment by tglman** [comment]
hi @obi1kenobi,

the default value and custom value are fixed, for the different arguments orient happen everytime .gz beacuse the export is an archive, if you already do an export with .gz (like `myExp.json.gz`) it will not append it.

Bye

**Comment by obi1kenobi** [comment]
Thanks for the clarification!

**Comment by obi1kenobi** [comment]
I just downloaded version 2.2.7 and can confirm that this issue is in fact NOT fixed. Neither CUSTOM fields nor DEFAULT properties are preserved. I'm not sure what fix was applied in 2.2.5, but it doesn't seem to have worked.

**Comment by tglman** [comment]
hi @obi1kenobi, 

I just rexectued all the steps and seems to work fine are you sure you are using 2.2.7 ?

Regards

**Comment by obi1kenobi** [comment]
So first of all, I can't even run the reproduction code on 2.2.7 because creating the database immediately fails, whereas the same command worked on 2.1.16:
```
OrientDB console v.2.2.7 (build 2.2.x@rdcab5af4dce4b538bdb4b372abba46e3fc9f19b7; 2016-08-11 15:17:33+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> create database remote:localhost:2424/test_defaults <user> <password> graph

Creating database [remote:localhost:2424/test_defaults] using the storage type [graph]...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: test_defaults

Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing

Error: java.lang.IllegalArgumentException: Cannot create database: storage mode 'graph' is not supported.
```

Hacking around that by creating the databases in Studio ahead of time, we see that the syntax of the `ALTER CLASS CUSTOM` command has changed -- while the value in the 2.1.x series was required to NOT be in quotes, now I get a parsing error:
```
orientdb {db=test_manual_default}> alter class V1 custom set_data=hello world

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter class V1 custom set_data=hello world
                                         ^
Encountered " <IDENTIFIER> "world "" at line 1, column 38.
Was expecting one of:
    <EOF> 
    <UNSAFE> ...
    ";" ...
    <UNSAFE> ...
    <UNSAFE> ...
    
	DB name="test_manual_default"
	DB name="test_manual_default"
```

I think the quotes are great, I just would have expected some warning -- I didn't see any mention of this breaking change in the [release notes](http://orientdb.com/docs/last/Release-2.2.0.html).

Finally, it appears that the issue might not be deterministically reproducible -- sometimes CUSTOM fields are imported and sometimes not. I created a CUSTOM class field on class V1 in database `test_manual_default`, then exported it to a file and imported the file into database `test_manual_default_2`. This is the output of a "lucky" run: note how `customFields` has data in the first database, but not the other.
```
orientdb {db=test_manual_default}> select name, customFields from (select expand(classes) from metadata:schema) where name='V1'

+----+----+----------------------+
|#   |name|customFields          |
+----+----+----------------------+
|0   |V1  |{set_data=hello world}|
+----+----+----------------------+

1 item(s) found. Query executed in 0.007 sec(s).

orientdb {db=test_manual_default_2}> select name, customFields from (select expand(classes) from metadata:schema) where name='V1'

+----+----+
|#   |name|
+----+----+
|0   |V1  |
+----+----+
```

However, running the following script 3-4 more times, I was unable to cause the same outcome to happen. Unfortunately, I used the same file path to export to, so the "lucky" run's output file was overwritten by my subsequent runs.
```
create database remote:localhost:2424/test_manual_default <user> <password> plocal graph
create class V1 extends V
alter class V1 custom set_data="hello world"
select name, customFields from (select expand(classes) from metadata:schema) where name='V1'
export database /tmp/export_data.json.gz
disconnect

create database remote:localhost:2424/test_manual_default_2 <user> <password> plocal graph
import database /tmp/export_data.json.gz
select name, customFields from (select expand(classes) from metadata:schema) where name='V1'
```

I'm not sure how to proceed best here, and I leave the issue in your capable hands.

**Comment by obi1kenobi** [comment]
Was the original bug on the import side or the export side? I have no way to verify this, but it's possible that for the runs that had missing data, I may have accidentally used an archive file from a pre-2.2.5 version of OrientDB. If the bug was on the export side, this would probably manifest in missing data when importing the archive in 2.2.7.

**Comment by PhantomYdn** [comment]
Guys, due to this issue OrientDB 2.1.21 is broken! All our previously setuped default values like `sysdate("yyyy-MM-dd HH:mm:ss")` stopped working! Had to rollback.

**Comment by tglman** [comment]
Hi obi1kenobi,

The original bug was on export, so if you have an old export it does not contains the data.

@PhantomYdn what's the case that create the problem for you? Regards

**Comment by PhantomYdn** [comment]
@tglman, case is very simple: we had database on 2.1.19 where some properties had default values set up.
Then we made just changing of minor version to 2.1.21: from absolutely lovely haven everything turned to  burning by exceptions hell. We had to return back to 2.1.19.
One type of exception mentioned above.

Other interesting: why simple query to DB executes default value functions?

**Comment by PhantomYdn** [comment]
@tglman , any comments? I see that 2.1.22 released, but it seems to be without fix for this issue.

**Comment by tglman** [comment]
hi @PhantomYdn,

I think is better oper another issue and track that, the reason why the could be calculated the default value on query, is because it happen when we set the class of a document, and that can happen also when we build a result set, we may move that calculation in a different place, but we need your help on that, due to the fact that it come from one of your Pull Request and i don't want to break even more your use cases.

Regards

**Comment by obi1kenobi** [comment]
This is not fixed as of OrientDB 2.2.8, and potentially an even worse bug has been introduced:

```
$ ./console.sh

OrientDB console v.2.2.8 (build 2.2.x@r39259e190e16045fe1425b1c0485f8562fca055b; 2016-08-23 14:38:49+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect remote:localhost:2424/test2 admin admin
orientdb {db=test2}> create class V1 extends V
orientdb {db=test2}> create property V1.name String
orientdb {db=test2}> alter property V1.name default ''
orientdb {db=test2}> alter class V1 custom foo="bar baz"
orientdb {db=test2}> export database /test2.json.gz
orientdb {db=test2}> disconnect

orientdb> create database remote:localhost:2424/test3 admin admin memory graph
orientdb {db=test3}> import database /test2.json.gz
orientdb {db=test3}> select name, customFields from (select expand(classes) from #0:1) where name='V1'

+----+----+
|#   |name|
+----+----+
|0   |V1  |
+----+----+
```

Note that no custom fields are present, even though we set a custom field named `foo` with value `"bar baz"`.

Furthermore,
```
orientdb {db=test3}> export database /test3.json.gz

$ gunzip /test2.json.gz
$ gunzip /test3.json.gz
```

The following data in the `"schema"` key in `/test2.json` is *entirely missing* from `/test3.json`:
```
{
  "name": "V1",
  "default-cluster-id": 11,
  "cluster-ids": [
    11
  ],
  "super-classes": [
    "V"
  ],
  "cluster-selection": "round-robin",
  "properties": [
    {
      "name": "name",
      "type": "STRING",
      "collate": "default",
      "default-value": ""
    }
  ],
  "customFields": {
    "foo": "bar baz"
  }
}
```

@tglman I'm not sure how you re-ran my steps, but clearly something is still wrong here.

**Comment by tglman** [comment]
Hi @obi1kenobi,

I'll double check everything again and let you know.

Regards

**Comment by obi1kenobi** [comment]
Thanks!

(replying to remove the "waiting reply" label)

**Comment by tglman** [comment]
hi @obi1kenobi,

I reproduced it, and the problem is only in remote, i added the tests for embedded and seems to work, i'll try to fix this also in remote.

**Comment by obi1kenobi** [comment]
Thanks for the update. Any idea on why remote and embedded treat import/export differently? That sounds very concerning regardless of this bug...

**Comment by tglman** [comment]
Hi, 
I actually improved the test, found the problem and fixed, was happening in both plocal and remote.

will be released in 2.2.10

**Comment by obi1kenobi** [comment]
Thanks, looking forward to 2.2.10 getting released!
