### ISSUE TITLE
Order BY @RID DESC stops working in 2.2

### ISSUE THREAD

**Issue by AlessandroRota** [orientechnologies/orientdb#6694]
See the question on google groups https://groups.google.com/forum/#!topic/orient-database/v7hPzH-6-4I

Hi altogether

I am in the process of adapting ActiveOrient (https://github.com/topofocus/active-orient) to Version 2.2.
And found that  DatabaseClass#Last returns the first instead of the last record.

The following query is transmitted by the test-suite:

 select  from industry  order by @rid desc

The result is the same as

 select  from industry 

I verified this in studio.
The documentation @ http://orientdb.com/docs/2.2/SQL-Query.html
refers explicit to this feature:

Return records from the class Profile in descending order of their creation:

orientdb> SELECT FROM Profile ORDER BY @rid DESC

Beginning in version 1.7.7, OrientDB can open an inverse cursor against clusters. This is very fast and doesn't require the classic ordering resources, CPU and RAM.

Is this a bug or missed I something?

**Comment by mindnuts** [comment]
@lvca I do not see any milestone attached to this bug. I think this issue is quite serious as sorting records by @rid does not work when there are multiple clusters for a Class.

**Comment by luigidellaquila** [comment]
Hi @mindnuts 

My bad, I just set it to next hotfix. I'll work on this in next hours

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @AlessandroRota @mindnuts 

I just pushed a fix on 2.2.x. The fix will be released in 2.2.11

Thanks

Luigi

**Comment by mindnuts** [comment]
@luigidellaquila I just downloaded 2.2.11 and i can see that its not fixed. I am able to reproduce this bug with the test case reported by the original bug reporter.

![](https://lh3.googleusercontent.com/-uVZyHhaE5BA/V1mYfevMTYI/AAAAAAAAKGQ/8Rfg2KgTxyIfieoFvTRY5uTSF2rlcnzyQCLcB/s1600/shot.png)

**Comment by luigidellaquila** [comment]
Hi @mindnuts 

you're right, two clashing commit and a flawed test case...
Fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, fixed (again). The fix will be in 2.2.12

Thanks

Luigi

**Comment by mindnuts** [comment]
@luigidellaquila @lvca Sorry to say this is not fixed in 2.2.12 release as well.


![](http://pix.toile-libre.org/upload/original/1477040881.png)

**Comment by mindnuts** [comment]
@luigidellaquila Can you please acknowledge the bug and reopen it if possible?

**Comment by luigidellaquila** [comment]
Hi @mindnuts 

checking it now

**Comment by luigidellaquila** [comment]
Hi @mindnuts 

Sorry, but the result in the screenshot you sent seems to be correct...
The RIDs are sorted by cluster ID and then by cluster position.

Am I missing something?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @mindnuts 

ah, got it, but it's not how the `ORDER BY @RID` works...
To get what you need you can use a sequence http://orientdb.com/docs/2.2/Sequences-and-auto-increment.html

or you can create the class with only one cluster

Thanks

Luigi

**Comment by smolinari** [comment]
@mindnuts - to do Luigi's second suggestion, you'd need to set the global setting for the database with the following command.

`ALTER DATABASE MINIMUMCLUSTERS 1`

Do correct me if I am wrong Luigi.

Scott

**Comment by mindnuts** [comment]
@luigidellaquila From your perspective you are correct. But the original issue on Google Groups mentions the desired behaviour:

```
Return records from the class Profile in descending order of their creation
```

We also wanted similar behaviour and now i understand "Sequences" would be better suited as RIDs are not akin to auto increment IDs.

M

**Comment by smolinari** [comment]
The auto increment is the better solution, as soon as there is more than one cluster per class (which was how ODB worked up until version 2.2). Now, with multiple clusters per class, you get the different cluster ids mixed in (i.e. 15 and 16 in your example), which messes up the original insertion order (and why ODB is now faster, as it can do work like insertions in parallel).

Scott

**Comment by luigidellaquila** [comment]
Hi @mindnuts 

I'm closing this issue because it's technically fixed, but please feel free to comment if you need guidance on your use case

Thanks

Luigi
