### ISSUE TITLE
Concurrent Batch HTTP Updates Returning 409.

### ISSUE THREAD

**Issue by tomasaftalion** [orientechnologies/orientdb#6753]
## OrientDB Version, operating system, or hardware.
- v2.2
## Operating System
- Ubuntu 14.04
## Expected behavior and actual behavior

device (from-vertex) ----> phone number (to-vertex)

Using batch http request to generate various transactions with the following pattern:

/batch/db-name

```
{  "transaction" : True, 
    "operations" :  [
                               {"type" : "script", "language" : "sql", "script" : "command A"},
                               {"type" : "script", "language" : "sql", "script" : "command B"},
                               {"type" : "script", "language" : "sql", "script" : "command C"},
                               {"type" : "script", "language" : "sql", "script" : "command B"},
                               {"type" : "script", "language" : "sql", "script" : "command C"},
                              ....  one device (command A) has thousands of phone numbers (commands B & C)

                               {"type" : "script", "language" : "sql", "script" : "command A"}, 
                               ... new device
                           ]
}
```

sql commands:

```
UPDATE <from-vertex> MERGE <json-doc> UPSERT WHERE id = <from-vertex-id>;  (command A)

DELETE EDGE <edge> 
FROM (SELECT FROM <from-vertex> WHERE id = <from-vertex-id>)
TO (SELECT FROM <to-vertex> WHERE id = <to-vertex-id>) ; (command B)

CREATE EDGE <edge>
FROM (SELECT FROM <from-vertex> WHERE id = <from-vertex-id>)
TO (SELECT FROM <to-vertex> WHERE id = <to-vertex-id>)
SET <param1>=x, <param2>=y; (command C)
```

Note: from-vertex-id and to-vertex-id are unique.

This is the hack I created to update/create thousands of nodes and edges, one user at a time (each user has several devices <from-vertex> and phone numbers <to-vertex>). This pattern works ok when testing independently. However when running multiple threads I start getting 409 errors.  

I tried different combinations of graph consistency (tx, notx_sync_repair, notx_async_repair) and consistency types (version, content, automerge) but still no luck.  Expected 409 errors to disappear after modifying any of these.

I would need a reliable way of concurrently updating thousand of edges and vertexes using batch http. Either by better formed sql commands or by changing the settings. Any assistance much appreciated!

**Comment by lvca** [comment]
What kind of errors are those 409?

**Comment by tomasaftalion** [comment]
Hi, thanks for following up. To simplify, I'm trying to change the approach to follow http://orientdb.com/docs/2.2.x/SQL-batch.html.  Basically, I want to update/create one "from vertex", one "to vertex" and the edge between these two. By solving this I should be able to get rid of any concurrency problems.

My schema is:

```
CREATE CLASS class_a EXTENDS V;
CREATE PROPERTY class_a.id INTEGER;
CREATE INDEX class_a.id UNIQUE;

CREATE CLASS class_b EXTENDS V;
CREATE PROPERTY class_b.id INTEGER;
CREATE INDEX class_b.id UNIQUE;

CREATE CLASS edge_a EXTENDS E;
```

I'm trying to do:

`{ "transaction" : false, "operations" : [<operations-1>, <operation-2>,...]}`

where operations are:

` { "type" : "script", "language" : "sql", "script" : "<sql-commands>"}`

and the sql commands are:

```
BEGIN;
UPDATE class_a SET id = {from_id} WHERE id = {from_id};
UPDATE class_b SET id = {to_id} WHERE id = {to_id};
CREATE EDGE edge_a FROM (SELECT FROM class_a WHERE id = {from_id}) TO (SELECT FROM class_b WHERE id = {to_id});
COMMIT;
```

I'm getting "OCommandExecutionException: No edge has been created because no target vertices". Sorry for bringing up such a basic problem such as batch updating/creating edges and vertices. The updates are kind of meaningless but just as a skeleton example. I can't even make this example work but my aim is to:

update/create a from node
update/create a to node
update/create an edge between these two

**Comment by tomasaftalion** [comment]
Using "UPDATE vertex_a MERGE {"id": x} UPSERT WHERE id = x" to do the update/create vertex. This works. Trying to see if this approach solves the concurrency problem when updating thousand of edges concurrently.

**Comment by lvca** [comment]
Apart the problem I hope it's resolved with your last attempt, 2 things:

(1) Instead of creating an edge with 2 sub-queries, I suggest you to use this that is more efficient:

```
BEGIN;
LET $a = UPDATE class_a SET id = {from_id} WHERE id = {from_id} RETURN AFTER @this;
LET $b = UPDATE class_b SET id = {to_id} WHERE id = {to_id} RETURN AFTER @this;
CREATE EDGE edge_a FROM $a TO $b;
COMMIT;
```

(2) Why don't put all the statements in the same TX?

**Comment by tomasaftalion** [comment]
1) Thanks, yes, it does make things more efficient. (still not very fluent in the sql-ish idiom)
2) Not sure what the best split is. Sending many operations with a few statements or a few operations with many statements. Experienced that using few statements makes it a bit more manageable in case of conflicts (retry 50 would make it very expensive if there is a conflict). But again, not sure what is considered a "best practice".

There is very good documentation, however it would probably help to have common use cases exemplified. This might be one. In any case, thanks for the help!

**Comment by tomasaftalion** [comment]
sorry, correcting:

the suggested query throws:

```
com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalid script:Encountered " <LET> "let "" at line 1, column 20.
Was expecting one of:
    <IF> ...
    ";" ...
    <IF> ...
```
