### ISSUE TITLE
Very high memory consumption

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6922]
## OrientDB Version, operating system, or hardware.

2.2.12 (and later 2.2.14)

## Operating System
- [X ] Linux

## Expected behavior and actual behavior

Embedded Orient DB appears to be consuming between 2GB and 4GB of memory on our server. The net result is that our server gets stuck in major collections, CPU usage sky rockets, the application becomes totally unusable. We are not storing large objects in our Orient DB. Mostly list of email addresses and id's. 

We would not expect Orient DB to consume such a massive amount of memory. I wonder if Andrey's new refactoring of Orient locking schemes is causing this behaviour?

![orient](https://cloud.githubusercontent.com/assets/6212848/20345620/ae3ce4dc-ac00-11e6-99d8-4169546bc890.jpg)

## Steps to reproduce the problem

This is occuring in production, so its tough to advise how to reproduce. Please refer to snapshots below>

**Comment by prakashpandey** [comment]
I am using Orientdb JDBC in multi-threaded application , almost not storing anything in program.  

I provided 521mb heap(for testing), and I got heap after 2 hrs.

[This is my sudo code](http://stackoverflow.com/questions/40013369/orientdb-java-heap-error/)

I request people at orientdb , please release a tutorial for multithred system, doing (similar ) [this](http://stackoverflow.com/questions/40013369/orientdb-java-heap-error/)

**Comment by jamieb22** [comment]
The problem happens also with Orient DB 2.2.13. Our server locks up due to very high memory consumption of Orient DB after about two days of operation.

**Comment by laa** [comment]
Hi @jamieb22 how much storages do you open at once on single node, 66 ? Or that is only one storage ?

**Comment by jamieb22** [comment]
I am not sure exactly what you mean by "stores". We are opening about twenty of these: graphFactory = new OrientGraphFactory(database.location);
On many of these database, there is not much data being stored, on others there is more data.Why would adding more "stores"be a problem?

**Comment by jamieb22** [comment]
I have downgrade Orient DB to v2.2.11 in the interim.

**Comment by laa** [comment]
@jamieb22 by storage I mean database. I do not think that downgrade to 2.2.11 will solve the issue.
Each database has a local cache of loaded edges. I suggest you set ```sbtreebonsai.linkBagCache.size``` parameter to 5000 to fix this problem.

**Comment by jamieb22** [comment]
Lets assume that Orient DB consumes 2GB of memory. That means that Orient is consuming 100MB of memory per database. I don't even think many of the databases are that size. Seems excessive for a database.

**Comment by laa** [comment]
@jamieb22 according to you thread dump in picture you have 66 instances of edge managers, each database contains single edge manager. Could you look at heap dump and send me how much instances of OLocalPaginatedStorage do you have ? Because if we consume 2GB memory and we have 66 instances it gives about 30 MB of memory per each. Taking in account that only amount of code (I mean Java classes which need to be loaded) without all metadata which Java creates in memory is 11 M I do not think that 20 Mb is big memory consumption.

**Comment by jamieb22** [comment]
Andrey.. We have these other parameters set:
		OGlobalConfiguration.STORAGE_LOCK_TIMEOUT.setValue(300000);
		OGlobalConfiguration.RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(-1);
		OGlobalConfiguration.FILE_LOCK.setValue(false);
Are they correct? Should we apply any other settings besides:
	OGlobalConfiguration.SBTREEBONSAI_LINKBAG_CACHE_SIZE.setValue(5000);

**Comment by jamieb22** [comment]
Shouldn't the caches be shared across all databases?

**Comment by jamieb22** [comment]
Ok. That's about right, but most of those databases are not used / empty. Considering, I need to scale up to 500 databases on one server. What should the Orient DB settings be?

**Comment by laa** [comment]
@jamieb22 yes just add OGlobalConfiguration.SBTREEBONSAI_LINKBAG_CACHE_SIZE.setValue(5000); to the list.

**Comment by laa** [comment]
> Shouldn't the caches be shared across all databases?
Let me think may be that is possible.

**Comment by jamieb22** [comment]
Another idea: can't Orient Db have some kind of intelligent cache sizing? I.e. monitor performance of queries and scale the size of the cache dynamically taking into account available heap memory / upper bound limit. Clearly, if the major GC's are occuring Orient DB is pushing it too far on cache sizes, then logical step would be to reduce cache sizes dynamically.

**Comment by jamieb22** [comment]
A performance feature (i.e. cache) shouldn't get in the way of the proper functioning of a database.

**Comment by prakashpandey** [comment]
@laa I to have same memory problem(**memory heap**) with orientdb v2.2.13.

**In one comment you asked** "how much storages do you open at once on single node, 66 ? Or that is only one storage ?"

**In my use-case (50 threaded application) in every rest-request(my java application handle it), I receive data to store (vertex, edge name) + the database name in which it has to store .**

e.g  `'A' going to 'B' using honda_vr230 in 'ABC' database`

Then, I create `vertex A,B edge and  honda_vr230 edge between them` and **then commit, close connection object (JDBC driver).**

I receive this type of rest-request in 50 threaded system, 100-500 rest request per-second.

**Are these multiple connection leading to memory consumption (memory heap).**

Thanks..!

**Comment by taburet** [comment]
@prakashpandey as a temporary workaround you may lower the value of `sbtreebonsai.linkBagCache.size`/`OGlobalConfiguration.SBTREEBONSAI_LINKBAG_CACHE_SIZE`, that is the size of the per-database edge cache. Working on the global/unified edge cache now to put the total caches size under control.

**Comment by prakashpandey** [comment]
@taburet  these settings are under which file,

or

How to execute these setting using JDBC driver.

Thanks..!

**Comment by taburet** [comment]
Pass `-Dsbtreebonsai.linkBagCache.size=5000` to the JVM running JDBC driver.

**Comment by taburet** [comment]
Fixed in 2.2.x and develop branches. The fix will be available in the next 2.2.x series release. Closing.

**Comment by jamieb22** [comment]
I don't think this is not resolved. Our server ran out of heap space again with linkBagCache.size set to 5000. It takes a few days for this to happen.

**Comment by laa** [comment]
@jamieb22 did you try fix which is provided by @taburet  ? Could you provide us heap dump ?

**Comment by jamieb22** [comment]
I had to restart the server. Let me wait for a few more days. It is bound to run into memory problems again.

**Comment by jamieb22** [comment]
Andrey.. I sent through another snapshot of high memory consumption. I see 12,7m ReadWriteLocks in memory. Doesn't seem right to me.

**Comment by taburet** [comment]
@jamieb22 did you build fresh OrientDB server from sources of 2.2.x branch or just change `-Dsbtreebonsai.linkBagCache.size` setting?

**Comment by jamieb22** [comment]
This is a production server, so its too dangerous for us to run development code on it, even though the production of Orient db never seems to work reliably. We changed the value of -Dsbtreebonsai.linkBagCache.size

**Comment by taburet** [comment]
@jamieb22 seems like that cannot be fixed w/o upgrading to yet unreleased 2.2.14. Given 66 databases, each has associated edge cache (`OSBTreeCollectionManagerShared`) of size 5 000 (`linkBagCache.size`) in the worst case, that gives 330 000 of resident edge collections (`OSBTreeBonsaiLocal`), each has 64 locks (`ReentrantReadWriteLock`) on a typical 8-core setup, that gives 21 120 000 locks in the worst case.

Please lower `sbtreebonsai.linkBagCache.size` to 1000 as a temporary solution until 2.2.14 will be released, that should lower number of the locks to 4 224 000 in the worst case scenario.

**Comment by smolinari** [comment]
Does this mean, this "(non)limit" in the Limits section of the docs isn't really true?

>Databases: There is no limit to the number of databases per server or embedded. Users reported no problem with 1000 databases open

http://orientdb.com/docs/2.2.x/Limits.html

Scott

**Comment by jamieb22** [comment]
Most of those database have very little information in them. Only a few have many records.

**Comment by taburet** [comment]
@smolinari there is no limit, that's just a bug that is already fixed in 2.2.x branch, in 2.2.14 edge cache will use `cores * 8` locks per database, not `cores * 8 * linkBagCache.size` per database.

**Comment by jamieb22** [comment]
When will 2.2.14 be released?

**Comment by taburet** [comment]
@jamieb22 that's why we have only "12,7m ReadWriteLocks", not 21m as in the calculated worst case. Some of the edge caches are not filled entirely. Also, the number of edge collections is not in a one-to-one relation with the number of records, it's at least `2 * number_of_records * number_of_edge_properties_per_record`.

**Comment by taburet** [comment]
The 2.2.14 release is scheduled for the next week.

BTW, sorry guys, I mixed two issues in my mind, the first one is "1 edge cache per 1 database", in 2.2.14 there will be only one global cache instance, the second one is "`cores * 8` locks per single edge cache entry", in 2.2.14 there will be only one global locks array. So the total edge cache size will be really controlled by `linkBagCache.size`, and no locks will be allocated for each individual edge cache entry.

**Comment by smolinari** [comment]
@taburet - Is the no limit on databases is still true? 

And as I see it, the hardware will always represent some sort of limiting factor. There will be either not enough RAM, or CPU, or disk space, etc. I mean, 1000 databases open on a 512MB machine wouldn't really work well, if at all. Correct?

Scott

**Comment by taburet** [comment]
@smolinari that's hardware limits, not software ;) Seriously, there are always some hardware limits, the more effective we use resources on software side the more hardware limits are distant.

**Comment by smolinari** [comment]
@taburet - that is true. 

So the "software non-limit" on the number of open databases still stands?

Scott

**Comment by taburet** [comment]
@smolinari For sure, there are some practical limits, for example database instances are internally stored in a standard Java collection. As we all know, a standard Java collection can't store more than 2^31 items even theoretically at this moment, since it uses 32-bit signed int to report its size. We are constantly pushing all non-practical limits to practical ones, this issue is an example of such process.

**Comment by smolinari** [comment]
So, the limit on the number of databases run by one server would be 2,147,483,647? I know nobody would do that, but that is the theoretical limit?

Scott

**Comment by jamieb22** [comment]
Scott.... where is Orient 2.2.14?

**Comment by jamieb22** [comment]
Its been 10 days since  taburet commented 2.2.14 release is scheduled for the next week. Any ETA?

**Comment by taburet** [comment]
@jamieb22 sorry for the delay, pre-release testing revealed problems with 2.2.14, it's rescheduled to the end of this week.

**Comment by taburet** [comment]
@jamieb22 2.2.14 released today, please update and verify.

**Comment by jamieb22** [comment]
Thanks. I've updated it on the server and will report back.

**Comment by laa** [comment]
Hi @jamieb22 any updates on that ?

**Comment by jamieb22** [comment]
Its still too early to tell, but memory seems more stable. There appear to be other issues with the build however. We have several environments that whose databases wont open after upgrade. I am still trying to get further info. Also, another potential issue: https://github.com/orientechnologies/orientdb/issues/7053

**Comment by jamieb22** [comment]
I am still receiving OOM. The heap seems fine. This appears to be happening on direct memory. I have 32 GB of RAM. It seems Orient may be either consuming too much direct memory or there is a leak. Our server doesn't run for more than one hour before quitting. 

[37716.156330] Out of memory: Kill process 21889 (java) score 929 or sacrifice child
[37716.164218] Killed process 21889 (java) total-vm:135943936kB, anon-rss:31467364kB, file-rss:0kB

09-Jan-2017 21:37:37.233 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize
: readers != 0
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000007bf780000, 2097152, 0) failed; error='C
annot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2097152 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /mnt/data/var/opt/mailarchiva/tomcat/webapps/ROOT/WEB-INF/hs_err_pid1493.log

**Comment by jamieb22** [comment]
Startup options are as follows:
export JAVA_OPTS="-Dfile.encoding=UTF-8 -agentlib:yjpagent=onexit=memory,port=10001,disabletracing,disablealloc,probe_disable=*,dir=/mnt/archive-four -XX:HeapDumpPath=/mnt/archive-four -XX:MaxDirectMemorySize=512g"

**Comment by jamieb22** [comment]
These are the settings currently set:
	OGlobalConfiguration.NON_TX_RECORD_UPDATE_SYNCH.setValue(true); //Executes a synch against the file-system at every record operation. This slows down records updates but guarantee reliability on unreliable drives
		OGlobalConfiguration.STORAGE_LOCK_TIMEOUT.setValue(300000);
		OGlobalConfiguration.RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(-1);
		OGlobalConfiguration.FILE_LOCK.setValue(false);

**Comment by laa** [comment]
@jamieb22 this message "There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 2097152 bytes for committing reserved memory.
An error report file with more information is saved as:" means that you do not have 32 GB of RAM which you are trying to get to the system. It is not related to OrientDB. JVM tries to book 32 GB of RAM according to your settings and fails because a system does not allow to do that, what is an amount of RAM on your server how many other applications are running there? What is your disk cache size?

**Comment by cmassi** [comment]
Looking at memory in use by jvm, it seems to me that process is quite big (in use, anon-rss:31467364kB) and so cannot allocate a size of 2097152 bytes = 2GB, using address 0x00000007bf780000 = 33277083648 = 31735 MB 
See code http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/os/linux/vm/os_linux.cpp for mmap in os::Linux::commit_memory_impl

Virtual size is huge: total-vm:135943936kB = 132757 MB = 129 GB

Please provide /mnt/data/var/opt/mailarchiva/tomcat/webapps/ROOT/WEB-INF/hs_err_pid1493.log and check the line at the end of the log:
Memory: ..k page, physical ...k(...k free), swap ...k(...k free)

It is embedded in tomcat, so the leak (or simply the memory usage) could be everywhere; we are investigating on orientdb direct memory usage, per db.

Set the 2 max values (java heap+ direct mem) to be below 32g, so process do not use more than 32gb, and you avoid swapping. With one java process could be: -Xmx8g -Dstorage.diskCache.bufferSize=20480

Set java heap to a fixed size and limit direct too, e.g:

java 8 heap: -Xms8g -Xmn3m -Xmx8g -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:+UseCompressedOops -XX:CompressedClassSpaceSize=256m -XX:-UseAdaptiveSizePolicy -XX:InitialCodeCacheSize=96m -XX:ReservedCodeCacheSize=96m

direct: -XX:MaxDirectMemorySize=20g -Dstorage.diskCache.bufferSize=20480


You said "heap seems fine"; How do you verify ? Use -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -Xloggc:$ORIENTDB_HOME/log/gc_%p_%t.log and provide the file.

Check direct with jconsole, section MBeans, choose  com.orientechnologies.common.directmemory -> OByteBufferPoolMXBean -> Attributes
http://andreylomakin.blogspot.it/2016/05/how-to-calculate-maximum-amount-of.html

**Comment by jamieb22** [comment]
Do you have an email where I can send you the dump? It is very large.

**Comment by jamieb22** [comment]
Nevermind, here is the link to the hs_err_pid file. See: https://www.dropbox.com/s/bd7t95l25unmczk/hs_err_pid18498.log?dl=0. It is a different event from above, but no doubt same cause. The server crashes every hour or so. I worry that some of our Orient DB's are in a corrupted state, and therefore, somehow Orient code is not cleaning up after itself. Of course, this is just speculation at this point.

**Comment by jamieb22** [comment]
When connected to server using Yourkit, and OME happens, there is no unusual heap activity and heap stays well within range. As you can see from below,  6GB is allocated to heap. Max direct memory is set to 512G as per instructions from Andrey. We are not allocating any direct memory in our code, only Orient and Lucene as far as I know. Startup settings are as follows:

 ```
/opt/mailarchiva/server/../jre64/bin/java -Djava.util.logging.config.file=/var/o
pt/mailarchiva/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dfile.encoding=
UTF-8 -agentlib:yjpagent=onexit=memory,port=10001,disabletracing,disablealloc,probe_disable=*,dir=/mnt/archive-four -XX:HeapDump
Path=/mnt/archive-four -XX:MaxDirectMemorySize=512g -Dversion=enterpriseedition -Xmx6192m -Xms256m -XX:PermSize=128M -XX:MaxPerm
Size=192M -Djava.endorsed.dirs=/opt/mailarchiva/server/../server/endorsed -classpath /opt/mailarchiva/server/../server/bin/boots
trap.jar:/opt/mailarchiva/server/../server/bin/tomcat-juli.jar -Dcatalina.base=/var/opt/mailarchiva/tomcat -Dcatalina.home=/opt/
mailarchiva/server/../server -Djava.io.tmpdir=/var/opt/mailarchiva/tomcat/temp org.apache.catalina.startup.Bootstrap start
```

**Comment by taburet** [comment]
@jamieb22 what is the value of disk cache size setting (`storage.diskCache.bufferSize`, the actual value should be printed to the log at OrientDB startup)? Do you use some kind of a hot Tomcat application reloading w/o restarting the Tomcat? Is there a chance that OrientDB runtime is not shared across Tomcat applications bounds, if there are multiple application?

**Comment by cmassi** [comment]
From hs_err_pid18498.log

=========================================================================
# Native memory allocation (mmap) failed to map 12288 bytes for committing reserved memory.
...
#  Out of Memory Error (os_linux.cpp:2627), pid=18498, tid=0x00007f372884f700
...
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)

---------------  T H R E A D  ---------------

Current thread (0x0000000048c5f800):  JavaThread "DataHandler.getInputStream" [_thread_new, id=29425, stack(0x00007f372874f000,0x00007f3728850000)]
....
C  [libpthread.so.0+0x8184]  start_thread+0xc4

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
=>0x0000000048c5f800 JavaThread "DataHandler.getInputStream" [_thread_new, id=29425, stack(0x00007f372874f000,0x00007f3728850000)]
...
Heap:
 PSYoungGen      total 1826304K, used 487319K [0x000000073f000000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1548288K, 21% used [0x000000073f000000,0x000000075379a580,0x000000079d800000)
  from space 278016K, 54% used [0x00000007ae300000,0x00000007b774b820,0x00000007bf280000)
  to   space 273408K, 0% used [0x000000079d800000,0x000000079d800000,0x00000007ae300000)
 ParOldGen       total 4227072K, used 3469691K [0x000000063d000000, 0x000000073f000000, 0x000000073f000000)
  object space 4227072K, 82% used [0x000000063d000000,0x0000000710c5eeb0,0x000000073f000000)
 Metaspace       used 173216K, capacity 180287K, committed 181424K, reserved 1210368K
  class space    used 18930K, capacity 19789K, committed 20144K, reserved 1048576K
....
CodeCache: size=245760Kb used=166738Kb max_used=178855Kb free=79021Kb
....

uname:Linux 3.19.0-78-generic #86~14.04.1-Ubuntu SMP Tue Dec 6 17:58:35 UTC 2016 x86_64

-XX:MaxDirectMemorySize=512g -Dversion=enterpriseedition -Xmx6192m -Xms256m -XX:PermSize=128M -XX:MaxPermSize=192M

CPU:total 12 (16 cores per cpu, 2 threads per core) 

Memory: 4k page, physical 32947592k(254220k free), swap 0k(0k free)
========================================================================


Crashed while creating a new thread , and free memory is low 
Using java 8 the PermSize should be replaced by Metaspace and Classspace, according to current usage

Try to use something like

-Xms8g -Xmn3m -Xmx8g -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:+UseCompressedOops -XX:CompressedClassSpaceSize=128m -XX:-UseAdaptiveSizePolicy -XX:InitialCodeCacheSize=48m -XX:ReservedCodeCacheSize=48m -XX:ParallelGCThreads=8 -XX:MaxDirectMemorySize=20g -Dstorage.diskCache.bufferSize=20480

Then increase ram, if more direct is needed, and no leak is detected by orientdb

**Comment by jamieb22** [comment]
Let me give it a go and see if it helps! Thank you all for your suggestions

**Comment by jamieb22** [comment]
![orientshot](https://cloud.githubusercontent.com/assets/6212848/21820727/91b7e2ae-d779-11e6-89d1-8c6f4caa0a79.png)

The server just crashed again. If you take a look at the Yourkit shot above, Orient DB is found allocating directmemory in restoreQueueWithPageLoad method. Could it be that OrientDB is having trouble loading a large database, and in doing so it allocates a massive amount of direct memory and causes catastrophic crash.

**Comment by jamieb22** [comment]
I think it might be related to the Orient DB database below: (we have multiple databases, so its difficult to isolate the exact one that might be causing the problem)
`
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during local hash table creation DB name="archiva$da" at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.create(OLocalHashTable.java:195) at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.create(OHashTableIndexEngine.java:94) at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:1582) at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:237) ... 22 common frames omittedCaused by: com.orientechnologies.orient.core.exception.OStorageException: File with given name already exists but has different id 43 vs. proposed 1989533988011638870 DB name="archiva$da" at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.addFile(OWOWCache.java:482) at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.addFile(O2QCache.java:186) at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:415) at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:460) at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:404) at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:116) at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.create(OLocalHashTable.java:189) ... 25 common frames omitted`

**Comment by jamieb22** [comment]
As it happens, the database causing problems is no longer needed, thus I moved it out of service, and last night, not a single OME exception. Perhaps, its too early to say, but I believe this may be the source of the problem. I can supply the database, but it is very large. It looks to be a bug in Orient code. Can Orient DB team confirm?

**Comment by taburet** [comment]
@jamieb22 there should be nothing wrong with `restoreQueueWithPageLoad`, OrientDB restores the previous file cache state on the startup, this way the cache is filled with the hot data and ready to serve requests even after the cold restart.

Regarding `File with given name already exists` exception, seems like that is caused by the OOMs the database experienced in the past. If the database is not needed anymore, lets just wait.

Could you please provide the information I have requested in the last comment.

**Comment by jamieb22** [comment]
storage.diskCache.bufferSize is set to default value. I believe the default should be 4096.

**Comment by taburet** [comment]
@jamieb22 nope, the default is configured as described here: https://github.com/orientechnologies/orientdb/issues/7007#issuecomment-272139478

**Comment by taburet** [comment]
CC from #7007:

@weixliu @lodrion @jamieb22 Guys, I have analysed all the provided information from #7047, #6922 and #7007, what I have learned:

1. Direct memory usage reported by JVM doesn't go far beyond `storage.diskCache.bufferSize`, information from `java.nio:type=BufferPool,name=direct` and `com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean` match with some minor differences, so I assume there is no leaks in ODB's direct byte buffers management. If you spotted a counterexample, please capture the jmx beans information and send it to me along with the actual `storage.diskCache.bufferSize` value. If you unhappy with the default/auto-configured `storage.diskCache.bufferSize`, just set the value you like.

2. `NonHeapMemoryUsage` doesn't include direct memory allocations, but it includes things like memory allocated for the stacks of running threads. The value is correlated well with the number of running threads, with the default JVM setting of 1MB thread stack size and 2000 threads running the usage may easily go above 2GB. In the one of the provided thread dumps I spotted about 1800 active threads and only minority of them are related to ODB. Please capture a thread dump and send it me if you suspect ODB is guilty.

3. _Mapped_ memory "usage" reported by `java.nio:name=mapped,type=BufferPool` bean may go really high, that's because of ODB full text indexing, which uses Lucene, which uses memory mapped files to do its job. As Lucene developers [claim](http://blog.thetaphi.de/2012/07/use-lucenes-mmapdirectory-on-64bit.html), there is nothing dangerous in this situation.

**Comment by jamieb22** [comment]
Our server is still crashing due to OME. Still investigating. No threads seems stable throughout duration of execution. We prefer let the JVM set the default value for MaxDirectMemorySize.  We explicitly set OGlobalConfiguration.DISK_CACHE_SIZE to a suitable value. From our testing, if MaxDirectMemorySize is not specified, on a 6g heap, max direct memory will be set to 5.33g. According to our algorithm (in initProps() below), the cache size will be set to 1g. There should be no OME arises for Orient cache allocations. In this situation, shouldn't the Orient warning below be switched off?

2017-01-17 07:38:11.474 WARN  - MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=32174m option when you start the JVM. 

```
	private void initProps() {
		long maxMemory = Runtime.getRuntime().maxMemory();
		long maxMemoryGB = (maxMemory / 1024L / 1024L / 1024L);
		logger.debug("max memory {value='"+maxMemoryGB+"'}");
		maxMemoryGB = maxMemoryGB < 1 ? 1 : maxMemoryGB;
		long cacheSizeMb = 2 * 65536 * maxMemoryGB / 1024;
		logger.debug("est orient cache size {value='"+cacheSizeMb+"'}");
		long maxDirectMemoryMb =  VM.maxDirectMemory() / 1024L / 1024L;
		logger.debug("max direct memory {value='"+maxDirectMemoryMb+"'}");
		String cacheProp = System.getProperty("storage.diskCache.bufferSize");
	    if (cacheProp==null) {
	    	long maxDirectMemoryOrientMb = maxDirectMemoryMb / 3L;
			long cachSizeMb = cacheSizeMb  > maxDirectMemoryOrientMb ? maxDirectMemoryOrientMb : cacheSizeMb;
			cacheSizeMb =  (long)Math.pow(2, Math.ceil( Math.log(cachSizeMb)/ Math.log((2))));
	    	logger.debug("setting orient disk cache {value='"+cacheSizeMb+"mb'}");
	    	OGlobalConfiguration.DISK_CACHE_SIZE.setValue(cacheSizeMb);
	    } else {
	    	logger.debug("orient disk cache set {value='"+cacheProp+"mb'}");
	    }
		//orient locking bug https://github.com/orientechnologies/orientdb/issues/6797 workaround
		//Orient DB is coming to a halt due to excessive contention for locks over groups of records. 
		//Your resolution is to lock each record individually, so that it reduces contention, but has a 
		//side effect of a slow down in query performance.
		//System.setProperty("query.scanThresholdTip", "1");
		//System.setProperty("query.scanPrefetchPages", "0");
		//System.setProperty("query.scanBatchSize","1");
	}
```

**Comment by laa** [comment]
@jamieb22 
1. If you see "2017-01-17 07:38:11.474 WARN - MaxDirectMemorySize JVM option is not set or has an invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=32174m option when you start the JVM." it means that you do experience OOM exceptions. This warning implemented to warn users that they will exhibit OOMs with their settings. And as you mentioned you do exhibit OOM as listed in warning.
2.   You exhibit OOM because disk cache initialized before you set OGlobalConfiguration.DISK_CACHE_SIZE . I suggest you set disk cache value using system properties and check whether warning will gone.

**Comment by laa** [comment]
@jamieb22 
3. Yes, it is initiated by wrong value because of NPE. Suggest you to try to use system property value instead. I will fix this NPE today.

**Comment by laa** [comment]
@jamieb22 I do not suggest you to trust Java by setting direct memory settings to default because Java does not know how you are going to use direct memory and if Java and your opinions about cache size will be different you again will experience OOM exception

**Comment by jamieb22** [comment]
Andrey, I refer you to this article from your blog, wherein you state that the cache size can be changed dynamically:
```
Direct memory cache size may be changed at runtime since #OrientDB 2.2 version Since 2.1 (next hotfix) and 2.2 versions of  #OrientDB it will be possible to change size of direct memory disk cache at runtime. ..etc. etc.
```
I have done extensive testing. The Sun JVM sets DirectMemory to just short of heap size. In any case, we are limiting the cache size so that it never exceeds 1/3 of the DirectMemory allocation.

**Comment by jamieb22** [comment]
Andrey, the default Orient cache size is too high for embedded scenarios. You make a big assumption that there is no other software running on the machine. Our software gets installed along side many other products including Microsoft Exchange, etc. We are also embedded other libraries that use direct memory. We cannot have such a huge cache for one component. Our users frequently monitor memory usage, and complain if our application is too hungry on resources.

**Comment by cmassi** [comment]
The method sun/misc/VM.java.maxDirectMemory() should run: 
// -XX:MaxDirectMemorySize not given, take default
directMemory = Runtime.getRuntime().maxMemory()


If I use a server.sh with no MaxDirectMemorySize and Xms=Xmx=6g, it will complain with the WARN message, which is correct from the point of view of a java process running orientdb, but no explicit value will be set for XX option (if this is checked somewhere else):
$ jinfo -flag MaxDirectMemorySize pid_server
-XX:MaxDirectMemorySize=0

It will print: auto-config DISKCACHE=5,888MB (heap=5,888MB direct=5,888MB os=16,384MB), assuming maximum direct memory size equals to maximum JVM heap size

If you run MonBuffers, from Alan Bateman, you get current usage of direct

$ java -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/tools.jar:. MonBuffers pid_server
           mapped                        direct             
 Count   Capacity     Memory   Count   Capacity     Memory  
     0          0          0       3 1073872896 1073872896  

It would be better to set Xmx and MaxDirectMemorySize to explicit values, according to your needs

**Comment by jamieb22** [comment]
I am closing this issue since our problem is resolved.The resolution was to limit the cache size on startup.  I do however, still believe the default settings for Orient DB are far too aggressive. For reference, the working settings are as follows:

```
	static {
		OGlobalConfiguration.NON_TX_RECORD_UPDATE_SYNCH.setValue(true); //Executes a synch against the file-system at every record operation. This slows down records updates but guarantee reliability on unreliable drives
		OGlobalConfiguration.STORAGE_LOCK_TIMEOUT.setValue(300000);
		OGlobalConfiguration.RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(-1);
		OGlobalConfiguration.FILE_LOCK.setValue(false);
		OGlobalConfiguration.SBTREEBONSAI_LINKBAG_CACHE_SIZE.setValue(5000);
		OGlobalConfiguration.INDEX_IGNORE_NULL_VALUES_DEFAULT.setValue(true);
		OGlobalConfiguration.MEMORY_CHUNK_SIZE.setValue(32);
		long maxMemory = Runtime.getRuntime().maxMemory();
		long maxMemoryGB = (maxMemory / 1024L / 1024L / 1024L);
		maxMemoryGB = maxMemoryGB < 1 ? 1 : maxMemoryGB;
		long cacheSizeMb = 2 * 65536 * maxMemoryGB / 1024;
		long maxDirectMemoryMb =  VM.maxDirectMemory() / 1024L / 1024L;
		String cacheProp = System.getProperty("storage.diskCache.bufferSize");
	    if (cacheProp==null) {
	    	long maxDirectMemoryOrientMb = maxDirectMemoryMb / 3L;
			long cachSizeMb = cacheSizeMb  > maxDirectMemoryOrientMb ? maxDirectMemoryOrientMb : cacheSizeMb;
			cacheSizeMb =  (long)Math.pow(2, Math.ceil( Math.log(cachSizeMb)/ Math.log((2))));
	    	System.setProperty("storage.diskCache.bufferSize",Long.toString(cacheSizeMb));
	    	// the command below generates a NullPointerException in Orient 2.2.15-snapshot
	    	// OGlobalConfiguration.DISK_CACHE_SIZE.setValue(cacheSizeMb);
	    }
	}
```

**Comment by lightjiao** [comment]
@jamieb22 
hi, could you write a `orientdb-server-config.xml` file of your setting? or server.sh start parameter version.

thank you.

**Comment by marshal999** [comment]
@jamieb22 
ty very much, u r my saviour.
and this orientdb has worst documentation i've ever seen.
