### ISSUE TITLE
ODistributedOperationException issue in cluster mode

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7400]
## Expected behavior  
Can update or create edge successfully in cluster mode

## Actual behavior  
Can't update or create edge successfully in cluster mode.

## Steps to reproduce  
I have three masters named orientdb-server1,orientdb-server2,orientdb-server3.
I have tried to avoid update/create an edge in parallel in cluster model.
However I still encountered the below issue. I'm very strange why the version is not consistent among the masters in sequence??? I can provide more clues if you need, thank you.
Issue exception message: 
     2017-05-06 10:01:21.387 [pool-1-thread-16][c.m.o.t.OrientSqlUtils]INFO  create edge CallTo from #61:3488508 to #65:1753069 set callCnt = ?,callLen=?,callInCnt=?,callOutCnt=?,reportTime=? retry 100,class com.orientechnologies.orient.server.distributed.task.ODistributedOperationException,Quorum 2 not reached for request (id=0.16599762 task=tx[3]{record_create(#165:6093729 v.0),record_update(#61:3488508 v.227),record_update(#65:1753069 v.15)}). Elapsed=43ms. Servers in timeout/conflict are:
 - orientdb-server2: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #61:3488508 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v215 your=v227)
	DB name="sns"
 - orientdb-server3: com.orientechnologies.orient.core.exception.OConcurrentCreateException: Cannot create the record #165:6093729 because the assigned RID was #165:6102717 instead
	DB name="sns"
Received: 
 - orientdb-server3: com.orientechnologies.orient.core.exception.OConcurrentCreateException: Cannot create the record #165:6093729 because the assigned RID was #165:6102717 instead
	DB name="sns"
 - orientdb-server2: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #61:3488508 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v215 your=v227)
	DB name="sns"
 - orientdb-server1: TX[3]{#165:6093729 v.1,228,16}
	DB name="sns"
	DB name="sns"

**Comment by santo-it** [comment]
Hi,

Thanks for opening this. We fixed an issue related to concurrent edge update (from all master nodes) in version 2.2.19; wondering if you can give it a try and see if you can reproduce the problem?

**Comment by KishoDai** [comment]
Hi,
    Today I will have a try to see the result.
    Thank you very much.

**Comment by KishoDai** [comment]
Hi @prjhub,
     I have upgraded to 2.2.19. But the same issue is still happening at create edge frequently for the same vertex in cluster mode in sequence. 

Thank you
Kisho

**Comment by KishoDai** [comment]
Hi @santo-it,
      Added more.
      This issue is not always happening, Sometimes it's working.

Thank you,
Kisho

**Comment by ozgursucu** [comment]
Are there any updates for this issue? I am facing it as well.

**Comment by lvca** [comment]
Hi guys, this is not a bug. That exception extends `ONeedRetryException`, so the code should always be ready to collect it and retry the operation. This is the way OrientDB works: optimistic vs pessimistic. Take a look at: https://orientdb.com/docs/2.2/Concurrency.html

**Comment by ozgursucu** [comment]
Hi @lvca 
Then how can we manage the retry operation in a @Transactional method like provided in spring data orientdb?

**Comment by KishoDai** [comment]
Hi @Ivca,
      when batch to create edge under the multi-master, it will be happening.

**Comment by lvca** [comment]
@robfrank does Spring Data have a retry mechanism with annotations?
