### ISSUE TITLE
Cannot delete edge by date, but can select it by date.

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7407]
### OS: linux 

I can select:
`select * from workedOn where dt = "2017-05-02"`

Receiving: 
```
@rid #62:5
@version 1
@class workedOn
dt 2017-05-02 00:00:00
time 60 
out #42:3
in #25:0
```

but I cannot delete: 
`delete edge workedOn where dt = "2017-05-02"`

General delete method works: 
`delete workedOn where dt = "2017-05-02" unsafe`

Range delete works, for example:
`delete edge ed where date > "2015-02-01"`

There is no problem if we replace DATE with STRING :(

## Steps to reproduce  
I can provide repo to my project if anyone finds this interesting.

This should be quicker and easier though:

```
create class A extends V
create class B extends V
create class ed extends E
create property ed.date DATE

create vertex A
create vertex B

create edge ed FROM (SELECT FROM A) TO (SELECT FROM B) set date="2015-02-02"
delete edge ed where date="2015-02-02"

select * from ed
```

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

I fixed a similar issue just a couple of days ago. Any chance to try it on latest snapshot?

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.20-SNAPSHOT/

I did it and it seems to work fine. In case, the new release will be officially out in a few hours hopefully

Thanks

Luigi

**Comment by karolmie1** [comment]
I did try out latest snapshot. Studio works ok. With Java code I can delete edge, if parameter is a string.

I still encounter problems when passing util.Date or sql.Date or epoch as a parameter.

After creating entry using sql.Date (which works)
```
    val params = HashMap<String, any>()
    params.put("user", user)
    params.put("task", task)
    params.put("date", java.sql.Date.valueOf(date))
    params.put("time", time)
    val query = "CREATE EDGE ${TimeEntry.CLASS} FROM :task TO :user SET dt=:date, time=:time"

    val wrapper = QueryWrapper(query, params)
    graph.execute(wrapper)

```

I cannot find or delete the created entry using equality sign if I don't cast to string.
This does not work:

```
    params.put("date", java.sql.Date.valueOf(date)) // date is of type LocalDate. Don't work with util.Date, or epoch too
    val query = "DELETE EDGE ${TimeEntry.CLASS} WHERE dt=:date"
```

But this does:
```
    val query = "DELETE EDGE ${TimeEntry.CLASS} WHERE dt=`${date.toString()}`"
```


Actually this specific scenario I don't care for timezones and time. I would love to be able to simply use LocalDate instead.

I am able to make it work with string though, so it's not a big deal.

**Comment by luigidellaquila** [comment]
Thank you for the feedback @karolmie1 
I'll check the specific cases and let you know

Thanks

Luigi
