### ISSUE TITLE
java.lang.NullPointerException during INSERT INTO

### ISSUE THREAD

**Issue by Marchrius** [orientechnologies/orientdb#7604]
## Expected behavior  
New record into lh_item class

## Actual behavior  
```
$ANSI{green {db=main_database_v1}} Error on creating record in cluster: plocal cluster: lh_item
com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during record creation
  DB name="main_database_v1"
  Component Name="lh_item"
  at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createSinglePageRecord(OPaginatedCluster.java:636)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createDataRecord(OPaginatedCluster.java:513)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:478)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:3726)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:1191)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2211)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:241)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:171)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2758)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:63)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.saveRecord(OCommandExecutorSQLInsert.java:338)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.execute(OCommandExecutorSQLInsert.java:246)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3208)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
  at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
  at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
  at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.IllegalArgumentException
  at java.nio.Buffer.position(Buffer.java:244)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.readData(OWALPageChangesPortion.java:226)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.getIntValue(OWALPageChangesPortion.java:85)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getIntValue(ODurablePage.java:116)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPage.appendRecord(OClusterPage.java:103)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.addEntry(OPaginatedCluster.java:1930)
  at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createSinglePageRecord(OPaginatedCluster.java:627)
  ... 23 more
$ANSI{green {db=main_database_v1}} Exception `3706BA41` in storage `main_database_v1`
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #14:-1
  DB name="main_database_v1"
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:203)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2758)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:63)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.saveRecord(OCommandExecutorSQLInsert.java:338)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.execute(OCommandExecutorSQLInsert.java:246)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3208)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
  at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
  at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
  at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #14
  DB name="main_database_v1"
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2257)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:241)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:171)
  ... 16 more
Caused by: java.lang.NullPointerException
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2212)
  ... 18 more
$ANSI{green {db=main_database_v1}} Exception `3706BA41` in storage `main_database_v1`
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #14:-1
  DB name="main_database_v1"
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:203)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2758)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:63)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.saveRecord(OCommandExecutorSQLInsert.java:338)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.execute(OCommandExecutorSQLInsert.java:246)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3208)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
  at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
  at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
  at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #14
  DB name="main_database_v1"
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2257)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:241)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:171)
  ... 16 more
Caused by: java.lang.NullPointerException
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2212)
  ... 18 more
Internal server error:

java.lang.NullPointerException
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2212)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:241)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:171)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2758)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:63)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.saveRecord(OCommandExecutorSQLInsert.java:338)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.execute(OCommandExecutorSQLInsert.java:246)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3208)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
  at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
  at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
  at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```
## Steps to reproduce  
Not sure how to reproduce the issue. At the moment the only class that has this error is lh_item, other works fine.

The same behavior on both OrientDB Studio and OrientDB console

If more informations or more tests needed please let me know

**Comment by luigidellaquila** [comment]
Hi @Marchrius 

are you doing the insert via Studio? Do you have a db where to replicate the problem?

Thanks

Luigi

**Comment by Marchrius** [comment]
Hi @luigidellaquila 
I'm doing the insert from PHPOrient, Studio and Console. All have same issue. Unfortunately I don't have a database to replicate the problem since the problem is associated to the `lh_item` specific Class and if I make a new database with same structure It works.

**Comment by luigidellaquila** [comment]
Hi @Marchrius 

Any chance to just empty that db (delete all the records) and share it?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
An option could also be to drop all the other classes and share a minimal schema...

Thanks

Luigi

**Comment by Marchrius** [comment]
I'm sorry but I'm unable to share due to an internal policy. I know that at this point stack trace is useless without other informations but if you want I can run more test / operations on the database.

**Comment by laa** [comment]
Hi @Marchrius , the first thing which we need to know is a version of the product was used to create this database? Did you use the old version and just upgraded to the new one (if so which version was used) or you started to use 2.2.25 version at once?

**Comment by Marchrius** [comment]
@laa Sure, the original OrientDB version was 2.1 (specific don't know, It was created by an external web agency) then we upgraded to OrientDB 2.2.20 and in this days we started to use 2.2.25 as a possible solution to this problem.

**Comment by laa** [comment]
@Marchrius exactly as I suspected )) It was an issue in earlier versions when during the load part of the data in pages may be not flushed because of we missed part of new Java NIO contract.  This issue is already fixed you need just to make import/export of database from to JSON, and if I suppose during two weeks in production you will not have given issue, I suppose we may close it.

**Comment by Marchrius** [comment]
@laa just a question. Exactly, what version are you talking about? At the moment we restored a valid backup (saved the corrupted one) and all goes well but we want to fix it once and for all.

**Comment by laa** [comment]
@Marchrius if I remember it correctly all version prior 2.2.15 had this issue.

**Comment by laa** [comment]
Hi, @Marchrius any updates about this issue?

**Comment by laa** [comment]
Hi @Marchrius, any update on this issue?

**Comment by laa** [comment]
Hi @Marchrius, any update on this issue?

**Comment by laa** [comment]
Hi @Marchrius, any update on this issue?

**Comment by laa** [comment]
Closed because of no reply. But frankly speaking I think issue is fixed

**Comment by Marchrius** [comment]
Hi @laa, sorry for the delay but I was in vacation in these days.
The problem is not resolved (we are using a backup of the database with success).

There is another problem that my colleagues has had with OrientDB and I'm talking about the indexes of some vertexes/edges properties that has corrupted the database with problem in new row inserting in the vertexes / edges. This is a different problem from the primary one but has the same behavior (no record can be saved). I'll investigate and report more (and reliable) informations about this. In the meantime mark this problem as `resolved` or something else. Thank you for your time.

**Comment by laa** [comment]
Hi, @Marchrius thank you for feedback. We are waiting for your new issue. Once you will do it we will start to investigate it.

**Comment by Marchrius** [comment]
A fast feddback:

After command in the console `repair database --fix-graph --fix-links --fix-ridbags` seems that I can insert correctly a record in the broken vertex.
