### ISSUE TITLE
OrientDB shortestpath - specific edges

### ISSUE THREAD

**Issue by nksmjun** [orientechnologies/orientdb#7842]
### OS: windows10  

I have a Question about the shortestPath() Function of OrientDB.

I confirmed that the following functions are valid.

>select shortestPath('#9:1', '#15:1', 'BOTH','Friends').

However, in the above method, only 'Friends' can narrow down. For example, you want to do it with 'Friends' and 'Family'.

>select shortestPath('#9:1', '#15:1', 'BOTH',['Friends', 'Family']).

But it did not go well. Is it impossible to acquire the shortest path by specifying multiple edges?

I am sorry for poor English, I hope this problem will be solved.

**Comment by luigidellaquila** [comment]
Hi @nksmjun 

I just pushed a little addition, now it works fine. This fix will be released with 2.2.30

Thanks

Luigi

**Comment by nksmjun** [comment]
thank you !

**Comment by hossein-md** [comment]
Hi @luigidellaquila 
I think the [document](https://orientdb.com/docs/last/SQL-Functions.html#shortestpath) must be updated. According to the document:
>... edgeClassName, optional, is **the edge class** to traverse. By default all edges are crossed.

Thanks

**Comment by luigidellaquila** [comment]
Hi @hossein-md 

The docs seem to be correct, what is the wrong info...?

Thanks

Luigi

**Comment by hossein-md** [comment]
Hi @luigidellaquila 

It would be great if you mention that more than one edge type can be chosen.

Thanks

**Comment by luigidellaquila** [comment]
Oh, got it, thanks! I'll do it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hossein-md 

I just fixed the docs, it will be available in next few hours on the website

Thanks

Luigi

**Comment by hossein-md** [comment]
Hi @luigidellaquila 

Great!

Thanks

**Comment by suhassumukhv** [comment]
I'm using version 3.0.15,

I still have the same problem. 
The following works.
```
shortestpath($from, $to, "OUT", "EdgeClassA")
```

None of the following work. Gives an empty result.
```
shortestpath($from, $to, "OUT", ["EdgeClassA"])
shortestpath($from, $to, "OUT", ["EdgeClassA", "EdgeClassB"])
```
