### ISSUE TITLE
Incorrect java.lang.IllegalStateException: Cannot begin a transaction while a hook is executing

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8072]
### OS: Centos 

Hi,

Hooks is throwing a wrong and misleading exception when the code is actually correct.  In onRecordBeforeCreate if a vertex is created and the active record is modified before a call to a new vertex is called, then it'll throw an exception. but if the record, which has nothing to do with the new vertex is modified after the save of the new index, it will not throw an error.

`
    public RESULT onRecordBeforeCreate(final ODocument iDocument)
    {
         //creates another record for aggregation.
        OVertex indexVertex = database.newVertex(targetTable);
        indexVertex.setProperty("BLA", iDocument.getProperty("_id"));
        iDocument.setProperty("BLI", indexVertex);        //<<<<will throw the exception
        indexVertex.save();

        return RESULT.RECORD_CHANGED;
     }
`

However, the code below will not throw an error

`
    public RESULT onRecordBeforeCreate(final ODocument iDocument)
    {
         //creates another record for aggregation.
        OVertex indexVertex = database.newVertex(targetTable);
        indexVertex.setProperty("BLA", iDocument.getProperty("_id"));
        indexVertex.save();

        iDocument.setProperty("BLI", indexVertex);        //<<<<will not throw the exception
        return RESULT.RECORD_CHANGED;
     }
`

Regards,
Safwan

**Comment by ShakAttacked** [comment]
Hi,

I see that if I remove .save(), it doesn't cause an error.. if .save() is not needed, then should it do anything at all while in Hooks? or is it needed sometimes and if so, when?

Thanks,
Safwan

**Comment by laa** [comment]
@ShakAttacked I do not recommend you to create records in hooks, it will break db lifecycle, that is one of the reasons why we think remove hooks at all.

**Comment by ShakAttacked** [comment]
@laa 

Please don't. it's brilliant as it is.  If you remove it, we would lose a tremendous feature.  I've just moved all my code towards Hooks, if you remove it, I would be taking a step backwards.  Having hooks removes and solves way too many problems.

Thanks,
Safwan

**Comment by laa** [comment]
@ShakAttacked it creates tons of problems in production when users do not understand why data in indexes are lost and why txs are not rolled back completely. So likely we remove hooks, but I suppose we can find some kind of replacement. anyway having hooks which can do everything that possible in the middle of db lifecycle is not an option.

**Comment by lvca** [comment]
We're more thinking about speedup queries bypassing hooks for some cases (like a scan of entire clusters/classes). Hooks are fundamental and they will stay there.

**Comment by ShakAttacked** [comment]
@laa,

I didn't see your reply earlier.  We may need to have a conversation to better understand where it fails and I can give you my scenarios, so we can see what can be done.  I can give you 5 use cases of what is needed and why it's needed. we just have to find the right approach.

Thanks,
Safwan

**Comment by laa** [comment]
@ShakAttacked if @lvca writes that it will stay there it will stay there.

**Comment by ShakAttacked** [comment]
ok. thanks @laa,  how about the issue, can you give a hint on save() and why it throws this exception?

Thanks,
Safwan

**Comment by laa** [comment]
@ShakAttacked, the creation of records in hook, is prohibited because it breaks internal DB lifecycle. So you can not do that.

**Comment by ShakAttacked** [comment]
@laa so there is a bigger problem. I've successfully implemented it multiple times today and it's working.  And I hope it continues working.  

Safwan

**Comment by laa** [comment]
@ShakAttacked the problem with hooks, that we can control the execution of code inside of hooks. So we can limit code execution only on the limited degree. So sometimes this limitation works, sometimes probably as you mentioned it has issues and we do not prohibit actions correctly. In general creation of records inside of hooks is prohibited because they are not correctly handled by DB TX mechanics.

**Comment by ShakAttacked** [comment]
@laa, are you saying that a revert on the transaction would not revert these new records?

Safwan

**Comment by laa** [comment]
@ShakAttacked sometimes yes, because we can not always track them when they created inside of hooks.

**Comment by ShakAttacked** [comment]
@laa 

Are these actions safe?

- Query to find a record?
- Modifying another record than the one being modified?
- deleting another record?
- modifying lists/maps, etc?

Thanks,
Safwan

**Comment by laa** [comment]
By "modifying lists/maps, etc" what do you mean modifying those data where?

**Comment by ShakAttacked** [comment]
@laa fetch another record from the one being modified and modify the embeddedlist/map etc.

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

I just pushed a fix for this problem, please let me know if it completely covers your use case

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila,

I've updated to latest code and the problem is still there. Let's connect, I'll show you the scenario.  

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Sorry, my bad, I found a (trivial) problem and fixed it, now it should be OK. 
I just pushed the fix, please let me know if it works now

Thanks

Luigi
