### ISSUE TITLE
OrientDB static initialisation is not thread-safe

### ISSUE THREAD

**Issue by hakanai** [orientechnologies/orientdb#8425]
## Expected behavior  

It should be possible to create two independent databases in the same JVM, even if this occurs at the same time on two different threads.

## Actual behavior  

We attempt to create two databases, and occasionally get errors such as:

    java.lang.NullPointerException
    	at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.changeCacheSize(OEngineLocalPaginated.java:80)
    	at com.orientechnologies.orient.core.config.OGlobalConfiguration$1.change(OGlobalConfiguration.java:114)
    	at com.orientechnologies.orient.core.config.OGlobalConfiguration.setValue(OGlobalConfiguration.java:1032)
    	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaultDiskCacheSize(OMemoryAndLocalPaginatedEnginesInitializer.java:89)
    	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaults(OMemoryAndLocalPaginatedEnginesInitializer.java:63)
    	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.java:52)
    	at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.startup(OEngineLocalPaginated.java:56)
    	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:858)
    	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:466)
    	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:171)
    	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:425)
    	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:421)
    	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:357)
    	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:116)
    	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:71)
    	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:52)

## Steps to reproduce  

Since it's a multi-threading issue, I don't have a reliable reproduction.

## Investigation so far

If I look through the stack trace, for `OEngineLocalPaginated.changeCacheSize`, the null thing is surely `readCache`. You can tell that `readCache` would be `null` on construction, but that `startup()` has not yet been called.

Further down the stack, `OMemoryAndLocalPaginatedEnginesInitializer.initialize` is performing an unsafe static initialisation:

 ```
 /**
   * Initializes common parts of memory and plocal engines if not initialized yet. Does nothing if engines already initialized.
   */
  public void initialize() {
    if (initialized)
      return;
    initialized = true;

    configureDefaults();

    OMemory.checkDirectMemoryConfiguration();
    OMemory.checkByteBufferPoolConfiguration();
    OMemory.checkCacheMemoryConfiguration();

    OMemory.fixCommonConfigurationProblems();
  }
```

In this case, `initialized` should _not_ be set to `true` until _after_ initialisation. But proper locking should probably be put in place so that multiple threads don't simultaneously try to initialise all this static state.

Current master appears to have the same issue:

```
  /**
   * Initializes common parts of memory and plocal engines if not initialized yet. Does nothing if engines already initialized.
   */
  public void initialize() {
    if (initialized)
      return;
    initialized = true;

    configureDefaults();

    OMemory.checkCacheMemoryConfiguration();
    OMemory.fixCommonConfigurationProblems();
  }
```

**Comment by hakanai** [comment]
So I take it this has been fixed? Which version has the update?

**Comment by andrii0lomakin** [comment]
Hi @hakanai . We close old issues which were not been active for a long time. Seems like this issue is still actual for you, so I reopen it.

**Comment by tglman** [comment]
Hi,

This bug refer to "OEngineLocalPaginated" that has been removed from all the currently maintained release, and replaced with another component that seems to not have this problem, clonsing
