### ISSUE TITLE
Can not allocate space (error 95) for file ... using native Linux API, more slower methods will be used [OFileClassic]

### ISSUE THREAD

**Issue by crocy** [orientechnologies/orientdb#8431]
## Expected behavior  
No warnings when using the DB.

## Actual behavior  
```
2018-07-24 16:07:48:520 WARNI Can not allocate space (error 95) for file .../orientdb-3.0.4/databases/testDB/appsettingsdata_15_188.pcl using native Linux API, more slower methods will be used [OFileClassic]
2018-07-24 16:07:49:308 WARNI Can not allocate space (error 95) for file .../orientdb-3.0.4/databases/testDB/appsettingsdata_159.cpm using native Linux API, more slower methods will be used [OFileClassic]
```
(some parts of the path above have been omitted with `...`)

I keep getting a lot of these warnings on two different Linux OS-es (though both Debian based) since 3.0.2 (in all versions up to including 3.0.4) and I'm wandering is this really a problem/performance hit? No such warnings in 3.0.1.

## Steps to reproduce  
Just run the DB (non-embedded via `server.sh`) and write data to it. I'm using `spring-data-orientdb` in my app to access/use the DB but I don't think that's the reason for the warnings.

**Comment by crocy** [comment]
Aha, ok then, thanks :)

**Comment by zerovian** [comment]
this is a very ugly debug message.  Still present in 3.0.8.  please fix soon.

**Comment by crocy** [comment]
Yep, still constantly seeing it.

**Comment by laa** [comment]
@fabriziofortino are you sure that you have rights to modify directory content? The error which you reported above usually happens if you do not have sufficient rights.

**Comment by zerovian** [comment]
Also got this after d/l and unpack tar .gz file... server won't even start.

2018-10-24 09:10:47:364 INFO  Detected limit of amount of simultaneously open files is 10000,  limit of open files for disk cache will be set to 4488 [ONative]
2018-10-24 09:10:47:368 WARNI Value of limit of simultaneously open files is too small, recommended value is 262144 [ONative]
2018-10-24 09:10:47:390 INFO  Loading configuration from: /users/ps/mbaker/orientdb-3.0.9/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2018-10-24 09:10:47:650 INFO  OrientDB Server v3.0.9 - Veloce (build 31c46e541ec0f36ae15c3d98caea4a9662df0312, branch 3.0.x) is starting up... [OServer]
2018-10-24 09:10:47:728 INFO  8238637056 B/7856 MB/7 GB of physical memory were detected on machine [ONative]
2018-10-24 09:10:47:728 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2018-10-24 09:10:47:729 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2018-10-24 09:10:47:730 INFO  Path to 'memory' cgroup is '/' [ONative]
2018-10-24 09:10:47:738 INFO  Mounting path for memory cgroup controller is '/cgroup/memory' [ONative]
2018-10-24 09:10:47:740 INFO  cgroup soft memory limit is 9223372036854775807 B/8796093022207 MB/8589934591 GB [ONative]
2018-10-24 09:10:47:742 INFO  cgroup hard memory limit is 9223372036854775807 B/8796093022207 MB/8589934591 GB [ONative]
2018-10-24 09:10:47:742 INFO  Detected memory limit for current process is 8238637056 B/7856 MB/7 GB [ONative]
2018-10-24 09:10:47:744 INFO  JVM can use maximum 1963MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2018-10-24 09:10:47:745 INFO  Because OrientDB is running outside a container 12% of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLo                                                              calPaginatedEnginesInitializer]
2018-10-24 09:10:47:746 INFO  OrientDB auto-config DISKCACHE=4,951MB (heap=1,963MB os=7,856MB) [orientechnologies]
2018-10-24 09:10:47:751 INFO  System is started under an effective user : `mbaker` [OEngineLocalPaginated]
2018-10-24 09:10:47:867 INFO  WAL maximum segment size is set to 27 MB [OrientDBDistributed]
2018-10-24 09:10:47:868 INFO  Databases directory: /users/ps/mbaker/orientdb-3.0.9/databases [OServer]
2018-10-24 09:10:47:911 INFO  Creating the system database 'OSystem' for current server [OSystemDatabase]
2018-10-24 09:10:48:014 INFO  Direct IO for WAL located in /users/ps/mbaker/orientdb-3.0.9/databases/OSystem is allowed with block size 32768 bytes. [OCASDiskWriteAheadLog]
2018-10-24 09:10:48:015 INFO  Page size for WAL located in /users/ps/mbaker/orientdb-3.0.9/databases/OSystem is set to 32768 bytes. [OCASDiskWriteAheadLog]Can not open file using Linux API, Java FileChannel wi                                                              ll be used instead
com.sun.jna.LastErrorException: [22] Invalid argument
        at com.sun.jna.Native.invokeInt(Native Method)
        at com.sun.jna.Function.invoke(Function.java:419)
        at com.sun.jna.Function.invoke(Function.java:354)
        at com.sun.jna.Library$Handler.invoke(Library.java:244)
        at com.sun.proxy.$Proxy2.open(Unknown Source)
        at com.orientechnologies.common.jna.ONative.open(ONative.java:234)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:28)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Error during WAL writing
java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception during WAL flush
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1502)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.log(OCASDiskWriteAheadLog.java:1101)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:302)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:573)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:564)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:149)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:376)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:329)
        at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1236)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:156)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:45)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
        ... 7 more
Exception in thread 'OrientDB WAL Flush Task'
java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
        ... 7 more
Exception `45C2C807` in storage `plocal:/users/ps/mbaker/orientdb-3.0.9/databases/OSystem`: 3.0.9 - Veloce (build 31c46e541ec0f36ae15c3d98caea4a9662df0312, branch 3.0.x)
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.                                                              wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1505)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.log(OCASDiskWriteAheadLog.java:1101)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:302)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:573)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:564)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:149)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:376)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:329)
        at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1236)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:156)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:45)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1502)
        ... 13 more
Caused by: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
        ... 7 more
Exception `45C2C807` in storage `plocal:/users/ps/mbaker/orientdb-3.0.9/databases/OSystem`: 3.0.9 - Veloce (build 31c46e541ec0f36ae15c3d98caea4a9662df0312, branch 3.0.x)
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.                                                              wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1505)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.log(OCASDiskWriteAheadLog.java:1101)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:302)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:573)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:564)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:149)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:376)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:329)
        at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1236)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:156)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:45)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1502)
        ... 13 more
Caused by: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
        ... 7 more

2018-10-24 09:10:48:063 INFO  - shutdown storage: OSystem... [OrientDBDistributed]Error during server execution
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'OSystem'
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:331)
        at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1236)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:156)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:45)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem                                                              /OSystem.1.wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1505)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.log(OCASDiskWriteAheadLog.java:1101)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:302)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:573)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:564)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:149)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:376)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:329)
        ... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1502)
        ... 13 more
Caused by: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileAlreadyExistsException: /users/ps/mbaker/orientdb-3.0.9/databases/OSystem/OSystem.1.wal
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
        ... 7 more

**Comment by zerovian** [comment]
seems the file open fails on an NFS mount.  If I unpack and run this on a local disk... no problems.

this is what mount looks like where it fails:

isis:/users/ps on /users/ps type nfs (rw,vers=3,tcp,hard,nointr,rsize=32768,wsize=32768,sloppy,addr=xxx.xxx.xxx.xxx)

**Comment by zerovian** [comment]
Add -Dstorage.wal.allowDirectIO=false fixes the issue.

**Comment by fabriziofortino** [comment]
@laa it looks like a permission problem indeed. I think something has changed in the docker image because I use to run this without any problem. I have other applications (elasticsearch, zookeeper, kafka) where the volume is mounted in the exact same way without any issue.

My Docker version is 18.06.1-ce-mac73 (26764).

Here is the command I run to reproduce the issue:
```
docker run -i -p 2424:2424 -p 2480:2480 -v "$(pwd)"/odb/.volumes/orientdb/databases:/orientdb/databases -v "$(pwd)"/odb/.volumes/orientdb/backup:/orientdb/backup -e ORIENTDB_ROOT_PASSWORD=root orientdb
```

**Comment by myflowpl** [comment]
I have the similar error on my laptop with Ubuntu 18.04 and OrientDB 3.0.10 and java 1.8.0_111
run by command `bash bin/server.sh`
the serwer wont start at all
it works fine on my production server witch is debian
it's distribution downloaded as tar.gz and upacked

I tried to set all files permissions to 777 but no success
@zerovian suggestion works, but wish not to use it (definitely not on production)

any idea ???

### error log
```
2018-11-18 21:37:40:213 INFO  Detected limit of amount of simultaneously open files is 4096,  limit of open files for disk cache will be set to 1536 [ONative]
2018-11-18 21:37:40:218 WARNI Value of limit of simultaneously open files is too small, recommended value is 262144 [ONative]
2018-11-18 21:37:40:237 INFO  Loading configuration from: /home/piotr/www/slackmap/db/orientdb-3.0.10/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2018-11-18 21:37:40:541 INFO  OrientDB Server v3.0.10 - Veloce (build eac0654847df662ca03b45a6a5efa5eadd229ca5, branch 3.0.x) is starting up... [OServer]
2018-11-18 21:37:40:645 INFO  10358685696 B/9878 MB/9 GB of physical memory were detected on machine [ONative]
2018-11-18 21:37:40:646 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2018-11-18 21:37:40:647 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2018-11-18 21:37:40:648 INFO  Path to 'memory' cgroup is '/' [ONative]
2018-11-18 21:37:40:655 INFO  Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory' [ONative]
2018-11-18 21:37:40:656 INFO  cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2018-11-18 21:37:40:657 INFO  cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2018-11-18 21:37:40:658 INFO  Detected memory limit for current process is 10358685696 B/9878 MB/9 GB [ONative]
2018-11-18 21:37:40:660 INFO  JVM can use maximum 1963MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2018-11-18 21:37:40:660 INFO  Because OrientDB is running outside a container 12% of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2018-11-18 21:37:40:661 INFO  OrientDB auto-config DISKCACHE=6,730MB (heap=1,963MB os=9,878MB) [orientechnologies]
2018-11-18 21:37:40:670 INFO  System is started under an effective user : `piotr` [OEngineLocalPaginated]
2018-11-18 21:37:40:878 INFO  WAL maximum segment size is set to 4,690 MB [OrientDBDistributed]
2018-11-18 21:37:40:879 INFO  Databases directory: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases [OServer]
2018-11-18 21:37:41:034 INFO  Direct IO for WAL located in /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2018-11-18 21:37:41:035 INFO  Page size for WAL located in /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem is set to 4096 bytes. [OCASDiskWriteAheadLog]Can not open file using Linux API, Java FileChannel will be used instead
com.sun.jna.LastErrorException: [22] Invalid argument
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:419)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy2.open(Unknown Source)
	at com.orientechnologies.common.jna.ONative.open(ONative.java:234)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:28)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Error during WAL writing
java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception during WAL flush
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1502)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.flush(OCASDiskWriteAheadLog.java:1363)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:308)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:573)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:385)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:230)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:60)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:94)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:171)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:159)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:46)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
	... 7 more
Exception in thread 'OrientDB WAL Flush Task'
java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
	... 7 more
Exception `543364A9` in storage `plocal:/home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem`: 3.0.10 - Veloce (build eac0654847df662ca03b45a6a5efa5eadd229ca5, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:424)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:230)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:60)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:94)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:171)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:159)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:46)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1505)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.flush(OCASDiskWriteAheadLog.java:1363)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:308)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:573)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:385)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1502)
	... 13 more
Caused by: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
	... 7 more

2018-11-18 21:37:41:077 INFO  - shutdown storage: OSystem... [OrientDBDistributed]Error during WAL writing
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1985)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$writeBuffer$1(OCASDiskWriteAheadLog.java:2142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Exception in thread 'OrientDB WAL Write Task Thread)'
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$writeBuffer$1(OCASDiskWriteAheadLog.java:2142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread 'OrientDB WAL Flush Task'
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1985)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$writeBuffer$1(OCASDiskWriteAheadLog.java:2142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Error during server execution
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'OSystem'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:238)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:60)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:94)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:171)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:159)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:46)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:424)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:230)
	... 8 more
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1505)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.flush(OCASDiskWriteAheadLog.java:1363)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:308)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:573)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:385)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1502)
	... 13 more
Caused by: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.FileAlreadyExistsException: /home/piotr/www/slackmap/db/orientdb-3.0.10/databases/OSystem/OSystem.3.wal
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1860)
	... 7 more
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
ERROR: LogManager is shutdown, no logging is possible !!!
```

**Comment by fuss86** [comment]
We're experiencing the same issue in 3.0.13. OrientDb Server doesn't want to start.

**Comment by steve-todorov** [comment]
And the purposed `-Dstorage.wal.allowDirectIO=false` fix does not solve the issue as well. 

ping @laa any updates on this issue?

**Comment by carlspring** [comment]
Hi,

Is there any update on this? We're seeing a lot of these exceptions.

Please, advise!

Martin

**Comment by laa** [comment]
Should be fixed in latest 3.0.x appreciate if you check that.

**Comment by myflowpl** [comment]
Yes, works for me with orientdb version 3.0.18  on Ubuntu Windows Linux Subsystem, and on my production server with debian

Thanks a lot

**Comment by fabriziofortino** [comment]
@laa I am still getting this with v 3.0.29. See my comment here https://github.com/orientechnologies/orientdb/issues/8431#issuecomment-433367855 to reproduce it. I am running it on Docker for Mac
