### ISSUE TITLE
Invalid search query makes database unusable

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9498]
## Expected behavior 

To keep using a database although some queries throw errors.

## Actual behavior  

Passing an invalid search query using a Lucene index, the database gets unusable, every attempt to make a new connection fails until the server is restarted, logging this exception:

```
com.orientechnologies.orient.core.exception.OStorageException: Internal error happened in storage test please restart the server or re-open the storage to undergo the restore process and fix the error.
	DB name="test"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkErrorState(OAbstractPaginatedStorage.java:4876)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkOpenness(OAbstractPaginatedStorage.java:4867)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterIdByName(OAbstractPaginatedStorage.java:2105)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.getClusterIdByName(ODatabaseDocumentAbstract.java:794)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:129)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.loadMetadata(ODatabaseDocumentEmbedded.java:336)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.init(ODatabaseDocumentEmbedded.java:214)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:482)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:419)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1369)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:75)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
```

Restarting the server the problem goes away, until a new invalid query is executed. I don't know if only this type of invalid query causes the problem or there are another.

## Steps to reproduce  

It can be reproduced in a new database:

```
orientdb> create database remote:localhost/test root pass;

Creating database [remote:localhost/test] using the storage type [PLOCAL]...
Database created successfully.
Current database is: remote:localhost/test

orientdb {db=test}> create property V.text string;

Property created successfully.

orientdb {db=test}> create index lucene_index on V(text) FULLTEXT ENGINE LUCENE;

Creating index...
Created index successfully in 5,197000 sec(s).
```

In Java:

```java
        ODatabasePool opool = new ODatabasePool(orientDB, "test", "user", "pass");
        ODatabaseSession db = opool.acquire();
        try {
            System.out.println(db.query("select from V where search_index('lucene_index', :search) = true",
                    "inv?lid^").hasNext());
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        try {
            System.out.println("Using same session: " + (Long)db.query("select count(*) as c from V").next().getProperty("c"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        db.close();
        
        
        db = opool.acquire();
        try {
            System.out.println("Using another session: " + (Long)db.query("select count(*) as c from V").next().getProperty("c"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        db.close();
        
        opool.close();
        opool = new ODatabasePool(orientDB, "test", "user", "pass"); // <-- this line also throws a ODatabaseException, can't make new connection
        db = opool.acquire();
        try {
            System.out.println("Using another pool: " + (Long)db.query("select count(*) as c from V").next().getProperty("c"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        db.close();
        opool.close();
```

Output:

```
    Error parsing lucene query
        DB name="test"
        DB name="test"
    Internal error happened in storage test please restart the server or re-open the storage to undergo the restore process and fix the error.
        DB name="test"
        DB name="test"
    Internal error happened in storage test please restart the server or re-open the storage to undergo the restore process and fix the error.
        DB name="test"
        DB name="test"
```

Using version 3.1.5 the same code with the same database works fine:

```
    Error parsing lucene query
        DB name="test"
        DB name="test"
    Using same session: 0
    Using another session: 0
    Using another pool: 0
```

**Comment by kai-baumann** [comment]
I have a similiar issue with lucene queries which let the orient go into a limbo state where it does not accept any new connections.

**Comment by adepase** [comment]
I too have a similar issue, executing a lucene query directly from OrientDB Studio administration browse field and OrientDB version 3.1.9.
The query is the following:
`update morph set isTransport = (select from (select if(eval("isTransport.length()=3"),ifnull(isTransport[0],"P"),"P") as anim from (select unionall(isTransport).asString() as isTransport from (select distinct isTransport from synset where lemmas lucene $parent.$current.stem and lang='it' and id_lemma like 'n%')))) where simpleType='S' and not(stem like '%/%');`

Please note that I used this same query to update other fields (with other names, so imagine to replace "isTransport" with "isAnimated" or similar in the whole query) without issues, in the past.

I also tried to replace the old "lucene" syntax with the new search_class($parent.$current.stem) = true, but same result.
I'm running OrientDB under docker (on windows 10 pro) and using the following options:
```
ORIENTDB_OPTS_MEMORY -Xms1G -Xmx2G
JAVA_OPTS -XX:MaxDirectMemorySize=1g -Xmx2g
JAVA_HOME /usr/local/openjdk-8
LANG C.UTF-8
JAVA_VERSION 8u282
ORIENTDB_VERSION 3.1.9
```

The corresponding log:
```
mrjorient   | 2021-06-14 10:12:49:771 INFO  Storage 'plocal:/orientdb/databases/mrj' is opened under OrientDB distribution : 3.1.9 - Veloce (build ea45186cfc40f4e155ae967965d9772d6baefdb0, branch UNKNOWN) [OLoc
alPaginatedStorage]Exception `641B8CF3` in storage `plocal:/orientdb/databases/mrj`: 3.1.9 - Veloce (build ea45186cfc40f4e155ae967965d9772d6baefdb0, branch UNKNOWN)
mrjorient   | java.lang.NullPointerException
mrjorient   |   at com.orientechnologies.lucene.builder.OLuceneQueryBuilder.constructQueryString(OLuceneQueryBuilder.java:79)
mrjorient   |   at com.orientechnologies.lucene.builder.OLuceneQueryBuilder.query(OLuceneQueryBuilder.java:69)
mrjorient   |   at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getInTx(OLuceneFullTextIndexEngine.java:269)
mrjorient   |   at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.get(OLuceneFullTextIndexEngine.java:137)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:3206)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:3180)
mrjorient   |   at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.getRids(OLuceneIndexNotUnique.java:361)
mrjorient   |   at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchFromTarget(OLuceneSearchOnClassFunction.java:128)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OFunctionCall.executeIndexedFunction(OFunctionCall.java:166)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.executeIndexedFunction(OLevelZeroIdentifier.java:98)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.executeIndexedFunction(OBaseIdentifier.java:103)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBaseExpression.executeIndexedFunction(OBaseExpression.java:165)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OExpression.executeIndexedFunction(OExpression.java:302)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.executeIndexedFunction(OBinaryCondition.java:149)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.init(FetchFromIndexedFunctionStep.java:98)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.syncPull(FetchFromIndexedFunctionStep.java:38)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.fetchNextItem(FilterByClustersStep.java:58)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.hasNext(FilterByClustersStep.java:94)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:48)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:87)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:44)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:82)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:31)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:99)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.access$100(DistinctExecutionStep.java:15)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep$1.hasNext(DistinctExecutionStep.java:53)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:31)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.executeAggregation(AggregateProjectionCalculationStep.java:94)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.syncPull(AggregateProjectionCalculationStep.java:46)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SubQueryStep.syncPull(SubQueryStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SubQueryStep.syncPull(SubQueryStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OParenthesisExpression.execute(OParenthesisExpression.java:64)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OUpdateItem.applyUpdate(OUpdateItem.java:105)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.UpdateSetStep$1.next(UpdateSetStep.java:43)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:52)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:41)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:154)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
mrjorient   |   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:649)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:205)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:107)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:253)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:811)
mrjorient   |   at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
mrjorient   | Internal server error:
mrjorient   |
mrjorient   | java.lang.NullPointerException
mrjorient   |   at com.orientechnologies.lucene.builder.OLuceneQueryBuilder.constructQueryString(OLuceneQueryBuilder.java:79)
mrjorient   |   at com.orientechnologies.lucene.builder.OLuceneQueryBuilder.query(OLuceneQueryBuilder.java:69)
mrjorient   |   at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getInTx(OLuceneFullTextIndexEngine.java:269)
mrjorient   |   at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.get(OLuceneFullTextIndexEngine.java:137)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:3206)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:3180)
mrjorient   |   at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.getRids(OLuceneIndexNotUnique.java:361)
mrjorient   |   at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchFromTarget(OLuceneSearchOnClassFunction.java:128)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OFunctionCall.executeIndexedFunction(OFunctionCall.java:166)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.executeIndexedFunction(OLevelZeroIdentifier.java:98)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.executeIndexedFunction(OBaseIdentifier.java:103)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBaseExpression.executeIndexedFunction(OBaseExpression.java:165)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OExpression.executeIndexedFunction(OExpression.java:302)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.executeIndexedFunction(OBinaryCondition.java:149)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.init(FetchFromIndexedFunctionStep.java:98)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.syncPull(FetchFromIndexedFunctionStep.java:38)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.fetchNextItem(FilterByClustersStep.java:58)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.hasNext(FilterByClustersStep.java:94)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:48)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:87)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:44)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:82)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:31)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:99)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.access$100(DistinctExecutionStep.java:15)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep$1.hasNext(DistinctExecutionStep.java:53)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:31)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.executeAggregation(AggregateProjectionCalculationStep.java:94)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.syncPull(AggregateProjectionCalculationStep.java:46)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SubQueryStep.syncPull(SubQueryStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SubQueryStep.syncPull(SubQueryStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OParenthesisExpression.execute(OParenthesisExpression.java:64)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OUpdateItem.applyUpdate(OUpdateItem.java:105)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.UpdateSetStep$1.next(UpdateSetStep.java:43)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:52)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:41)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:154)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
mrjorient   |   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:649)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:205)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:107)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:253)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:811)
mrjorient   |   at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
mrjorient   | Exception `39A750D0` in storage `plocal:/orientdb/databases/mrj`: 3.1.9 - Veloce (build ea45186cfc40f4e155ae967965d9772d6baefdb0, branch UNKNOWN)
mrjorient   | com.orientechnologies.orient.core.exception.OStorageException: Internal error happened in storage mrj please restart the server or re-open the storage to undergo the restore process and fix the er
ror.
mrjorient   |   DB name="mrj"
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkErrorState(OAbstractPaginatedStorage.java:4897)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkOpenness(OAbstractPaginatedStorage.java:4888)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterIdByName(OAbstractPaginatedStorage.java:2124)
mrjorient   |   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.getClusterIdByName(ODatabaseDocumentAbstract.java:804)
mrjorient   |   at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:129)
mrjorient   |   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.loadMetadata(ODatabaseDocumentEmbedded.java:334)
mrjorient   |   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.init(ODatabaseDocumentEmbedded.java:212)
mrjorient   |   at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:458)
mrjorient   |   at com.orientechnologies.orient.core.db.OrientDBEmbedded.lambda$executeNoAuthorization$9(OrientDBEmbedded.java:1091)
mrjorient   |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
mrjorient   |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
mrjorient   |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
mrjorient   |   at java.lang.Thread.run(Thread.java:748)
mrjorient   | Caused by: java.lang.NullPointerException
mrjorient   |   at com.orientechnologies.lucene.builder.OLuceneQueryBuilder.constructQueryString(OLuceneQueryBuilder.java:79)
mrjorient   |   at com.orientechnologies.lucene.builder.OLuceneQueryBuilder.query(OLuceneQueryBuilder.java:69)
mrjorient   |   at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getInTx(OLuceneFullTextIndexEngine.java:269)
mrjorient   |   at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.get(OLuceneFullTextIndexEngine.java:137)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:3206)
mrjorient   |   at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:3180)
mrjorient   |   at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.getRids(OLuceneIndexNotUnique.java:361)
mrjorient   |   at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchFromTarget(OLuceneSearchOnClassFunction.java:128)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OFunctionCall.executeIndexedFunction(OFunctionCall.java:166)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.executeIndexedFunction(OLevelZeroIdentifier.java:98)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.executeIndexedFunction(OBaseIdentifier.java:103)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBaseExpression.executeIndexedFunction(OBaseExpression.java:165)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OExpression.executeIndexedFunction(OExpression.java:302)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.executeIndexedFunction(OBinaryCondition.java:149)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.init(FetchFromIndexedFunctionStep.java:98)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.syncPull(FetchFromIndexedFunctionStep.java:38)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.fetchNextItem(FilterByClustersStep.java:58)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.hasNext(FilterByClustersStep.java:94)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:48)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:87)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:44)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:82)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:31)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:99)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.access$100(DistinctExecutionStep.java:15)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep$1.hasNext(DistinctExecutionStep.java:53)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:31)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.executeAggregation(AggregateProjectionCalculationStep.java:94)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.syncPull(AggregateProjectionCalculationStep.java:46)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SubQueryStep.syncPull(SubQueryStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SubQueryStep.syncPull(SubQueryStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OParenthesisExpression.execute(OParenthesisExpression.java:64)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OUpdateItem.applyUpdate(OUpdateItem.java:105)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.UpdateSetStep$1.next(UpdateSetStep.java:43)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:52)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
mrjorient   |   at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:41)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:154)
mrjorient   |   at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
mrjorient   |   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:649)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:205)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:107)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:253)
mrjorient   |   at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:811)
mrjorient   |   at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)

```

**Comment by adepase** [comment]
Update: in my case, it was a row with stem null. So 
`where lemmas lucene $parent.$current.stem`
returned a null pointer. I think this is another bug, anyway, but the solution seems to be simple.
In the context of this thread, mine is just a type of "invalid" query and the workaround for me was easy (avoiding check with nulls), but it remains the original issue of a database to be restarted just because the query was "invalid".

**Comment by johny65** [comment]
This is also happening in version 3.2. The bug is much simpler to reproduce:

```sql
create class Test extends V;
create property Test.prop string;
create index theindex on Test(prop) FULLTEXT ENGINE LUCENE;
rebuild index theindex; /* this line breaks the server */
select from V; /* can't execute anymore until server is restarted */
```

**Comment by timw** [comment]
This is fixed in 3.1.x as of 3.1.13, more specifically it looks like it was resolved as a side-effect of 72e7d639a5f96be237dc49c43c815ef7c9255400.

It's still a bug in 3.2.x/develop, including 3.2.5.

**Comment by timw** [comment]
@laa - would it make sense to pull 72e7d639a5f96be237dc49c43c815ef7c9255400 up to 3.2?

**Comment by tglman** [comment]
Hi,

This should be already fixed in from 3.1.18 and 3.2.7, could you verify it?

Regards

**Comment by johny65** [comment]
> This should be already fixed in from 3.1.18 and 3.2.7, could you verify it?

Hi, I'm testing it in 3.2.7 but it still happens. I can still reproduce it in a new fresh database:

```sql
create property V.text string;
create index lucene_index on V(text) FULLTEXT ENGINE LUCENE;
select from V where search_class('*this breaks') = true; /* this line crashes the database */
select from V; /* not working until server restart */
```
Now when I want to restart the server, it crashes on shutdown:

```
2022-06-14 07:43:15:131 INFO  - shutdown storage: testdb... [OrientDBDistributed]
2022-06-14 07:43:15:131 SEVER Because of JVM error happened inside of storage it can not be properly closed [OEnterpriseLocalPaginatedStorage]
2022-06-14 07:43:15:230 INFO  Clearing byte buffer pool [Orient]#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8bc4d767c3, pid=13948, tid=14194
#
# JRE version: OpenJDK Runtime Environment (11.0.15+10) (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.15+10-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0xa17c3]malloc(): unsorted double linked list corrupted
```

**Comment by johny65** [comment]
I can confirm this is fixed is 3.2.8. Thanks!
